// 자동 생성 파일 — scraper/scrape_business.py 가 갱신합니다. 직접 수정 금지.
// 갱신 시각: 2026-08-10T02:09:25+00:00
const BUSINESS_LISTINGS_UPDATED_AT = "2026-08-10T02:09:25+00:00";
const BUSINESS_LISTINGS = [
  {
    "id": "biz-10932",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Jual Take Over Bisnis Online Profit Perkakas Rumah Tangga Sudah Berjalan di Jakarta",
    "category": "온라인 사업",
    "location": "Jakarta",
    "locationKo": "자카르타",
    "address": "Jl. Gn. Sahari No.1, RT.11/RW.6, Ancol, Kec. Pademangan, Jkt Utara, Daerah Khusus Ibukota Jakarta 14420",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 650 jt",
    "priceNum": 650000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Lokasi: Jl. Gn. Sahari No.1, RT.11/RW.6, Ancol, Kec. Pademangan, Jkt Utara, Daerah Khusus Ibukota Jakarta 14420 Keterangan: Jual Usaha Bisnis Online Perkakas Rumah Tangga Avg Omset 180jt/bulan Avg Net Profit 35jt/bulan Laporan keuangan lengkap Minim kompetitor Hanya perlu 1-2 karyawan Lokasi terkini...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6287883172107",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10932/jual-take-over-bisnis-online-profit-perkakas-rumah-tangga-sudah-berjalan-di-jakarta/",
    "postedAt": "2026-06-25T23:37:00",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10844",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "MURAH! (Take Over Usaha) DIJUAL Peternakan Ayam Petelur (Sekitar 60 Ribu Ekor) di Desa Kemiri Tangerang",
    "category": "농축산",
    "location": "Tangerang",
    "locationKo": "탕그랑",
    "address": "Desa Kemiri Tangerang",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 16 M",
    "priceNum": 16000000000,
    "established": null,
    "area": 32000.0,
    "floors": null,
    "description": "Lokasi: Desa Kemiri Tangerang Luas Tanah: 32.000 m2 Keterangan: https://youtube.com/shorts/BZK_8lLoLaU?si=MF-_C1uWsLnk_3Er SHM Pagar panel beton Genset 60 kva Listrik +/- 50.000 watt Mobil Mitsubishi double & engkel Jumlah ayam +/- 60 ribu ekor Produksi +/- 2 ton Dijual karena anaknya tidak mau mene...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6281213519229",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10844/murah-take-over-usaha-dijual-peternakan-ayam-petelur-sekitar-60-ribu-ekor-di-desa-kemiri-tangerang/",
    "postedAt": "2026-05-08T14:42:00",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10862",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Dijual Cepat 2.9 M Nego, Rumah Kost Dengan 11 Kamar di Ciputat Timur, 5 Menit ke Kampus UIN, Kondisi Kamar Full Semua Terisi - Potensi Income 200 Juta - 250 Juta per Tahun",
    "category": "숙박",
    "location": "Tangerang Selatan",
    "locationKo": "탕그랑 남부",
    "address": "Jl. Semanggi I, RT.002/RW.003, Cemp. Putih, Kec. Ciputat Tim., Kota Tangerang Selatan, Banten 15412",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2.90 M",
    "priceNum": 2900000000,
    "established": null,
    "area": 165.0,
    "floors": null,
    "description": "Lokasi: Jl. Semanggi I, RT.002/RW.003, Cemp. Putih, Kec. Ciputat Tim., Kota Tangerang Selatan, Banten 15412 Luas Tanah: 165 m2 Luas Bangunan: 165 m2 Keterangan: Ada 11 kamar dan semua dengan kamar mandi dalam, ac, water heater, meja, kursi. Full terisi 11 kamar. Potensi income 200 juta - 250 juta pe...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6281803518280",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10862/dijual-cepat-2-9-m-nego-rumah-kost-dengan-11-kamar-di-ciputat-timur-5-menit-ke-kampus-uin-kondisi-kamar-full-semua-terisi-potensi-income-200-juta-250-juta-per-tahun/",
    "postedAt": "2026-04-29T16:11:48",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10730",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Korean Salon Lokasi PIK Jakarta Utara - Kawasan Strategis Rukan Exclusive Dekat Golf Course - Lengkap dengan Peralatan dan Karyawan Terlatih",
    "category": "뷰티 & 살롱",
    "location": "Jakarta Utara",
    "locationKo": "자카르타 북부",
    "address": "Jl. Pantai Indah Kapuk Blok A. 27, RT.7/RW.2, Kamal Muara, Kecamatan Penjaringan, Jakarta Utara",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 650 jt",
    "priceNum": 650000000,
    "established": null,
    "area": 100.0,
    "floors": null,
    "description": "Lokasi: Rukan Exclusive, Jl. Pantai Indah Kapuk Blok A. 27, RT.7/RW.2, Kamal Muara, Kecamatan Penjaringan, Jakarta Utara, Daerah Khusus Ibukota Jakarta 14470 Luas Tanah: 100 m2++ Luas Bangunan: 100 m2++ Keterangan: Sudah lengkap dengan semua peralatan, karyawan (terlatih), sistem (rapi), gedung masi...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6285378967612",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10730/take-over-usaha-korean-salon-lokasi-pik-jakarta-utara-kawasan-strategis-rukan-exclusive-dekat-golf-course-lengkap-dengan-peralatan-dan-karyawan-terlatih/",
    "postedAt": "2026-02-03T11:24:08",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10744",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Korean Salon Lokasi Kawasan Strategis Greenlake City Boulevard Tangerang - Lengkap Semua Peralatan, Karyawan dan Sistem",
    "category": "뷰티 & 살롱",
    "location": "Tangerang",
    "locationKo": "탕그랑",
    "address": "Jl. Green Lake City Boulevard Green Lake City Ruko Wallstreet No.B23, Petir, Kec. Cipondoh, Kota Tangerang, Banten 15147",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 400 jt",
    "priceNum": 400000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Lokasi: Jl. Green Lake City Boulevard Green Lake City Ruko Wallstreet No.B23, Petir, Kec. Cipondoh, Kota Tangerang, Banten 15147 Luas Tanah: 100++ m2 Luas Bangunan: 100++ m2 Keterangan: Sudah lengkap dengan semua peralatan, karyawan (terlatih), sistem (rapih) Semua ruangan AC Perijinan lengkap, Reka...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6285378967612",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10744/take-over-usaha-korean-salon-lokasi-kawasan-strategis-greenlake-city-boulevard-tangerang-lengkap-semua-peralatan-karyawan-dan-sistem/",
    "postedAt": "2026-01-10T19:56:00",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10737",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Coffee Shop di Rawa Lumbu Bekasi - Masih Beroperasi",
    "category": "카페 & 레스토랑",
    "location": "Bekasi",
    "locationKo": "브카시",
    "address": "SPBU 34-17124, Jl. Cut Mutia No.77, RT.002/RW.001, Sepanjang Jaya, Rawa Lumbu, Bekasi, West Java 17114",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 210 jt",
    "priceNum": 210000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Lokasi: SPBU 34-17124, Jl. Cut Mutia No.77, RT.002/RW.001, Sepanjang Jaya, Rawa Lumbu, Bekasi, West Java 17114 Keterangan: Coffe shop sudah jalan tahun ke 3 Booth konsep container dengan bahan di lapisi kayu dan bisa di lepas, kwalitas bahan bagus (Baru di renovasi) Masa Sewa Lokasi 8 Bulan lagi dan...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6281513388377",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10737/take-over-usaha-coffee-shop-di-rawa-lumbu-bekasi-masih-beroperasi/",
    "postedAt": "2026-01-05T16:54:00",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10678",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Korean Salon, 4 Cabang Lokasi: Gading Serpong, Green Lake City, Pantai Indah Kapuk, Citra Garden City 6",
    "category": "뷰티 & 살롱",
    "location": "Tangerang",
    "locationKo": "탕그랑",
    "address": "Jl. Beryl Barat 2, Pakulonan Barat, Kecamatan Kelapa Dua, Kabupaten Tangerang, Banten 15810",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2.40 M",
    "priceNum": 2400000000,
    "established": null,
    "area": 400.0,
    "floors": null,
    "description": "Lokasi: Jl. Beryl Barat 2, Pakulonan Barat, Kecamatan Kelapa Dua, Kabupaten Tangerang, Banten 15810 Luas Tanah: 400m2 Luas Bangunan: 400m2 Keterangan: Open Rp 2,4 M (Nego) Sudah lengkap dengan semua peralatan, karyawan (terlatih), sistem (rapi), gedung masih 3 tahun lagi *baru diperpanjang Semua rua...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6285378967612",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10678/take-over-usaha-korean-salon-4-cabang-lokasi-gading-serpong-green-lake-city-pantai-indah-kapuk-citra-garden-city-6/",
    "postedAt": "2025-11-04T02:06:00",
    "lat": null,
    "lng": null
  },
  {
    "id": "biz-10490",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Warteg 24 Jam di Graha Raya Tangerang Lokasi Ramai",
    "category": "카페 & 레스토랑",
    "location": "Tangerang",
    "locationKo": "탕그랑",
    "address": "Graha Raya Ruko fortune 8 blok C no 18 Tangerang",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 400 jt",
    "priceNum": 400000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Lokasi: Graha Raya Ruko fortune 8 blok C no 18 Tangerang Keterangan: Warteg 24 jam baru dibuka Des 2024. Sistem yang digunakan sekarang adalah autopilot pembagian laba 50:50 dengan manajemen, namun jika mau kontrol 100% tanpa bagi laba juga bisa. Di area depan warteg sudah dipasang kanopi ada meja k...",
    "facilities": [
      "운영 중 사업체",
      "tempat-usaha.com 수집"
    ],
    "whatsapp": "+6281575018721",
    "c2c": false,
    "images": "🏪",
    "badge": "완전인수",
    "source": "tempat-usaha.com",
    "sourceUrl": "https://www.tempat-usaha.com/10490/take-over-warteg-24-jam-di-graha-raya-tangerang-lokasi-ramai/",
    "postedAt": "2025-05-08T19:26:00",
    "lat": null,
    "lng": null
  }
];
