// 자동 생성 파일 — scraper/scrape_indoweb.py 가 갱신합니다. 직접 수정 금지.
// 제목/지역/게시일/가격/면적/사실 요약만 보관한다.
// 글쓴이 이름·전화·이메일·메신저 ID 는 저장하지 않는다(MASK_RE 로 제거).
// 갱신 시각: 2026-08-11T22:04:20+07:00
const COMMUNITY_LISTINGS_UPDATED_AT = "2026-08-11T22:04:20+07:00";
const COMMUNITY_LISTINGS = [
  {
    "id": "iw-real_estate_mb-10424",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "MOI 끌라빠가딩 즉시 운영 가능한 카페 매장 양도",
    "category": "한인 커뮤니티 매물 · ruko",
    "dealType": "매매",
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "끌라빠 가딩",
    "address": "북 자카르타 끌라빠 가딩 모이",
    "description": "td>\n\r\n \r\n \r\n \r\n \r\n \r\n\r\n \n \n \n \n \n \r\n TheV Cafe\nRuko French Walk, Mall of Indonesia\nKelapa Gading, Jakarta Utara\nMall of Indonesia와 끌라빠가딩 중심 상권에 위치한 2층 루꼬형 F&B 카페 매장을 양도합니다.\n단순히 중고 장비만 판매하는 매물이 아닙니다.\n인테리어, 가구, 커피 및 주방 장비, 기본 운영 시스템과 남은 임대기간을 포함하여, 인수 후 별도의 대규모 공사 없이 바로 새로운 콘셉트로 운영할 수 있는 완성형 F&B 매장 양도 매물입니다.\n현재 브랜드를 그대로 이어갈 필요는 없으며, 인수자의 사업 방향에 따라 자유롭게 리브랜딩할 수 있습니다.\n주요 장점\nMall of Indonesia 및 Kelapa Gading 중심 상권\nRuko French Walk 내 2층 구조\nF&B 영업을 위한 내부 인테리어와 동선 완성\n대규모 신규 공사 없이 즉시 운영 가능\n커피숍, 베이커리, 디저트 전문점, 브런치 매장, 한식 디저트 카페, 쇼룸 등 다양한 업종으로 전환 가능\n신규 매장을 처음부터 구축하는 것보다 시간과 초기 비용 절감 가능\n인수 후 운영 및 리브랜딩을 위한 기본 인수인계 지원 가능\n양도 포함 항목\n커피 및 음료 장비\n상업용 커피머신\n커피 그라인더\n대용량 워터히터\n냉·온수 디스펜서\n제빙기 2대\n상업용 블렌더\nGalaxy Tab POS용 기기\n기타 음료 제조 장비 및 도구\n냉장·주방 장비\n냉장고\n냉동고\n디저트 쇼케이스\n주방 장비\n조리 및 음료 제조 도구\n카페 운영에 필요한 기본 비품\n인테리어 및 시설\n대형 에어컨 3대\n소형 에어컨 1대\nCCTV\n대리석 테이블\n의자\n소파\n가구 및 인테리어 비품\n공기청정기\n조명\n전기 및 수도 설치\n바와 주방 공간\n기존 리노베이션 시설 전체\n운영 관련 ...",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "28,000 USD (≈ Rp 448,000,000)",
    "priceNum": 448000000.0,
    "area": 200.0,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인",
      "면적/방: 200㎡, 1개"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_E3OR9eUw_thumb-608708320_e0o6kNPx_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.42.24_750x1002.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_crhtN3s1_thumb-608708320_HlCe39yo_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.42.46_750x997.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_sJNVkMdZ_thumb-608708320_QVa5gnwA_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.42.33_750x1003.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_n2iPNC6c_thumb-608708320_yS3QVORs_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.43.14_750x663.jpg"
    ],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10424&page=1",
    "postedAt": "2026-08-11T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10423",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "땅그랑 모던 골프장 근처 세차장 매각 합니다 오토로 운영하시기 적합한 세차장 매각",
    "category": "한인 커뮤니티 매물 · 세차장",
    "dealType": "매매",
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "탕그랑",
    "address": "땅그랑 찌뽄도 모던 골프장 근처",
    "description": "td>\n\r\n \r\n \r\n \r\n \r\n \r\n\r\n \n \n \n \n \n \n \r\n 탕그랑 찌뽄도 대형 세차장·디테일링 사업 양도\nMR CARWASH X LOUIS\nhttps://www.facebook.com/watch/?v=1522871062973188 ( 세차장 매각 홍보 동영상)\nCipondoh, Tangerang\n현재 정상 운영 중인 대형 세차장 및 차량관리 사업을 양도합니다.\n넓은 부지, 세차시설, 유압리프트, 디테일링 공간, 고객 대기실, 직원 숙소, 창고 및 운영 인력까지 갖춰져 있어, 인수자가 새로운 부지를 찾거나 시설을 처음부터 공사할 필요 없이 바로 운영을 이어갈 수 있습니다.\n이번 거래는 기존 회사나 회사 지분을 매각하는 방식이 아닙니다.\n토지 임대권, 세차장 시설, 장비, 브랜드, 고객 기반, 운영 시스템 및 합의된 영업자산을 인수하는 사업 및 자산 양도 방식입니다.\n위치 및 부지\nTangerang Cipondoh 지역\n주요 도로변 및 교차로 인근\n차량 통행량이 많은 입지\n약 700㎡ 이상의 넓은 운영 부지\n진입로 폭이 넓어 일반 승용차, SUV, 트럭 및 대형 차량 진입 가능\n침수 이력 없음\n우천 시에도 운영 가능한 구조\n약 5~6대의 대기 및 주차 공간\n세차 및 작업시설\n약 4대의 차량을 동시에 세차할 수 있는 작업 공간\n정상 작동 중인 유압리프트 3대\n차량 하부 세척 가능\n승용차, SUV, 오토바이 및 대형 차량 작업 가능\n고압세척기\n컴프레서\n에어블로어\n진공청소기\n기타 세차 운영 장비\n디테일링 및 코팅 전용 공간 2곳\n창고 2곳\n넓은 직원 숙소\n직원 숙소 약 20명 수용 가능 추정\nCCTV 및 기본 보안시설\n전기·수도·지하수·배수 시스템 완비\n캐노피와 바닥 및 고정 시설 구축 완료\n고객 편의시설\n일반적인 세차장보다 넓고 쾌적한 고객 대기공간을 보유하고 있습니다.\n에어...",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "50,000 USD (≈ Rp 800,000,000)",
    "priceNum": 800000000.0,
    "area": 750.0,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인",
      "면적/방: 750m2㎡, 6개"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_LiHKYSqm_2.jpeg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_pCj2nuNR_3.jpeg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_oiyXfBUs_44.jpeg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_3PqXdgUj_EC8AA4ED81ACEBA6B0EC83B7_2026-08-06_15.36.24.png",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=1854527193_o0gPQWTV_WhatsApp_Image_2026-07-30_at_15.31.12.jpeg"
    ],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10423&page=1",
    "postedAt": "2026-08-11T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-biz_promo-32737",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "카페 및 세차장 사업체 양도 / 자카르타·탕그랑 운영 사업체 2건 양도 MOI 끌라빠가딩 카페 매장 / 땅그랑 대형 세차장·…",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "업체 홍보·양도",
    "location": "Indonesia",
    "locationKo": "자카르타",
    "address": null,
    "description": "자카르타·탕그랑 운영 사업체 2건 양도 MOI 끌라빠가딩 F&B 매장 / 찌뽄도 대형 세차장·디테일링 센터 현재 인도네시아에서 실제 운영 중인 사업체 두 곳을 각각 양도합니다.\n 두 사업을 묶어서 일괄 매각하는 구조가 아니며, 카페와 세차장은 각각 별도로 인수할 수 있습니다. \n 이번 양도는 회사 지분이나 기존 법인 자체를 매각하는 거래가 아닙니다.\n각 사업장의 임대권, 시설, 장비, 운영 시스템 및 합의된 영업자산을 인수하는 사업자산 양도 방식 입니다.\n 운영자가 향후 공장 및 핵심 사업에 역량을 집중하기 위해 사업 포트폴리오를 재정비하는 과정에서 매각을 진행합니다.\n \n 매물 A MOI 끌라빠가딩 즉시 운영 가능한 F&B 매장 양도 TheV Cafe Ruko French Walk, Mall of Indonesia\nKelapa Gading, Jakarta Utara\n Mall of Indonesia와 끌라빠가딩 중심 상권에 위치한 2층 루꼬형 F&B 매장을 양도합니다.\n 단순히 중고 장비만 판매하는 매물이 아닙니다.\n 인테리어, 가구, 커피 및 주방 장비, 기본 운영 시스템과 남은 임대기간을 포함하여, 인수 후 별도의 대규모 공사 없이 바로 새로운 콘셉트로 운영할 수 있는 완성형 F&B 매장 양도 매물 입니다.\n 현재 브랜드를 그대로 이어갈 필요는 없으며, 인수자의 사업 방향에 따라 자유롭게 리브랜딩할 수 있습니다.\n 주요 장점 Mall of Indonesia 및 Kelapa Gading 중심 상권\n Ruko French Walk 내 2층 구조\n F&B 영업을 위한 내부 인테리어와 동선 완성\n 대규모 신규 공사 없이 즉시 운영 가능\n 커피숍, 베이커리, 디저트 전문점, 브런치 매장, 한식 디저트 카페, 쇼룸 등 다양한 업종으로 전환 가능\n 신규 매장을 처음부터 구축하는 것보다 ...",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [
      "https://indoweb.org/love/bbs/view_image.php?bo_table=biz_promo&fn=608708320_e0o6kNPx_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.42.24.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=biz_promo&fn=608708320_QVa5gnwA_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.42.33.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=biz_promo&fn=608708320_HlCe39yo_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.42.46.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=biz_promo&fn=608708320_yS3QVORs_EC8AA4ED81ACEBA6B0EC83B7_2026-07-30_12.43.14.jpg",
      "https://indoweb.org/love/bbs/view_image.php?bo_table=biz_promo&fn=608708320_GL2czSXI_EC8AA4ED81ACEBA6B0EC83B7_2026-08-06_15.36.24.jpg"
    ],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=biz_promo&wr_id=32737&page=1",
    "postedAt": "2026-08-06T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10419",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Majalengka 공장 매매",
    "category": "한인 커뮤니티 매물 · 공장",
    "dealType": "매매",
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "지역 미상",
    "address": "MAJALENGKA",
    "description": "td>\n\r\n \r\n \r\n \r\n \r\n \r\n\r\n \n \r\n Gerbang Tol Kertajati 에서 16km 거리 위치,\nLT : 21,201 M² (HGB)\nLB : 10,000 M² \nListrik : 550 KVA\n법인 소유\n연락처 : [연락처 비공개](whatsapp) \r\n \n\r\n \r\n \r\n \r\n \n\r\n\r\n \r\n \r\n \r\n 추천 0",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "1 USD (≈ Rp 16,000)",
    "priceNum": 16000.0,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인",
      "면적/방: ㎡"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10419&page=1",
    "postedAt": "2026-07-22T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-biz_promo-32732",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "반둥 한국 감성 디저트 카페 브랜드 매각 - 연매출 20억 이상",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "업체 홍보·양도",
    "location": "Indonesia",
    "locationKo": "반둥",
    "address": null,
    "description": "반둥에서 운영 중인 프리미엄 디저트 카페 브랜드입니다. 한국식 미니멀 감성과 트렌디한 공간 디자인을 바탕으로, 현지 MZ세대를 중심으로 꾸준한 고객층을 확보하고 있습니다. 현재 반둥 지역에 총 9개 매장을 운영하며, 홀 운영뿐 아니라 홀케이크, 커스텀 케이크, 배달 판매까지 안정적인 비즈니스 모델을 구축하고 있습니다.\n \n 브랜드 특징 \n - 한국 감성의 인테리어와 브랜딩\n \n - 저당(Less Sugar) 프리미엄 디저트 컨셉\n \n - 자체 레시피 기반의 케이크 및 디저트 판매\n \n - Halal 인증을 통한 폭넓은 현지 고객 확보\n \n - 9개(직영) 오프라인 매장 + 온라인 주문 시스템 운영\n - 대략 매출 20억, 영업이익 3억원을 내고 있습니다.\n \n \n 성장 가능성 \n 인도네시아는 K-푸드와 K-라이프스타일에 대한 관심이 지속적으로 증가하고 있으며, 한국 컨셉의 카페 브랜드에 대한 수요 역시 꾸준히 확대되고 있습니다. 이미 현지에서 브랜드 인지도와 운영 경험을 갖춘 만큼, 추가 출점 및 프랜차이즈 사업으로의 확장 가능성이 높은 브랜드입니다. 매출 또한 매년 약 2배씩 성장하였습니다.\n \n 이런 분께 추천드립니다.\n - 인도네시아 F&B 시장 진출을 고려하는 기업\n \n - 한국 카페 브랜드의 해외 진출 거점을 찾는 사업자\n \n - 이미 검증된 운영 시스템을 인수하여 빠르게 시장에 진입하고 싶은 투자자\n \n - 한국 감성 브랜드를 활용한 프랜차이즈 사업에 관심 있는 투자자\n \n - 관심 있으신 분께는 매출 자료, 운영 현황, 브랜드 자산, 매각 조건 등 상세 자료를 별도로 제공해드립니다.\n \n \n 연락은 카톡/WA으로 부탁드립니다! 010-6681-3349\n\r\n \r\n \r\n \r\n \r\n\r\n\r\n \r\n \r\n \r\n 좋아요 0",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=biz_promo&wr_id=32732&page=1",
    "postedAt": "2026-07-12T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-market-63690",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "식당/식품 | 반둥 한국 감성 디저트 카페 브랜드 매각 - 연매출 20억 이상",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "벼룩시장",
    "location": "Indonesia",
    "locationKo": "반둥",
    "address": null,
    "description": "td>\n\r\n \r\n \r\n \r\n\r\n \r\n\r\n \n \r\n 반둥에서 운영 중인 프리미엄 디저트 카페 브랜드입니다. 한국식 미니멀 감성과 트렌디한 공간 디자인을 바탕으로, 현지 MZ세대를 중심으로 꾸준한 고객층을 확보하고 있습니다. 현재 반둥 지역에 총 9개 매장을 운영하며, 홀 운영뿐 아니라 홀케이크, 커스텀 케이크, 배달 판매까지 안정적인 비즈니스 모델을 구축하고 있습니다.\n \n 브랜드 특징 \n - 한국 감성의 인테리어와 브랜딩\n \n - 저당(Less Sugar) 프리미엄 디저트 컨셉\n \n - 자체 레시피 기반의 케이크 및 디저트 판매\n \n - Halal 인증을 통한 폭넓은 현지 고객 확보\n \n - 9개(직영) 오프라인 매장 + 온라인 주문 시스템 운영\n - 대략 매출 20억, 영업이익 3억원을 내고 있습니다.\n \n \n 성장 가능성 \n 인도네시아는 K-푸드와 K-라이프스타일에 대한 관심이 지속적으로 증가하고 있으며, 한국 컨셉의 카페 브랜드에 대한 수요 역시 꾸준히 확대되고 있습니다. 이미 현지에서 브랜드 인지도와 운영 경험을 갖춘 만큼, 추가 출점 및 프랜차이즈 사업으로의 확장 가능성이 높은 브랜드입니다. 매출 또한 매년 약 2배씩 성장하였습니다.\n \n 이런 분께 추천드립니다.\n - 인도네시아 F&B 시장 진출을 고려하는 기업\n \n - 한국 카페 브랜드의 해외 진출 거점을 찾는 사업자\n \n - 이미 검증된 운영 시스템을 인수하여 빠르게 시장에 진입하고 싶은 투자자\n \n - 한국 감성 브랜드를 활용한 프랜차이즈 사업에 관심 있는 투자자\n \n - 관심 있으신 분께는 매출 자료, 운영 현황, 브랜드 자산, 매각 조건 등 상세 자료를 별도로 제공해드립니다.\n \n \n 연락은 카톡/WA으로 부탁드립니다! 010-6681-3349\n \r\n \r\n \n\r\n \r\n \n\r\n \n\r\n \r\n \r\n 키워드 \r\n \r\n...",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=market&wr_id=63690&page=1",
    "postedAt": "2026-07-11T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10409",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "한식당 매각",
    "category": "한인 커뮤니티 매물 · Ruko",
    "dealType": "매매",
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "지역 미상",
    "address": "Kelapa",
    "description": "td>\n\r\n \r\n \r\n \r\n \r\n \r\n\r\n \n \r\n 끌라빠 MOI근처 한식당(BBQ) 매각합니다.\n- 임대 26년 6월까지/ 연장 가능\n- 루코 3개 연결/ 총 4층\n- 1~2층: 식당/ 3층: 냉장창고 및 사무실/ 4층: 조리시설 및 사무실\n- 식당 운영을 위한 모든 설비(테이블별 후드 시설 포함) 완비\n문의 : [연락처 비공개]\n \n\r\n \r\n \r\n \r\n \n\r\n\r\n \r\n \r\n \r\n 추천 0",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "0 IDR",
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인",
      "면적/방: ㎡"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10409&page=1",
    "postedAt": "2026-05-11T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10390",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "토지매매",
    "category": "한인 커뮤니티 매물 · -",
    "dealType": "매매",
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "지역 미상",
    "address": "KP. Cikananga, Cikumpai/Campaka, Purwakarta",
    "description": "td>\n\r\n \r\n \r\n \r\n \r\n \r\n\r\n \n \n \r\n PT. Samwha Indonesia 공장 길목 입구에서 약 50m 거리.\n토지 면적 : 6,290 ㎡\n매물가 : Rp.2,250,000/㎡\n이메일([이메일 비공개])로 연락 주시면 답변 드리도록 하겠습니다. \r\n \n\r\n \r\n \r\n \r\n \n\r\n\r\n \r\n \r\n \r\n 추천 0",
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "2,250,000 IDR",
    "priceNum": 2250000.0,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인",
      "면적/방: ㎡"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [
      "https://indoweb.org/love/bbs/view_image.php?bo_table=real_estate_mb&fn=3530345531_ABDvh0pH_1988754754_0MgULT8D_ECA780EB8F84_EBA994EC9DB8.png"
    ],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10390&page=1",
    "postedAt": "2026-01-21T00:00:00+00:00",
    "indexOnly": false,
    "lat": null,
    "lng": null
  }
];
