// 자동 생성 파일 — scraper/scrape_indoweb.py 가 갱신합니다. 직접 수정 금지.
// 제목/지역/게시일/가격/면적/사실 요약만 보관한다.
// 글쓴이 이름·전화·이메일·메신저 ID 는 저장하지 않는다(MASK_RE 로 제거).
// 갱신 시각: 2026-08-12T21:16:50+07:00
const COMMUNITY_LISTINGS_UPDATED_AT = "2026-08-12T21:16:50+07:00";
const COMMUNITY_LISTINGS = [
  {
    "id": "iw-real_estate_mb-10424",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "MOI 끌라빠가딩 즉시 운영 가능한 카페 매장 양도",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "끌라빠 가딩",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10424&page=1",
    "postedAt": "2026-08-11T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10423",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "땅그랑 모던 골프장 근처 세차장 매각 합니다 오토로 운영하시기 적합한 세차장 매각",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "탕그랑",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10423&page=1",
    "postedAt": "2026-08-11T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-biz_promo-32737",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "카페 및 세차장 사업체 양도 / 자카르타·탕그랑 운영 사업…",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "업체 홍보·양도",
    "location": "Indonesia",
    "locationKo": "자카르타",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=biz_promo&wr_id=32737&page=1",
    "postedAt": "2026-08-06T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10419",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Majalengka 공장 매매",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "지역 미상",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10419&page=1",
    "postedAt": "2026-07-22T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-biz_promo-32732",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "반둥 한국 감성 디저트 카페 브랜드 매각 - 연매출 20억…",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "업체 홍보·양도",
    "location": "Indonesia",
    "locationKo": "반둥",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=biz_promo&wr_id=32732&page=1",
    "postedAt": "2026-07-12T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-market-63690",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "반둥 한국 감성 디저트 카페 브랜드 매각 - 연매출 20억 이상",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "벼룩시장",
    "location": "Indonesia",
    "locationKo": "반둥",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=market&wr_id=63690&page=1",
    "postedAt": "2026-07-11T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10409",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "한식당 매각",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "지역 미상",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10409&page=1",
    "postedAt": "2026-05-11T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  },
  {
    "id": "iw-real_estate_mb-10390",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "토지매매",
    "category": "한인 커뮤니티 매물",
    "dealType": null,
    "board": "부동산·업체 매매(주력)",
    "location": "Indonesia",
    "locationKo": "지역 미상",
    "address": null,
    "description": null,
    "whatsapp": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": null,
    "priceNum": null,
    "area": null,
    "floors": null,
    "established": null,
    "facilities": [
      "한인 커뮤니티",
      "원문 링크에서 상세 확인"
    ],
    "c2c": false,
    "images": "🇰🇷",
    "photoUrls": [],
    "badge": "커뮤니티 매물",
    "source": "indoweb.org",
    "sourceUrl": "https://indoweb.org/love/bbs/board.php?bo_table=real_estate_mb&wr_id=10390&page=1",
    "postedAt": "2026-01-21T00:00:00+00:00",
    "indexOnly": true,
    "lat": null,
    "lng": null
  }
];
