// 샘플 매물 데이터 - 인도네시아 현실적 시세 반영
const LISTINGS = [
  {
    id: 1,
    type: "bisnis",
    subtype: "akuisisi",
    title: "스페셜티 카페 - 가딩 세르퐁",
    category: "카페 & 레스토랑",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: "Rp 80 jt",
    monthlyRevenueNum: 80000000,
    profit: "22%",
    price: "Rp 500 jt",
    priceNum: 500000000,
    established: 2019,
    area: null,
    floors: null,
    description: "스페셜티 커피 카페. 좌석 40석, 고정 단골 고객 다수. 완전 인테리어 포함. 직원 5명 인계 가능.",
    facilities: ["인테리어 포함", "냉장장비 포함", "직원 인계 가능", "임대계약 2년 잔여"],
    whatsapp: "+6281234567001",
    c2c: false,
    images: "☕",
    badge: "완전인수",
    lat: -6.2311,
    lng: 106.6200
  },
  {
    id: 2,
    type: "ruko",
    subtype: "jual",
    title: "루코 3층 - BSD 시티",
    category: "루코",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 4,5 M",
    priceNum: 4500000000,
    established: 2015,
    area: 120,
    floors: 3,
    description: "BSD 시티 핵심 상권 루코. 1층 상가, 2-3층 사무실. 주차 2대. 은행/마트 인근. HGB 증서.",
    facilities: ["주차 2대", "3상 전기", "에어컨 포함", "CCTV"],
    whatsapp: "+6281234567002",
    c2c: false,
    images: "🏢",
    badge: "매매",
    lat: -6.3016,
    lng: 106.6538
  },
  {
    id: 3,
    type: "bisnis",
    subtype: "akuisisi",
    title: "파당 레스토랑 - 자카르타 셀라탄",
    category: "카페 & 레스토랑",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: "Rp 150 jt",
    monthlyRevenueNum: 150000000,
    profit: "18%",
    price: "Rp 1,2 M",
    priceNum: 1200000000,
    established: 2016,
    area: null,
    floors: null,
    description: "자카르타 셀라탄 파당 레스토랑. 좌석 80석. 가맹점 아님, 독립 운영. 주방장 및 직원 10명 인계.",
    facilities: ["주방장 인계", "레시피 포함", "브랜드 포함", "직원 10명"],
    whatsapp: "+6281234567003",
    c2c: false,
    images: "🍽️",
    badge: "완전인수",
    lat: -6.2615,
    lng: 106.8106
  },
  {
    id: 4,
    type: "properti",
    subtype: "jual",
    title: "풀빌라 발리 - 스미냑",
    category: "빌라 & 부동산",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 12 M",
    priceNum: 12000000000,
    established: 2018,
    area: 350,
    floors: 2,
    description: "스미냑 풀빌라. 3베드룸, 개인 수영장. 에어비앤비 수익 연 Rp 400jt. Leasehold 25년 잔여.",
    facilities: ["수영장", "3베드룸", "에어비앤비 등록", "컨시어지 서비스"],
    whatsapp: "+6281234567004",
    c2c: false,
    images: "🏖️",
    badge: "매매",
    foreignNote: "외국인 Leasehold 가능",
    lat: -8.3405,
    lng: 115.0920
  },
  {
    id: 5,
    type: "bisnis",
    subtype: "investor",
    title: "제조 공장 - 데포",
    category: "제조업",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: "Rp 500 jt",
    monthlyRevenueNum: 500000000,
    profit: "12%",
    price: "Rp 3 M (지분 30%)",
    priceNum: 3000000000,
    established: 2012,
    area: 800,
    floors: 1,
    description: "플라스틱 부품 제조공장. 연매출 Rp 6M. PT 법인 운영 중. 30% 지분 투자 유치. 수출 거래처 보유.",
    facilities: ["공장 부지 800m²", "기계설비 포함", "수출 거래처", "PT법인 운영중"],
    whatsapp: "+6281234567005",
    c2c: false,
    images: "🏭",
    badge: "투자유치",
    lat: -6.4025,
    lng: 106.8042
  },
  {
    id: 6,
    type: "ruko",
    subtype: "sewa",
    title: "루코 2층 임대 - 탕그랑",
    category: "루코",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 35 jt/tahun",
    priceNum: 35000000,
    established: 2017,
    area: 72,
    floors: 2,
    description: "탕그랑 시내 루코 임대. 1층 상가 40m², 2층 사무실 32m². 전용 화장실 2개. 연 임대료.",
    facilities: ["전기 2200W", "에어컨 기본 제공", "주차 1대", "보안실"],
    whatsapp: "+6281234567006",
    c2c: false,
    images: "🏬",
    badge: "임대",
    lat: -6.1702,
    lng: 106.6402
  },
  {
    id: 7,
    type: "bisnis",
    subtype: "akuisisi",
    title: "코인세탁 프랜차이즈 - 가딩 세르퐁",
    category: "프랜차이즈",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: "Rp 45 jt",
    monthlyRevenueNum: 45000000,
    profit: "28%",
    price: "Rp 280 jt",
    priceNum: 280000000,
    established: 2021,
    area: null,
    floors: null,
    description: "가딩 세르퐁 코인세탁 프랜차이즈. 기계 12대. 본사 지원 포함. 직원 1명. 운영 매우 간단.",
    facilities: ["세탁기 8대", "건조기 4대", "본사 AS 지원", "POS 시스템"],
    whatsapp: "+6281234567007",
    c2c: true,
    images: "👕",
    badge: "직거래",
    lat: -6.2380,
    lng: 106.6150
  },
  {
    id: 8,
    type: "properti",
    subtype: "jual",
    title: "택지 분양 - BSD 시티",
    category: "토지",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 8,5 M",
    priceNum: 8500000000,
    established: null,
    area: 420,
    floors: null,
    description: "BSD 시티 주거지역 택지. SHM 증서. 420m². 정방형 토지. 건축 허가 취득 가능. 주택 단지 내.",
    facilities: ["SHM 증서", "정방형 토지", "전기 인입 가능", "수도 인입 가능"],
    whatsapp: "+6281234567008",
    c2c: false,
    images: "🌿",
    badge: "매매",
    lat: -6.3100,
    lng: 106.6600
  },
  {
    id: 9,
    type: "bisnis",
    subtype: "akuisisi",
    title: "상업 주차장 - 자카르타 푸삿",
    category: "주차장",
    location: "Jakarta Pusat",
    locationKo: "자카르타 중부",
    monthlyRevenue: "Rp 120 jt",
    monthlyRevenueNum: 120000000,
    profit: "55%",
    price: "Rp 2,5 M",
    priceNum: 2500000000,
    established: 2018,
    area: 600,
    floors: null,
    description: "자카르타 푸삿 상업지구 주차장. 120대 수용. 자동 요금 시스템. 임대 계약 3년 잔여. 고수익.",
    facilities: ["120대 수용", "자동 요금 시스템", "CCTV 24시간", "입출차 게이트"],
    whatsapp: "+6281234567009",
    c2c: false,
    images: "🚗",
    badge: "완전인수",
    lat: -6.1944,
    lng: 106.8229
  },
  {
    id: 10,
    type: "ruko",
    subtype: "jual",
    title: "코너 루코 - 데포",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 2,8 M",
    priceNum: 2800000000,
    established: 2016,
    area: 90,
    floors: 2,
    description: "데포 코너 루코. 두 면 도로 접면. 유동인구 많음. 현재 미용실 임차 중 (월 Rp 8jt). HGB.",
    facilities: ["코너 위치", "임차인 있음", "월세 Rp 8jt", "도로 양면 접면"],
    whatsapp: "+6281234567010",
    c2c: true,
    images: "🏪",
    badge: "직거래",
    lat: -6.4100,
    lng: 106.8000
  },
  {
    id: 11,
    type: "bisnis",
    subtype: "investor",
    title: "뷰티 클리닉 - 자카르타 셀라탄",
    category: "뷰티 & 클리닉",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: "Rp 200 jt",
    monthlyRevenueNum: 200000000,
    profit: "20%",
    price: "Rp 800 jt (지분 25%)",
    priceNum: 800000000,
    established: 2020,
    area: null,
    floors: null,
    description: "자카르타 셀라탄 피부과 클리닉. 의사 2명, 스태프 6명. 25% 지분 투자. 추가 지점 오픈 계획.",
    facilities: ["의료장비 최신", "단골 고객 2000명", "SNS 팔로워 5만", "온라인 예약 시스템"],
    whatsapp: "+6281234567011",
    c2c: false,
    images: "💆",
    badge: "투자유치",
    lat: -6.2700,
    lng: 106.8150
  },
  {
    id: 12,
    type: "properti",
    subtype: "jual",
    title: "4층 사무용 빌딩 - 자카르타 바랏",
    category: "사무실 빌딩",
    location: "Jakarta Barat",
    locationKo: "자카르타 서부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 22 M",
    priceNum: 22000000000,
    established: 2010,
    area: 800,
    floors: 4,
    description: "자카르타 바랏 4층 사무용 빌딩. 각 층 200m². 엘리베이터 1기. 현재 입주율 75%. 월 임대수익 Rp 60jt.",
    facilities: ["엘리베이터", "발전기", "주차 20대", "SHM 증서"],
    whatsapp: "+6281234567012",
    c2c: false,
    images: "🏗️",
    badge: "매매",
    lat: -6.1675,
    lng: 106.7484
  },
  {
    id: 13,
    type: "bisnis",
    subtype: "akuisisi",
    title: "미니마트 편의점 - 탕그랑",
    category: "편의점 & 소매",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: "Rp 95 jt",
    monthlyRevenueNum: 95000000,
    profit: "15%",
    price: "Rp 400 jt",
    priceNum: 400000000,
    established: 2020,
    area: null,
    floors: null,
    description: "탕그랑 주거지역 미니마트. 독립 브랜드 (프랜차이즈 아님). POS 시스템, 냉장고 8대. 직원 3명.",
    facilities: ["POS 시스템", "냉장고 8대", "CCTV", "재고 포함"],
    whatsapp: "+6281234567013",
    c2c: false,
    images: "🛒",
    badge: "완전인수",
    lat: -6.1800,
    lng: 106.6300
  },
  {
    id: 14,
    type: "ruko",
    subtype: "jual",
    title: "루코 3층 - 자카르타 우타라",
    category: "루코",
    location: "Jakarta Utara",
    locationKo: "자카르타 북부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 5,2 M",
    priceNum: 5200000000,
    established: 2013,
    area: 150,
    floors: 3,
    description: "자카르타 우타라 항구 인근 루코. 무역 비즈니스에 최적. 창고 공간 포함. 화물차 접근 가능.",
    facilities: ["창고 공간 포함", "화물차 접근", "3상 전기 10KVA", "보안실"],
    whatsapp: "+6281234567014",
    c2c: false,
    images: "🏢",
    badge: "매매",
    lat: -6.1381,
    lng: 106.8572
  },
  {
    id: 15,
    type: "bisnis",
    subtype: "akuisisi",
    title: "피트니스 센터 - 가딩 세르퐁",
    category: "피트니스",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: "Rp 180 jt",
    monthlyRevenueNum: 180000000,
    profit: "25%",
    price: "Rp 1,5 M",
    priceNum: 1500000000,
    established: 2019,
    area: 500,
    floors: null,
    description: "가딩 세르퐁 프리미엄 피트니스 센터. 회원 800명. 최신 운동기구. 개인 PT 트레이너 5명.",
    facilities: ["최신 운동기구", "회원 800명", "PT 트레이너 5명", "탈의실/샤워"],
    whatsapp: "+6281234567015",
    c2c: false,
    images: "💪",
    badge: "완전인수",
    lat: -6.2250,
    lng: 106.6250
  },

  // ── 실제 매물 (rumah123.com 수집, 2026-06) ──────────────────────────

  // 탕그랑 / 가딩 세르퐁 / BSD / 알람 수테라
  {
    id: 16,
    type: "ruko",
    subtype: "jual",
    title: "루코 BSD City Alunara Society Hub",
    category: "루코",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,98 M",
    priceNum: 1980000000,
    established: 2024,
    area: 58,
    floors: 1,
    description: "BSD 시티 신규 루코. 36m² 토지, 58m² 건물. 톨 인접 전략적 위치. 분양 중.",
    facilities: ["신축", "톨 인접", "1층", "HGB 증서"],
    whatsapp: "+6281234567016",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3016, lng: 106.6538
  },
  {
    id: 17,
    type: "ruko",
    subtype: "jual",
    title: "루코 CBD Boulevard 가딩 세르퐁 4층",
    category: "루코",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 6,9 M",
    priceNum: 6900000000,
    established: 2022,
    area: 300,
    floors: 4,
    description: "가딩 세르퐁 CBD 대로변 4층 루코. 85m² 토지. 양방향 접근 가능. 한정 유닛.",
    facilities: ["대로변", "4층", "양방향 접근", "주차 포함"],
    whatsapp: "+6281234567017",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2311, lng: 106.6200
  },
  {
    id: 18,
    type: "ruko",
    subtype: "jual",
    title: "루코 Hive Terraza Park 가딩 세르퐁 3층",
    category: "루코",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,3 M",
    priceNum: 1300000000,
    established: 2023,
    area: 110,
    floors: 3,
    description: "가딩 세르퐁 현대적 3층 루코. 54m² 토지. 더블 볼륨 + 루프 테라스. 학교 인근.",
    facilities: ["더블볼륨", "루프테라스", "학교인근", "현대식 설계"],
    whatsapp: "+6281234567018",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2350, lng: 106.6180
  },
  {
    id: 19,
    type: "ruko",
    subtype: "jual",
    title: "루코 Maggiore Signature 알람 수테라 3층",
    category: "루코",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,4 M",
    priceNum: 3400000000,
    established: 2023,
    area: 199,
    floors: 3,
    description: "알람 수테라 프리미엄 루코. 72m² 토지. 라이프스타일 허브 내 앵커 테넌트 인접.",
    facilities: ["프리미엄", "앵커테넌트 인접", "라이프스타일허브", "3층"],
    whatsapp: "+6281234567019",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2200, lng: 106.6600
  },
  {
    id: 20,
    type: "ruko",
    subtype: "jual",
    title: "루코 Pasadena Square South 가딩 세르퐁",
    category: "루코",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 2,9 M",
    priceNum: 2900000000,
    established: 2023,
    area: 80,
    floors: 2,
    description: "가딩 세르퐁 빠르게 개발 중인 지역 모던 컨셉 루코. 58m² 토지.",
    facilities: ["모던컨셉", "2층", "개발 성장지역", "주차 포함"],
    whatsapp: "+6281234567020",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2400, lng: 106.6220
  },
  {
    id: 21,
    type: "ruko",
    subtype: "jual",
    title: "루코 Sorrento East 코너 가딩 세르퐁",
    category: "루코",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,1 M",
    priceNum: 3100000000,
    established: 2022,
    area: 110,
    floors: 2,
    description: "가딩 세르퐁 코너 유닛. 55m² 토지. 주차 6대 가능. 대로변.",
    facilities: ["코너유닛", "주차6대", "대로변", "2층"],
    whatsapp: "+6281234567021",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2290, lng: 106.6230
  },
  {
    id: 22,
    type: "ruko",
    subtype: "jual",
    title: "루코 대로변 알람 수테라 Rp 3,8M",
    category: "루코",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,8 M",
    priceNum: 3800000000,
    established: 2015,
    area: 217,
    floors: 3,
    description: "알람 수테라 대로변 정면 루코. 80m² 토지. 상업지구 인근. 즉시 입주 가능.",
    facilities: ["대로변정면", "상업지구인근", "즉시입주", "3층"],
    whatsapp: "+6281234567022",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2150, lng: 106.6550
  },
  {
    id: 23,
    type: "ruko",
    subtype: "jual",
    title: "루코 Sutera Niaga 3 알람 수테라 2층",
    category: "루코",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 2,38 M",
    priceNum: 2380000000,
    established: 2014,
    area: 140,
    floors: 2,
    description: "알람 수테라 2층 루코. 67m² 토지. 침수 없음, 즉시 사용 가능.",
    facilities: ["침수없음", "즉시사용", "2층", "HGB"],
    whatsapp: "+6281234567023",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2180, lng: 106.6520
  },
  {
    id: 24,
    type: "ruko",
    subtype: "jual",
    title: "루코 Boulevard 가딩 세르퐁 2층 대로",
    category: "루코",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 2,2 M",
    priceNum: 2200000000,
    established: 2016,
    area: 123,
    floors: 2,
    description: "가딩 세르퐁 메인 대로 2층 루코. 63m² 토지. 합리적 가격.",
    facilities: ["메인대로", "합리적가격", "2층", "주차"],
    whatsapp: "+6281234567024",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2320, lng: 106.6210
  },
  {
    id: 25,
    type: "ruko",
    subtype: "jual",
    title: "루코 Elevee Promenade 알람 수테라 3층",
    category: "루코",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 7,8 M",
    priceNum: 7800000000,
    established: 2020,
    area: 323,
    floors: 3,
    description: "알람 수테라 프리미엄 게이티드 커뮤니티 루코. 105m² 토지. 24시간 보안.",
    facilities: ["24시간보안", "게이티드커뮤니티", "프리미엄", "3층"],
    whatsapp: "+6281234567025",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2170, lng: 106.6580
  },

  // 데포 (Depok)
  {
    id: 26,
    type: "ruko",
    subtype: "jual",
    title: "루코 창고형 소완간 데포 2.5층",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3 M",
    priceNum: 3000000000,
    established: 2018,
    area: 380,
    floors: 2,
    description: "소완간 데포 루코 창고형. 152m² 토지. 임대 수익 즉시 가능. 성장 지역.",
    facilities: ["창고형", "152m²토지", "임대수익가능", "성장지역"],
    whatsapp: "+6281234567026",
    c2c: false,
    images: "🏭",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.4200, lng: 106.7900
  },
  {
    id: 27,
    type: "ruko",
    subtype: "jual",
    title: "루코 소완간 데포 2층 즉시입주",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,7 M",
    priceNum: 1700000000,
    established: 2019,
    area: 86,
    floors: 2,
    description: "소완간 데포 루코. 52m² 토지. 서향. 에어컨 3대. 즉시 입주.",
    facilities: ["서향", "에어컨3대", "즉시입주", "2층"],
    whatsapp: "+6281234567027",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.4150, lng: 106.7950
  },
  {
    id: 28,
    type: "ruko",
    subtype: "jual",
    title: "루코 베지 데포 시내중심 3층",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,8 M",
    priceNum: 3800000000,
    established: 2012,
    area: 196,
    floors: 3,
    description: "데포 시내 중심 루코. 130m² 토지. 교통 요지.",
    facilities: ["시내중심", "교통요지", "3층", "HGB"],
    whatsapp: "+6281234567028",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3900, lng: 106.8100
  },
  {
    id: 29,
    type: "ruko",
    subtype: "jual",
    title: "루코 마르곤다 데포 대로변 11층",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 4,7 M",
    priceNum: 4700000000,
    established: 2010,
    area: 90,
    floors: 11,
    description: "데포 마르곤다 라야 대로변 고층 루코. 185m² 토지. 번화가 핵심 위치.",
    facilities: ["대로변", "번화가핵심", "185m²토지", "고층"],
    whatsapp: "+6281234567029",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3950, lng: 106.8200
  },
  {
    id: 30,
    type: "ruko",
    subtype: "jual",
    title: "루코 치네레 데포 대형 3층",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,75 M",
    priceNum: 3750000000,
    established: 2014,
    area: 250,
    floors: 3,
    description: "치네레 라야 번화가 최적 위치 루코. 147m² 토지. 은행·클리닉·사무실 용도 적합.",
    facilities: ["번화가최적위치", "은행/클리닉용", "147m²토지", "3층"],
    whatsapp: "+6281234567030",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3700, lng: 106.7800
  },
  {
    id: 31,
    type: "ruko",
    subtype: "jual",
    title: "루코 치네레 몰 앞 3층 KPR가능",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 5,25 M",
    priceNum: 5250000000,
    established: 2015,
    area: 315,
    floors: 3,
    description: "치네레 몰 정면 3층 루코. 105m² 토지. KPR 대출 가능. 은행·클리닉·사무실 용도.",
    facilities: ["몰정면", "KPR가능", "105m²토지", "3층"],
    whatsapp: "+6281234567031",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3720, lng: 106.7820
  },
  {
    id: 32,
    type: "ruko",
    subtype: "jual",
    title: "루코 팡코란 마스 데포 3층 코스트 포함",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 2,5 M",
    priceNum: 2500000000,
    established: 2013,
    area: 140,
    floors: 3,
    description: "팡코란 마스 데포 3층 루코 + 코스트(기숙사) 함께 매각. 대로변. 154m² 토지.",
    facilities: ["코스트포함", "대로변", "154m²토지", "3층"],
    whatsapp: "+6281234567032",
    c2c: true,
    images: "🏪",
    badge: "직거래",
    source: "rumah123.com",
    lat: -6.4000, lng: 106.8050
  },
  {
    id: 33,
    type: "ruko",
    subtype: "jual",
    title: "루코 소완간 3.5층 DTC 인근",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,75 M",
    priceNum: 1750000000,
    established: 2020,
    area: 144,
    floors: 3,
    description: "소완간 DTC 인근 루코. 83m² 토지. 데사리 톨, 자카르타-데포 접근 용이.",
    facilities: ["DTC인근", "톨접근", "83m²토지", "3.5층"],
    whatsapp: "+6281234567033",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.4100, lng: 106.7920
  },

  // 브카시 (Bekasi)
  {
    id: 34,
    type: "ruko",
    subtype: "jual",
    title: "루코 Anagata 하라판 인다 브카시 2층",
    category: "루코",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 2,2 M",
    priceNum: 2200000000,
    established: 2019,
    area: 88,
    floors: 2,
    description: "하라판 인다 브카시 비즈니스 지구 전략적 루코. 57m² 토지.",
    facilities: ["비즈니스지구", "전략위치", "57m²토지", "2층"],
    whatsapp: "+6281234567034",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2349, lng: 106.9896
  },
  {
    id: 35,
    type: "ruko",
    subtype: "jual",
    title: "루코 Westfield Center Grand Wisata 브카시",
    category: "루코",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 2,8 M",
    priceNum: 2800000000,
    established: 2024,
    area: 134,
    floors: 2,
    description: "그랜드 위사타 브카시 신규 루코. 50m² 토지. DP 0%, KPR 가능, 부가세 면제.",
    facilities: ["신규분양", "DP0%", "KPR가능", "부가세면제"],
    whatsapp: "+6281234567035",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2500, lng: 107.0100
  },
  {
    id: 36,
    type: "ruko",
    subtype: "jual",
    title: "루코 코너 5층 메가불르바르 하라판 인다",
    category: "루코",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 13,5 M",
    priceNum: 13500000000,
    established: 2010,
    area: 1150,
    floors: 5,
    description: "하라판 인다 메가불르바르 코너 5층 대형 루코. 528m² 토지. 대로변.",
    facilities: ["코너대형", "528m²토지", "5층", "대로변"],
    whatsapp: "+6281234567036",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2380, lng: 106.9850
  },
  {
    id: 37,
    type: "ruko",
    subtype: "jual",
    title: "루코 자티와르나 브카시 3층 신축",
    category: "루코",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,5 M",
    priceNum: 1500000000,
    established: 2024,
    area: 50,
    floors: 3,
    description: "자티와르나 브카시 신축 루코. 80m² 토지. 전략적 대로 위치.",
    facilities: ["신축", "대로위치", "80m²토지", "3층"],
    whatsapp: "+6281234567037",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2700, lng: 106.9700
  },

  // 추가 지역 매물
  {
    id: 38,
    type: "ruko",
    subtype: "jual",
    title: "루코 Calico Grande 파사르 케미스 2층",
    category: "루코",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,59 M",
    priceNum: 1590000000,
    established: 2024,
    area: 96,
    floors: 2,
    description: "파사르 케미스 신규 루코. 48m² 토지. 부가세 면제 혜택.",
    facilities: ["신규", "부가세면제", "48m²토지", "2층"],
    whatsapp: "+6281234567038",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.1900, lng: 106.5800
  },
  {
    id: 39,
    type: "ruko",
    subtype: "jual",
    title: "루코 Ruko Baru 소완간 데포 2층 (가격인하)",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1,2 M",
    priceNum: 1200000000,
    established: 2023,
    area: 86,
    floors: 2,
    description: "소완간 데포 신규 루코. 52m² 토지. 남자카르타 톨 인접. Rp 1.5M에서 가격 인하.",
    facilities: ["가격인하", "톨인접", "52m²토지", "침수없음"],
    whatsapp: "+6281234567039",
    c2c: true,
    images: "🏬",
    badge: "직거래",
    source: "rumah123.com",
    lat: -6.4080, lng: 106.7960
  },
  {
    id: 40,
    type: "ruko",
    subtype: "jual",
    title: "루코 수크마자야 데포 2층 (임대중 Rp110jt/년)",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,9 M",
    priceNum: 3900000000,
    established: 2011,
    area: 180,
    floors: 1,
    description: "수크마자야 데포 임대중 루코. 90m² 토지. 연 임대수익 Rp 110jt. 즉시 수익형.",
    facilities: ["임대수익Rp110jt/년", "90m²토지", "즉시수익", "HGB"],
    whatsapp: "+6281234567040",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3900, lng: 106.8220
  },
  {
    id: 41,
    type: "ruko",
    subtype: "jual",
    title: "루코 Amara Residence 소완간 데포 (Free PPN)",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 1 M ~ 1,8 M",
    priceNum: 1400000000,
    established: 2024,
    area: 101,
    floors: 2,
    description: "소완간 데포 신규 분양 루코. 70-77m² 토지. DP 0%, 부가세 면제, IKEA 가구 3천만 루피아 증정.",
    facilities: ["DP0%", "부가세면제", "IKEA가구증정", "신규분양"],
    whatsapp: "+6281234567041",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.4120, lng: 106.7900
  },
  {
    id: 42,
    type: "ruko",
    subtype: "jual",
    title: "루코 린보 치네레 데포 3층 고수익 투자",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 5,9 M",
    priceNum: 5900000000,
    established: 2016,
    area: 200,
    floors: 3,
    description: "린보 치네레 데포 전략적 루코. 300m² 토지. 높은 투자 수익률 예상.",
    facilities: ["300m²토지", "고수익예상", "전략위치", "3층"],
    whatsapp: "+6281234567042",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3750, lng: 106.7780
  },
  {
    id: 43,
    type: "ruko",
    subtype: "jual",
    title: "루코+코스트 수크마자야 데포 대로변 투자형",
    category: "루코",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 4 M",
    priceNum: 4000000000,
    established: 2012,
    area: 750,
    floors: 3,
    description: "수크마자야 데포 대로변 루코 + 코스트(기숙사) 운영 중. 300m² 토지. 다목적 투자형.",
    facilities: ["코스트운영중", "300m²토지", "대로변", "다목적"],
    whatsapp: "+6281234567043",
    c2c: false,
    images: "🏭",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.3920, lng: 106.8180
  },

  // 자카르타 동부 추가
  {
    id: 44,
    type: "ruko",
    subtype: "jual",
    title: "루코 자카르타 동부 상업지구 2층",
    category: "루코",
    location: "Jakarta Timur",
    locationKo: "자카르타 동부",
    monthlyRevenue: null, monthlyRevenueNum: null, profit: null,
    price: "Rp 3,5 M",
    priceNum: 3500000000,
    established: 2015,
    area: 120,
    floors: 2,
    description: "자카르타 동부 상업지구 루코. 교통 편리. 주변 대형마트, 학교, 병원 인접.",
    facilities: ["교통편리", "대형마트인접", "2층", "HGB"],
    whatsapp: "+6281234567044",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "현지조사",
    lat: -6.2250, lng: 106.9004
  },
  {
    id: 45,
    type: "bisnis",
    subtype: "akuisisi",
    title: "버블티 카페 - 탕그랑 알람 수테라",
    category: "카페 & 레스토랑",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: "Rp 55 jt",
    monthlyRevenueNum: 55000000,
    profit: "24%",
    price: "Rp 350 jt",
    priceNum: 350000000,
    established: 2022,
    area: null,
    floors: null,
    description: "알람 수테라 버블티 카페. 쇼핑몰 내 입점. 좌석 30석. 젊은 층 유동인구 多. 프랜차이즈 아님.",
    facilities: ["쇼핑몰 내", "인테리어 포함", "주방기기 포함", "SNS 마케팅 포함"],
    whatsapp: "+6281234567045",
    c2c: false,
    images: "🧋",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2200, lng: 106.6600
  },

  // ── 추가 매물 id 46~105 ─────────────────────────────────────────────

  // 카페 & 레스토랑
  {
    id: 46,
    type: "bisnis",
    subtype: "akuisisi",
    title: "브런치 카페 - 자카르타 셀라탄 블록엠",
    category: "카페 & 레스토랑",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: "Rp 95 jt",
    monthlyRevenueNum: 95000000,
    profit: "20%",
    price: "Rp 650 jt",
    priceNum: 650000000,
    established: 2020,
    area: null,
    floors: null,
    description: "블록엠 상권 브런치 카페. 좌석 50석. SNS 팔로워 3만. 직원 6명, 주방장 포함 인계.",
    facilities: ["인테리어 포함", "주방기기 포함", "SNS 채널 인계", "임대계약 18개월 잔여"],
    whatsapp: "+6281234567046",
    c2c: false,
    images: "☕",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2440, lng: 106.7990
  },
  {
    id: 47,
    type: "bisnis",
    subtype: "akuisisi",
    title: "스시 레스토랑 - 수라바야 구눙사리",
    category: "카페 & 레스토랑",
    location: "Surabaya",
    locationKo: "수라바야",
    monthlyRevenue: "Rp 130 jt",
    monthlyRevenueNum: 130000000,
    profit: "18%",
    price: "Rp 900 jt",
    priceNum: 900000000,
    established: 2018,
    area: null,
    floors: null,
    description: "수라바야 구눙사리 스시 레스토랑. 좌석 60석. 단골 기업 고객 다수. 전문 일본요리사 인계 협의 가능.",
    facilities: ["전문 주방장", "냉장시설 풀세트", "POS 시스템", "고객 DB 3000건"],
    whatsapp: "+6281234567047",
    c2c: false,
    images: "🍣",
    badge: "완전인수",
    source: "현지조사",
    lat: -7.3097, lng: 112.7395
  },
  {
    id: 48,
    type: "bisnis",
    subtype: "akuisisi",
    title: "프랜차이즈 치킨 패스트푸드 - BSD",
    category: "프랜차이즈",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: "Rp 210 jt",
    monthlyRevenueNum: 210000000,
    profit: "16%",
    price: "Rp 1,1 M",
    priceNum: 1100000000,
    established: 2021,
    area: null,
    floors: null,
    description: "BSD 쇼핑몰 내 치킨 프랜차이즈. 국내 유명 브랜드. 본사 운영 지원. 일평균 매출 Rp 7jt.",
    facilities: ["프랜차이즈 계약 포함", "본사 AS 지원", "POS 시스템", "직원 8명 인계"],
    whatsapp: "+6281234567048",
    c2c: false,
    images: "🍗",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.3020, lng: 106.6540
  },

  // 루코 - 수라바야, 반둥, 스마랑
  {
    id: 49,
    type: "ruko",
    subtype: "jual",
    title: "루코 3층 수라바야 라야 다르모",
    category: "루코",
    location: "Surabaya",
    locationKo: "수라바야",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 5,5 M",
    priceNum: 5500000000,
    established: 2014,
    area: 200,
    floors: 3,
    description: "수라바야 최고 상권 다르모 대로변 루코. 120m² 토지. 현재 클리닉 임차 중. 월세 Rp 18jt.",
    facilities: ["대로변", "임차중 월Rp18jt", "120m²토지", "3층"],
    whatsapp: "+6281234567049",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "현지조사",
    lat: -7.2819, lng: 112.7368
  },
  {
    id: 50,
    type: "ruko",
    subtype: "jual",
    title: "루코 2층 반둥 디빠티우쿠르",
    category: "루코",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 2,3 M",
    priceNum: 2300000000,
    established: 2016,
    area: 100,
    floors: 2,
    description: "반둥 대학가 디빠티우쿠르 루코. 50m² 토지. 카페·스터디룸·스쿨 용도 적합. 유동인구 풍부.",
    facilities: ["대학가 상권", "유동인구 多", "2층", "주차 2대"],
    whatsapp: "+6281234567050",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "현지조사",
    lat: -6.8916, lng: 107.6107
  },
  {
    id: 51,
    type: "ruko",
    subtype: "jual",
    title: "루코 스마랑 수다르만 대로 4층",
    category: "루코",
    location: "Semarang",
    locationKo: "스마랑",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 4,2 M",
    priceNum: 4200000000,
    established: 2012,
    area: 240,
    floors: 4,
    description: "스마랑 수다르만 대로 루코. 90m² 토지. 은행 지점, 사무실 용도로 인기. 교통 중심지.",
    facilities: ["수다르만 대로변", "90m²토지", "4층", "엘리베이터"],
    whatsapp: "+6281234567051",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "현지조사",
    lat: -7.0051, lng: 110.4381
  },
  {
    id: 52,
    type: "ruko",
    subtype: "sewa",
    title: "루코 임대 - 반둥 시티 워크 2층",
    category: "루코",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 55 jt/tahun",
    priceNum: 55000000,
    established: 2018,
    area: 80,
    floors: 2,
    description: "반둥 시티워크 상업 단지 루코 임대. 1층 40m², 2층 40m². 리테일 또는 사무실 적합.",
    facilities: ["1+2층 분리사용", "에어컨 기본", "주차 1대", "인터컴"],
    whatsapp: "+6281234567052",
    c2c: false,
    images: "🏬",
    badge: "임대",
    source: "현지조사",
    lat: -6.9175, lng: 107.6191
  },

  // 피트니스 & 뷰티
  {
    id: 53,
    type: "bisnis",
    subtype: "akuisisi",
    title: "요가 스튜디오 - 발리 창구",
    category: "피트니스",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: "Rp 85 jt",
    monthlyRevenueNum: 85000000,
    profit: "30%",
    price: "Rp 600 jt",
    priceNum: 600000000,
    established: 2020,
    area: 200,
    floors: 1,
    description: "발리 창구 외국인 밀집 지역 요가 스튜디오. 회원 300명(외국인 70%). 강사 4명 인계 가능. 온라인 예약 시스템.",
    facilities: ["외국인 회원 多", "강사 4명", "온라인예약 시스템", "샤워/탈의실"],
    whatsapp: "+6281234567053",
    c2c: false,
    images: "🧘",
    badge: "완전인수",
    source: "현지조사",
    lat: -8.6500, lng: 115.1900
  },
  {
    id: 54,
    type: "bisnis",
    subtype: "investor",
    title: "헤어살롱 체인 - 자카르타 우타라",
    category: "뷰티 & 클리닉",
    location: "Jakarta Utara",
    locationKo: "자카르타 북부",
    monthlyRevenue: "Rp 160 jt",
    monthlyRevenueNum: 160000000,
    profit: "22%",
    price: "Rp 600 jt (지분 20%)",
    priceNum: 600000000,
    established: 2019,
    area: null,
    floors: null,
    description: "자카르타 우타라 헤어살롱 3개 지점 운영. 20% 지분 투자 유치. 추가 지점 확장 계획 중.",
    facilities: ["3개 지점", "브랜드 확립", "SNS 팔로워 8만", "예약 앱 운영"],
    whatsapp: "+6281234567054",
    c2c: false,
    images: "💇",
    badge: "투자유치",
    source: "현지조사",
    lat: -6.1400, lng: 106.8600
  },
  {
    id: 55,
    type: "bisnis",
    subtype: "akuisisi",
    title: "레이저 스킨케어 클리닉 - 반둥",
    category: "뷰티 & 클리닉",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: "Rp 120 jt",
    monthlyRevenueNum: 120000000,
    profit: "24%",
    price: "Rp 950 jt",
    priceNum: 950000000,
    established: 2021,
    area: null,
    floors: null,
    description: "반둥 프리미엄 스킨케어 클리닉. 레이저 장비 3대. 의사 1명, 스태프 4명. 단골 고객 1500명.",
    facilities: ["레이저장비 3대", "단골 1500명", "온라인 예약", "의사 인계 협의가능"],
    whatsapp: "+6281234567055",
    c2c: false,
    images: "💆",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.9147, lng: 107.6098
  },

  // 편의점 & 소매
  {
    id: 56,
    type: "bisnis",
    subtype: "akuisisi",
    title: "인도마렛 프랜차이즈 - 자카르타 티무르",
    category: "편의점 & 소매",
    location: "Jakarta Timur",
    locationKo: "자카르타 동부",
    monthlyRevenue: "Rp 180 jt",
    monthlyRevenueNum: 180000000,
    profit: "10%",
    price: "Rp 750 jt",
    priceNum: 750000000,
    established: 2019,
    area: null,
    floors: null,
    description: "자카르타 티무르 주거 밀집지 인도마렛 프랜차이즈. 24시간 운영. 직원 6명 인계. 본사 리뉴얼 지원.",
    facilities: ["24시간 운영", "본사 지원", "직원 6명", "냉장·냉동 설비"],
    whatsapp: "+6281234567056",
    c2c: false,
    images: "🛒",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2300, lng: 106.9100
  },
  {
    id: 57,
    type: "bisnis",
    subtype: "akuisisi",
    title: "스포츠용품 소매점 - 수라바야",
    category: "편의점 & 소매",
    location: "Surabaya",
    locationKo: "수라바야",
    monthlyRevenue: "Rp 70 jt",
    monthlyRevenueNum: 70000000,
    profit: "19%",
    price: "Rp 380 jt",
    priceNum: 380000000,
    established: 2017,
    area: 60,
    floors: 1,
    description: "수라바야 스포츠용품 전문 소매점. 나이키·아디다스 공식 대리점. 재고 일체 포함. 온라인 채널 병행.",
    facilities: ["공식 대리점", "재고 포함", "온라인채널 포함", "CCTV"],
    whatsapp: "+6281234567057",
    c2c: true,
    images: "👟",
    badge: "직거래",
    source: "현지조사",
    lat: -7.2575, lng: 112.7521
  },

  // 세탁소 & 기타 프랜차이즈
  {
    id: 58,
    type: "bisnis",
    subtype: "akuisisi",
    title: "런드리킹 프랜차이즈 세탁소 - 브카시",
    category: "세탁소",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: "Rp 38 jt",
    monthlyRevenueNum: 38000000,
    profit: "30%",
    price: "Rp 230 jt",
    priceNum: 230000000,
    established: 2022,
    area: 30,
    floors: 1,
    description: "브카시 런드리킹 프랜차이즈. 세탁기 6대, 건조기 4대. 직원 1명. 아파트 단지 내 위치로 안정 수요.",
    facilities: ["세탁기 6대", "건조기 4대", "본사 지원", "아파트단지 내"],
    whatsapp: "+6281234567058",
    c2c: false,
    images: "👕",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2420, lng: 106.9920
  },
  {
    id: 59,
    type: "bisnis",
    subtype: "akuisisi",
    title: "코인 세탁소 - 자카르타 바랏",
    category: "세탁소",
    location: "Jakarta Barat",
    locationKo: "자카르타 서부",
    monthlyRevenue: "Rp 52 jt",
    monthlyRevenueNum: 52000000,
    profit: "26%",
    price: "Rp 320 jt",
    priceNum: 320000000,
    established: 2021,
    area: 40,
    floors: 1,
    description: "자카르타 바랏 자가 세탁 코인세탁소. 기계 10대 풀세트. 24시간 무인 운영. 인건비 최소화.",
    facilities: ["세탁기 6대", "건조기 4대", "24시간 무인", "CCTV·POS"],
    whatsapp: "+6281234567059",
    c2c: true,
    images: "👕",
    badge: "직거래",
    source: "현지조사",
    lat: -6.1680, lng: 106.7450
  },

  // IT 스타트업 & 교육
  {
    id: 60,
    type: "bisnis",
    subtype: "investor",
    title: "에듀테크 스타트업 - 자카르타 셀라탄",
    category: "IT & 스타트업",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: "Rp 80 jt",
    monthlyRevenueNum: 80000000,
    profit: "15%",
    price: "Rp 1 M (지분 20%)",
    priceNum: 1000000000,
    established: 2022,
    area: null,
    floors: null,
    description: "K-12 온라인 교육 플랫폼. 유료 회원 5000명. 연간 반복 매출. 시리즈 A 투자 준비 중. 팀 15명.",
    facilities: ["유료 회원 5000명", "자체 플랫폼", "팀 15명", "시리즈A 준비"],
    whatsapp: "+6281234567060",
    c2c: false,
    images: "💻",
    badge: "투자유치",
    source: "현지조사",
    lat: -6.2600, lng: 106.8100
  },
  {
    id: 61,
    type: "bisnis",
    subtype: "akuisisi",
    title: "코딩 학원 - 가딩 세르퐁",
    category: "교육 학원",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: "Rp 65 jt",
    monthlyRevenueNum: 65000000,
    profit: "25%",
    price: "Rp 450 jt",
    priceNum: 450000000,
    established: 2021,
    area: 80,
    floors: 1,
    description: "가딩 세르퐁 어린이·청소년 코딩 학원. 수강생 120명. 강사 4명. 태블릿·컴퓨터 30대 포함.",
    facilities: ["컴퓨터 30대", "강사 4명", "커리큘럼 포함", "학부모 앱 포함"],
    whatsapp: "+6281234567061",
    c2c: false,
    images: "🖥️",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2370, lng: 106.6190
  },
  {
    id: 62,
    type: "bisnis",
    subtype: "akuisisi",
    title: "영어 학원 - 자카르타 푸삿",
    category: "교육 학원",
    location: "Jakarta Pusat",
    locationKo: "자카르타 중부",
    monthlyRevenue: "Rp 90 jt",
    monthlyRevenueNum: 90000000,
    profit: "22%",
    price: "Rp 580 jt",
    priceNum: 580000000,
    established: 2018,
    area: 120,
    floors: 1,
    description: "자카르타 푸삿 영어 회화 학원. 수강생 200명. 원어민 강사 2명 포함. 오피스텔 내 위치.",
    facilities: ["원어민 강사 2명", "수강생 200명", "교재·자료 포함", "온라인 병행"],
    whatsapp: "+6281234567062",
    c2c: false,
    images: "📚",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.1900, lng: 106.8230
  },

  // 물류 & 제조
  {
    id: 63,
    type: "bisnis",
    subtype: "investor",
    title: "물류 창고 운영사 - 브카시 EJIP",
    category: "물류 창고",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: "Rp 350 jt",
    monthlyRevenueNum: 350000000,
    profit: "14%",
    price: "Rp 2 M (지분 15%)",
    priceNum: 2000000000,
    established: 2016,
    area: 2000,
    floors: 1,
    description: "EJIP 산업단지 내 물류 창고 운영사. 2000m² 창고. 일본계 기업 고객 5곳 계약 중. 안정적 매출.",
    facilities: ["2000m²창고", "일본계 고객사", "지게차 3대", "24시간 운영"],
    whatsapp: "+6281234567063",
    c2c: false,
    images: "📦",
    badge: "투자유치",
    source: "현지조사",
    lat: -6.2900, lng: 107.0500
  },
  {
    id: 64,
    type: "bisnis",
    subtype: "investor",
    title: "식품 가공 공장 - 스마랑",
    category: "제조업",
    location: "Semarang",
    locationKo: "스마랑",
    monthlyRevenue: "Rp 420 jt",
    monthlyRevenueNum: 420000000,
    profit: "11%",
    price: "Rp 2,5 M (지분 25%)",
    priceNum: 2500000000,
    established: 2013,
    area: 1200,
    floors: 1,
    description: "스마랑 식품 가공 공장. 템페·두부 제품 제조. 자바 전역 유통망 보유. BPOM 허가 완비.",
    facilities: ["BPOM허가 완비", "자바전역 유통망", "1200m²공장", "ISO 인증"],
    whatsapp: "+6281234567064",
    c2c: false,
    images: "🏭",
    badge: "투자유치",
    source: "현지조사",
    lat: -7.0100, lng: 110.4050
  },

  // 발리 & 부동산
  {
    id: 65,
    type: "properti",
    subtype: "jual",
    title: "빌라 2베드룸 - 발리 우붓",
    category: "빌라 & 부동산",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 7,5 M",
    priceNum: 7500000000,
    established: 2019,
    area: 220,
    floors: 1,
    description: "우붓 라이스필드뷰 빌라. 2베드룸, 수영장. 에어비앤비 연 Rp 280jt 수익. Leasehold 28년 잔여.",
    facilities: ["수영장", "라이스필드뷰", "에어비앤비 등록", "Leasehold 28년"],
    whatsapp: "+6281234567065",
    c2c: false,
    images: "🏖️",
    badge: "매매",
    foreignNote: "외국인 Leasehold 가능",
    source: "현지조사",
    lat: -8.5069, lng: 115.2624
  },
  {
    id: 66,
    type: "properti",
    subtype: "jual",
    title: "상가 아파트 - 자카르타 셀라탄 TB시마툽앙",
    category: "사무실 빌딩",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 18 M",
    priceNum: 18000000000,
    established: 2009,
    area: 600,
    floors: 5,
    description: "TB 시마툽앙 CBD 인근 5층 복합건물. 1~2층 상가, 3~5층 아파트. 입주율 85%. 월 임대수익 Rp 80jt.",
    facilities: ["복합용도", "월Rp80jt 임대", "입주율85%", "SHM"],
    whatsapp: "+6281234567066",
    c2c: false,
    images: "🏗️",
    badge: "매매",
    source: "현지조사",
    lat: -6.3100, lng: 106.8350
  },
  {
    id: 67,
    type: "properti",
    subtype: "jual",
    title: "토지 - 수라바야 웡오르코 산업지구",
    category: "토지",
    location: "Surabaya",
    locationKo: "수라바야",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 6 M",
    priceNum: 6000000000,
    established: null,
    area: 1500,
    floors: null,
    description: "수라바야 웡오르코 공업지역 토지. 1500m². SHM 증서. 공장 설립 허가 취득 가능.",
    facilities: ["SHM 증서", "공업용 허가가능", "전기 인입", "수도 인입"],
    whatsapp: "+6281234567067",
    c2c: false,
    images: "🌿",
    badge: "매매",
    source: "현지조사",
    lat: -7.2100, lng: 112.6800
  },
  {
    id: 68,
    type: "properti",
    subtype: "jual",
    title: "타운하우스 단지 - BSD 그린빌",
    category: "빌라 & 부동산",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 3,8 M",
    priceNum: 3800000000,
    established: 2021,
    area: 180,
    floors: 2,
    description: "BSD 그린빌 타운하우스. 3베드룸. 단지 내 수영장·클럽하우스. 24시간 보안. SHM 증서.",
    facilities: ["3베드룸", "단지수영장", "클럽하우스", "24시간보안"],
    whatsapp: "+6281234567068",
    c2c: false,
    images: "🏘️",
    badge: "매매",
    source: "현지조사",
    lat: -6.3000, lng: 106.6480
  },

  // 루코 - 자카르타 각 구역 추가
  {
    id: 69,
    type: "ruko",
    subtype: "jual",
    title: "루코 자카르타 바랏 팔메라 3층",
    category: "루코",
    location: "Jakarta Barat",
    locationKo: "자카르타 서부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 4,1 M",
    priceNum: 4100000000,
    established: 2015,
    area: 180,
    floors: 3,
    description: "팔메라 자카르타 바랏 루코. 90m² 토지. 주거·상업 혼합 지역. 현재 약국 임차 중 월 Rp 12jt.",
    facilities: ["약국 임차중 월Rp12jt", "90m²토지", "3층", "HGB"],
    whatsapp: "+6281234567069",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "현지조사",
    lat: -6.1600, lng: 106.7600
  },
  {
    id: 70,
    type: "ruko",
    subtype: "jual",
    title: "루코 자카르타 티무르 말랑 라야 2층",
    category: "루코",
    location: "Jakarta Timur",
    locationKo: "자카르타 동부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 2,7 M",
    priceNum: 2700000000,
    established: 2014,
    area: 110,
    floors: 2,
    description: "자카르타 티무르 번화가 루코. 66m² 토지. 1층 상가, 2층 사무실. 주차 2대. 즉시 입주 가능.",
    facilities: ["주차 2대", "즉시입주", "66m²토지", "2층"],
    whatsapp: "+6281234567070",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "현지조사",
    lat: -6.2180, lng: 106.8950
  },
  {
    id: 71,
    type: "ruko",
    subtype: "sewa",
    title: "루코 임대 - 자카르타 우타라 켈라파 가딩",
    category: "루코",
    location: "Jakarta Utara",
    locationKo: "자카르타 북부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 80 jt/tahun",
    priceNum: 80000000,
    established: 2017,
    area: 160,
    floors: 2,
    description: "켈라파 가딩 상업지 루코 임대. 1층 80m², 2층 80m². 은행·외식 업종 선호. 연 임대료 선불.",
    facilities: ["은행업종 선호", "1+2층 각 80m²", "전기 10KVA", "주차 2대"],
    whatsapp: "+6281234567071",
    c2c: false,
    images: "🏢",
    badge: "임대",
    source: "현지조사",
    lat: -6.1580, lng: 106.9050
  },
  {
    id: 72,
    type: "ruko",
    subtype: "jual",
    title: "루코 자카르타 푸삿 체웨 4층 코너",
    category: "루코",
    location: "Jakarta Pusat",
    locationKo: "자카르타 중부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 9,5 M",
    priceNum: 9500000000,
    established: 2011,
    area: 350,
    floors: 4,
    description: "자카르타 푸삿 체웨 코너 루코. 120m² 토지. 은행·대사관 인근. 기업 본사 용도 최적.",
    facilities: ["코너 위치", "120m²토지", "4층", "기업용 최적"],
    whatsapp: "+6281234567072",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "현지조사",
    lat: -6.2000, lng: 106.8350
  },

  // 발리 추가 비즈니스
  {
    id: 73,
    type: "bisnis",
    subtype: "akuisisi",
    title: "서핑숍 & 스쿨 - 발리 쿠타",
    category: "피트니스",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: "Rp 110 jt",
    monthlyRevenueNum: 110000000,
    profit: "28%",
    price: "Rp 780 jt",
    priceNum: 780000000,
    established: 2017,
    area: null,
    floors: null,
    description: "쿠타 해변 인근 서핑숍 + 서핑스쿨. 보드 50개, 강사 6명. 외국인 관광객 주 고객. 성수기 매출 2배.",
    facilities: ["서핑보드 50개", "강사 6명", "장비 렌탈 시스템", "SNS 채널 인계"],
    whatsapp: "+6281234567073",
    c2c: false,
    images: "🏄",
    badge: "완전인수",
    source: "현지조사",
    lat: -8.7200, lng: 115.1680
  },
  {
    id: 74,
    type: "bisnis",
    subtype: "akuisisi",
    title: "게스트하우스 10룸 - 발리 세미냑",
    category: "숙박업",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: "Rp 200 jt",
    monthlyRevenueNum: 200000000,
    profit: "32%",
    price: "Rp 2,8 M",
    priceNum: 2800000000,
    established: 2018,
    area: 400,
    floors: 2,
    description: "세미냑 게스트하우스 10룸. 에어비앤비·부킹닷컴 등록. 연 평균 점유율 80%. 직원 4명 인계.",
    facilities: ["10룸", "OTA 등록 일체", "수영장", "직원 4명"],
    whatsapp: "+6281234567074",
    c2c: false,
    images: "🏨",
    badge: "완전인수",
    source: "현지조사",
    lat: -8.6900, lng: 115.1600
  },

  // 주차장 & 특수 비즈니스
  {
    id: 75,
    type: "bisnis",
    subtype: "akuisisi",
    title: "자동 세차 - 탕그랑 셀라탄",
    category: "자동차 서비스",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: "Rp 68 jt",
    monthlyRevenueNum: 68000000,
    profit: "32%",
    price: "Rp 500 jt",
    priceNum: 500000000,
    established: 2021,
    area: 200,
    floors: 1,
    description: "탕그랑 셀라탄 자동 세차. 하루 평균 60대. 자동 터널식 세차 장비. 왁스·실내청소 부가서비스.",
    facilities: ["자동 터널세차", "일평균 60대", "부가서비스", "CCTV"],
    whatsapp: "+6281234567075",
    c2c: false,
    images: "🚗",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2900, lng: 106.6800
  },
  {
    id: 76,
    type: "bisnis",
    subtype: "akuisisi",
    title: "옥외 광고 주차빌딩 - 자카르타 바랏",
    category: "주차장",
    location: "Jakarta Barat",
    locationKo: "자카르타 서부",
    monthlyRevenue: "Rp 95 jt",
    monthlyRevenueNum: 95000000,
    profit: "45%",
    price: "Rp 2,2 M",
    priceNum: 2200000000,
    established: 2017,
    area: 800,
    floors: 3,
    description: "자카르타 바랏 3층 주차 빌딩. 300대 수용. 옥외 광고 수익 병행. 자동 발권 시스템.",
    facilities: ["300대 수용", "옥외광고 수익", "자동발권시스템", "24시간 운영"],
    whatsapp: "+6281234567076",
    c2c: false,
    images: "🚗",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.1720, lng: 106.7550
  },

  // 반둥 & 스마랑 비즈니스
  {
    id: 77,
    type: "bisnis",
    subtype: "akuisisi",
    title: "패션 부티크 - 반둥 파리아타",
    category: "편의점 & 소매",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: "Rp 85 jt",
    monthlyRevenueNum: 85000000,
    profit: "23%",
    price: "Rp 420 jt",
    priceNum: 420000000,
    established: 2020,
    area: 50,
    floors: 1,
    description: "반둥 파리아타 패션 거리 부티크. 자체 디자인 의류. 인스타그램 팔로워 12만. 제조업체 직납.",
    facilities: ["자체 브랜드", "SNS 12만 팔로워", "재고 포함", "제조업체 계약"],
    whatsapp: "+6281234567077",
    c2c: true,
    images: "👗",
    badge: "직거래",
    source: "현지조사",
    lat: -6.9150, lng: 107.6050
  },
  {
    id: 78,
    type: "bisnis",
    subtype: "akuisisi",
    title: "클라우드 키친 - 스마랑",
    category: "카페 & 레스토랑",
    location: "Semarang",
    locationKo: "스마랑",
    monthlyRevenue: "Rp 75 jt",
    monthlyRevenueNum: 75000000,
    profit: "20%",
    price: "Rp 480 jt",
    priceNum: 480000000,
    established: 2022,
    area: 60,
    floors: 1,
    description: "스마랑 클라우드 키친. 고젝·그랩푸드 입점 5개 브랜드 운영. 주방장 2명. 배달 전용 100% 수익형.",
    facilities: ["5개 브랜드 운영", "고젝·그랩푸드 인계", "주방장 2명", "냉장설비 풀셋"],
    whatsapp: "+6281234567078",
    c2c: false,
    images: "🍽️",
    badge: "완전인수",
    source: "현지조사",
    lat: -7.0050, lng: 110.4300
  },

  // 루코 임대 추가
  {
    id: 79,
    type: "ruko",
    subtype: "sewa",
    title: "루코 임대 - 수라바야 칼리룽구 대로",
    category: "루코",
    location: "Surabaya",
    locationKo: "수라바야",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 45 jt/tahun",
    priceNum: 45000000,
    established: 2016,
    area: 90,
    floors: 2,
    description: "수라바야 칼리룽구 대로변 루코 임대. 1층 45m², 2층 45m². 식음료·소매·오피스 적합. 주차 포함.",
    facilities: ["대로변", "주차 포함", "2층 분리사용", "전기 4400W"],
    whatsapp: "+6281234567079",
    c2c: false,
    images: "🏬",
    badge: "임대",
    source: "현지조사",
    lat: -7.2600, lng: 112.7300
  },
  {
    id: 80,
    type: "ruko",
    subtype: "sewa",
    title: "루코 임대 - 반둥 코타 바루 파라혼",
    category: "루코",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 40 jt/tahun",
    priceNum: 40000000,
    established: 2019,
    area: 70,
    floors: 2,
    description: "반둥 신도시 파라혼 루코. 1층 35m², 2층 35m². 주변 학교·병원 인접. 안전한 주거지역.",
    facilities: ["학교 인접", "병원 인접", "2층", "주차 1대"],
    whatsapp: "+6281234567080",
    c2c: false,
    images: "🏪",
    badge: "임대",
    source: "현지조사",
    lat: -6.9300, lng: 107.6400
  },

  // 제조업 & IT
  {
    id: 81,
    type: "bisnis",
    subtype: "investor",
    title: "섬유 의류 공장 - 반둥 마자랑카",
    category: "제조업",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: "Rp 600 jt",
    monthlyRevenueNum: 600000000,
    profit: "13%",
    price: "Rp 2 M (지분 20%)",
    priceNum: 2000000000,
    established: 2011,
    area: 1500,
    floors: 1,
    description: "반둥 마자랑카 의류 OEM 공장. 해외 브랜드 납품 경력. 직원 80명. 20% 지분 투자 유치.",
    facilities: ["해외 브랜드 납품", "직원 80명", "재봉기 100대", "수출 경험"],
    whatsapp: "+6281234567081",
    c2c: false,
    images: "🏭",
    badge: "투자유치",
    source: "현지조사",
    lat: -6.9500, lng: 107.6700
  },
  {
    id: 82,
    type: "bisnis",
    subtype: "investor",
    title: "SaaS 스타트업 - 자카르타 바랏",
    category: "IT & 스타트업",
    location: "Jakarta Barat",
    locationKo: "자카르타 서부",
    monthlyRevenue: "Rp 120 jt",
    monthlyRevenueNum: 120000000,
    profit: "30%",
    price: "Rp 800 jt (지분 15%)",
    priceNum: 800000000,
    established: 2023,
    area: null,
    floors: null,
    description: "인도네시아 SME 대상 회계 SaaS. 유료 고객 800사. MRR 성장률 월 12%. 시드 투자 완료.",
    facilities: ["유료 고객 800사", "MRR 성장 12%/월", "개발팀 8명", "시드투자 완료"],
    whatsapp: "+6281234567082",
    c2c: false,
    images: "💻",
    badge: "투자유치",
    source: "현지조사",
    lat: -6.1700, lng: 106.7650
  },

  // 부동산 추가
  {
    id: 83,
    type: "properti",
    subtype: "jual",
    title: "토지 - 탕그랑 셀라탄 폰독 칼리",
    category: "토지",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 5 M",
    priceNum: 5000000000,
    established: null,
    area: 600,
    floors: null,
    description: "탕그랑 셀라탄 전략 토지. 600m². SHM 증서. 상업시설 개발 허가 가능. 톨 IC 5분 거리.",
    facilities: ["SHM 증서", "상업허가가능", "톨IC 5분", "정방형"],
    whatsapp: "+6281234567083",
    c2c: false,
    images: "🌿",
    badge: "매매",
    source: "현지조사",
    lat: -6.3200, lng: 106.7000
  },
  {
    id: 84,
    type: "properti",
    subtype: "jual",
    title: "아파트 투자용 스튜디오 - 자카르타 셀라탄 TB시마툽앙",
    category: "사무실 빌딩",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 850 jt",
    priceNum: 850000000,
    established: 2020,
    area: 38,
    floors: 1,
    description: "TB 시마툽앙 CBD 스튜디오 아파트. 38m². 월 임대수익 Rp 5jt. 수영장·피트니스 단지 시설.",
    facilities: ["단지 수영장", "피트니스", "월세Rp5jt", "CBD 인접"],
    whatsapp: "+6281234567084",
    c2c: false,
    images: "🏘️",
    badge: "매매",
    source: "현지조사",
    lat: -6.3050, lng: 106.8300
  },
  {
    id: 85,
    type: "properti",
    subtype: "jual",
    title: "상가 건물 - 브카시 하라판 인다",
    category: "사무실 빌딩",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 8 M",
    priceNum: 8000000000,
    established: 2008,
    area: 400,
    floors: 3,
    description: "하라판 인다 상가 건물. 3층 400m². 현재 4개 점포 임차. 월 임대수익 Rp 28jt. SHM 증서.",
    facilities: ["4개 점포 임차중", "월Rp28jt 수익", "SHM 증서", "3층"],
    whatsapp: "+6281234567085",
    c2c: false,
    images: "🏗️",
    badge: "매매",
    source: "현지조사",
    lat: -6.2400, lng: 106.9900
  },

  // 프랜차이즈 추가
  {
    id: 86,
    type: "bisnis",
    subtype: "akuisisi",
    title: "알파마트 프랜차이즈 - 가딩 세르퐁",
    category: "프랜차이즈",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: "Rp 140 jt",
    monthlyRevenueNum: 140000000,
    profit: "12%",
    price: "Rp 600 jt",
    priceNum: 600000000,
    established: 2020,
    area: null,
    floors: null,
    description: "가딩 세르퐁 알파마트 프랜차이즈. 주거단지 내 독점 입점. 24시간 운영. 직원 5명.",
    facilities: ["독점 입점", "24시간 운영", "직원 5명", "본사 재고 관리"],
    whatsapp: "+6281234567086",
    c2c: false,
    images: "🛒",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2290, lng: 106.6170
  },
  {
    id: 87,
    type: "bisnis",
    subtype: "akuisisi",
    title: "약국 K-24 프랜차이즈 - 데포",
    category: "프랜차이즈",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: "Rp 110 jt",
    monthlyRevenueNum: 110000000,
    profit: "14%",
    price: "Rp 550 jt",
    priceNum: 550000000,
    established: 2019,
    area: null,
    floors: null,
    description: "데포 주거지역 K-24 약국 프랜차이즈. 24시간 운영. 약사 2명 인계 가능. 본사 의약품 공급.",
    facilities: ["24시간 운영", "약사 2명", "본사 의약품 공급", "처방 조제 가능"],
    whatsapp: "+6281234567087",
    c2c: false,
    images: "💊",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.4050, lng: 106.8100
  },
  {
    id: 88,
    type: "bisnis",
    subtype: "akuisisi",
    title: "피자 HUT 딜리버리 - 브카시 선야르기",
    category: "프랜차이즈",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: "Rp 170 jt",
    monthlyRevenueNum: 170000000,
    profit: "13%",
    price: "Rp 850 jt",
    priceNum: 850000000,
    established: 2018,
    area: null,
    floors: null,
    description: "브카시 선야르기 피자 HUT 딜리버리 점. 배달 반경 내 선두. 직원 10명. 본사 지원 인계.",
    facilities: ["브랜드 인지도", "배달 시스템", "직원 10명", "본사 계약 인계"],
    whatsapp: "+6281234567088",
    c2c: false,
    images: "🍕",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2480, lng: 107.0000
  },

  // 루코 - 추가 지역
  {
    id: 89,
    type: "ruko",
    subtype: "jual",
    title: "루코 스마랑 판두 라야 3층",
    category: "루코",
    location: "Semarang",
    locationKo: "스마랑",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 3,1 M",
    priceNum: 3100000000,
    established: 2015,
    area: 150,
    floors: 3,
    description: "스마랑 판두 라야 루코. 75m² 토지. 대학교·병원 인근. 현재 오피스 임차 중 월 Rp 10jt.",
    facilities: ["대학·병원 인근", "임차중 월Rp10jt", "75m²토지", "3층"],
    whatsapp: "+6281234567089",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "현지조사",
    lat: -7.0150, lng: 110.4200
  },
  {
    id: 90,
    type: "ruko",
    subtype: "jual",
    title: "루코 반둥 레겐시 2층 신개발지",
    category: "루코",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 1,8 M",
    priceNum: 1800000000,
    established: 2023,
    area: 72,
    floors: 2,
    description: "반둥 레겐시 신개발 상업지구 루코. 54m² 토지. DP 30%, KPR 가능. 고성장 지역.",
    facilities: ["신개발지", "KPR 가능", "54m²토지", "고성장 지역"],
    whatsapp: "+6281234567090",
    c2c: false,
    images: "🏪",
    badge: "매매",
    source: "현지조사",
    lat: -6.9600, lng: 107.7000
  },

  // 숙박 & 관광
  {
    id: 91,
    type: "bisnis",
    subtype: "akuisisi",
    title: "부티크 호텔 8룸 - 발리 누사두아",
    category: "숙박업",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: "Rp 280 jt",
    monthlyRevenueNum: 280000000,
    profit: "28%",
    price: "Rp 4,5 M",
    priceNum: 4500000000,
    established: 2017,
    area: 500,
    floors: 2,
    description: "누사두아 부티크 호텔 8룸. 스탠다드~딜럭스 객실. 야외 수영장. OTA 평점 9.1. 직원 8명 인계.",
    facilities: ["야외 수영장", "OTA 평점 9.1", "직원 8명", "레스토랑 운영"],
    whatsapp: "+6281234567091",
    c2c: false,
    images: "🏨",
    badge: "완전인수",
    source: "현지조사",
    lat: -8.7990, lng: 115.2270
  },
  {
    id: 92,
    type: "bisnis",
    subtype: "akuisisi",
    title: "다이빙센터 - 발리 아메드",
    category: "피트니스",
    location: "Bali",
    locationKo: "발리",
    monthlyRevenue: "Rp 95 jt",
    monthlyRevenueNum: 95000000,
    profit: "35%",
    price: "Rp 700 jt",
    priceNum: 700000000,
    established: 2019,
    area: null,
    floors: null,
    description: "아메드 다이빙 센터. PADI 공인. 강사 4명(외국인 2명 포함). 장비 풀셋. 연간 고객 500명.",
    facilities: ["PADI 공인", "강사 4명", "다이빙장비 풀셋", "예약 시스템"],
    whatsapp: "+6281234567092",
    c2c: false,
    images: "🤿",
    badge: "완전인수",
    source: "현지조사",
    lat: -8.3460, lng: 115.6210
  },

  // IT & 물류
  {
    id: 93,
    type: "bisnis",
    subtype: "investor",
    title: "전자상거래 물류 스타트업 - 자카르타 티무르",
    category: "물류 창고",
    location: "Jakarta Timur",
    locationKo: "자카르타 동부",
    monthlyRevenue: "Rp 250 jt",
    monthlyRevenueNum: 250000000,
    profit: "18%",
    price: "Rp 1,5 M (지분 20%)",
    priceNum: 1500000000,
    established: 2021,
    area: 800,
    floors: 1,
    description: "자카르타 이커머스 풀필먼트 센터. 토코피디아·쇼피 셀러 200곳 서비스 중. 800m² 창고.",
    facilities: ["풀필먼트 시스템", "셀러 200곳", "800m²창고", "ERP 시스템"],
    whatsapp: "+6281234567093",
    c2c: false,
    images: "📦",
    badge: "투자유치",
    source: "현지조사",
    lat: -6.2350, lng: 106.9200
  },
  {
    id: 94,
    type: "bisnis",
    subtype: "akuisisi",
    title: "3D 프린팅 서비스 - 자카르타 셀라탄",
    category: "IT & 스타트업",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: "Rp 55 jt",
    monthlyRevenueNum: 55000000,
    profit: "28%",
    price: "Rp 380 jt",
    priceNum: 380000000,
    established: 2022,
    area: 50,
    floors: 1,
    description: "자카르타 셀라탄 3D 프린팅 서비스. 프린터 8대. B2B 고객 30사. 프로토타입·부품 제작 특화.",
    facilities: ["3D프린터 8대", "B2B 고객 30사", "CAD 소프트웨어", "배송 서비스"],
    whatsapp: "+6281234567094",
    c2c: true,
    images: "🖨️",
    badge: "직거래",
    source: "현지조사",
    lat: -6.2700, lng: 106.8050
  },

  // 루코 추가
  {
    id: 95,
    type: "ruko",
    subtype: "jual",
    title: "루코 BSD Pasar Modern 3층 코너",
    category: "루코",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 5,8 M",
    priceNum: 5800000000,
    established: 2016,
    area: 220,
    floors: 3,
    description: "BSD 파사르 모던 인근 코너 루코. 90m² 토지. 주말 시장 방문객 유입. 레스토랑·소매 최적.",
    facilities: ["코너 위치", "주말시장 인접", "90m²토지", "3층"],
    whatsapp: "+6281234567095",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "현지조사",
    lat: -6.3080, lng: 106.6560
  },
  {
    id: 96,
    type: "ruko",
    subtype: "jual",
    title: "루코 가딩 세르퐁 커머셜 에리어 2층",
    category: "루코",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 2,4 M",
    priceNum: 2400000000,
    established: 2018,
    area: 96,
    floors: 2,
    description: "가딩 세르퐁 커머셜 에리어 루코. 60m² 토지. 한국 교민 밀집 지역 인근. 한식당 운영 경력.",
    facilities: ["한국 교민 인근", "60m²토지", "2층", "주차 2대"],
    whatsapp: "+6281234567096",
    c2c: false,
    images: "🏬",
    badge: "매매",
    source: "현지조사",
    lat: -6.2330, lng: 106.6220
  },

  // 교육 & 헬스
  {
    id: 97,
    type: "bisnis",
    subtype: "akuisisi",
    title: "수영 아카데미 - 데포",
    category: "피트니스",
    location: "Depok",
    locationKo: "데포",
    monthlyRevenue: "Rp 72 jt",
    monthlyRevenueNum: 72000000,
    profit: "26%",
    price: "Rp 520 jt",
    priceNum: 520000000,
    established: 2020,
    area: 400,
    floors: 1,
    description: "데포 수영 아카데미. 25m 풀 2개. 수강생 250명. 코치 4명. 학교 클럽 연계 계약 보유.",
    facilities: ["25m 풀 2개", "수강생 250명", "코치 4명", "학교 연계계약"],
    whatsapp: "+6281234567097",
    c2c: false,
    images: "🏊",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.4000, lng: 106.8150
  },
  {
    id: 98,
    type: "bisnis",
    subtype: "akuisisi",
    title: "음악 학원 - 탕그랑 리폰 빌리지",
    category: "교육 학원",
    location: "Tangerang",
    locationKo: "탕그랑",
    monthlyRevenue: "Rp 45 jt",
    monthlyRevenueNum: 45000000,
    profit: "28%",
    price: "Rp 300 jt",
    priceNum: 300000000,
    established: 2019,
    area: 80,
    floors: 1,
    description: "탕그랑 리폰 빌리지 음악 학원. 피아노·기타·바이올린 과목. 수강생 80명. 악기 일체 포함.",
    facilities: ["피아노 10대", "기타·바이올린 포함", "수강생 80명", "강사 4명"],
    whatsapp: "+6281234567098",
    c2c: true,
    images: "🎵",
    badge: "직거래",
    source: "현지조사",
    lat: -6.2100, lng: 106.6000
  },

  // 추가 부동산
  {
    id: 99,
    type: "properti",
    subtype: "jual",
    title: "빌라 단지 분양 - 반둥 레렝",
    category: "빌라 & 부동산",
    location: "Bandung",
    locationKo: "반둥",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 2,1 M",
    priceNum: 2100000000,
    established: 2024,
    area: 150,
    floors: 2,
    description: "반둥 레렝 산악 뷰 빌라 단지. 3베드룸. 서늘한 기후. 자카르타 주말 별장 수요 높음. SHM.",
    facilities: ["산악 뷰", "서늘한 기후", "SHM 증서", "단지 클럽하우스"],
    whatsapp: "+6281234567099",
    c2c: false,
    images: "🏔️",
    badge: "매매",
    source: "현지조사",
    lat: -6.8700, lng: 107.5700
  },
  {
    id: 100,
    type: "properti",
    subtype: "jual",
    title: "상업용 토지 - 스마랑 칼리바루",
    category: "토지",
    location: "Semarang",
    locationKo: "스마랑",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 3,5 M",
    priceNum: 3500000000,
    established: null,
    area: 700,
    floors: null,
    description: "스마랑 칼리바루 상업용 토지. 700m². SHM. 주요 도로 인접. 쇼핑몰·호텔 개발 잠재력.",
    facilities: ["SHM 증서", "주요도로 접면", "700m²", "상업허가가능"],
    whatsapp: "+6281234567100",
    c2c: false,
    images: "🌿",
    badge: "매매",
    source: "현지조사",
    lat: -6.9900, lng: 110.3900
  },

  // 자동차 서비스 & 기타
  {
    id: 101,
    type: "bisnis",
    subtype: "akuisisi",
    title: "자동차 정비소 - 자카르타 우타라",
    category: "자동차 서비스",
    location: "Jakarta Utara",
    locationKo: "자카르타 북부",
    monthlyRevenue: "Rp 80 jt",
    monthlyRevenueNum: 80000000,
    profit: "22%",
    price: "Rp 550 jt",
    priceNum: 550000000,
    established: 2016,
    area: 300,
    floors: 1,
    description: "자카르타 우타라 자동차 정비소. 일평균 20대. 정비사 5명 인계. 부품 재고 포함. 단골 법인 고객 10사.",
    facilities: ["정비사 5명", "리프트 4기", "부품 재고 포함", "법인 고객 10사"],
    whatsapp: "+6281234567101",
    c2c: false,
    images: "🔧",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.1350, lng: 106.8500
  },
  {
    id: 102,
    type: "bisnis",
    subtype: "akuisisi",
    title: "인쇄·광고물 제작소 - 브카시",
    category: "제조업",
    location: "Bekasi",
    locationKo: "브카시",
    monthlyRevenue: "Rp 65 jt",
    monthlyRevenueNum: 65000000,
    profit: "20%",
    price: "Rp 420 jt",
    priceNum: 420000000,
    established: 2015,
    area: 100,
    floors: 1,
    description: "브카시 인쇄·현수막·배너 제작소. B2B 고객 위주. 대형 플로터 3대. 직원 5명 인계.",
    facilities: ["대형 플로터 3대", "B2B 고객 위주", "직원 5명", "재료 재고 포함"],
    whatsapp: "+6281234567102",
    c2c: true,
    images: "🖨️",
    badge: "직거래",
    source: "현지조사",
    lat: -6.2550, lng: 107.0200
  },
  {
    id: 103,
    type: "bisnis",
    subtype: "akuisisi",
    title: "꽃집 & 웨딩 플라워 - 자카르타 셀라탄",
    category: "편의점 & 소매",
    location: "Jakarta Selatan",
    locationKo: "자카르타 남부",
    monthlyRevenue: "Rp 48 jt",
    monthlyRevenueNum: 48000000,
    profit: "30%",
    price: "Rp 280 jt",
    priceNum: 280000000,
    established: 2021,
    area: 30,
    floors: 1,
    description: "자카르타 셀라탄 플라워숍. 웨딩·이벤트 장식 특화. 인스타그램 팔로워 6만. 정기 기업 고객 20사.",
    facilities: ["웨딩 패키지", "기업 고객 20사", "SNS 6만 팔로워", "배달 서비스"],
    whatsapp: "+6281234567103",
    c2c: false,
    images: "💐",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2550, lng: 106.8200
  },
  {
    id: 104,
    type: "bisnis",
    subtype: "akuisisi",
    title: "펫숍 & 동물병원 - 가딩 세르퐁",
    category: "뷰티 & 클리닉",
    location: "Gading Serpong",
    locationKo: "가딩 세르퐁",
    monthlyRevenue: "Rp 75 jt",
    monthlyRevenueNum: 75000000,
    profit: "22%",
    price: "Rp 520 jt",
    priceNum: 520000000,
    established: 2021,
    area: 80,
    floors: 1,
    description: "가딩 세르퐁 펫숍 + 소동물 클리닉. 수의사 1명. 그루밍 서비스 병행. 단골 고객 600명.",
    facilities: ["수의사 1명", "그루밍 서비스", "단골 600명", "온라인 예약"],
    whatsapp: "+6281234567104",
    c2c: false,
    images: "🐾",
    badge: "완전인수",
    source: "현지조사",
    lat: -6.2260, lng: 106.6200
  },
  {
    id: 105,
    type: "ruko",
    subtype: "jual",
    title: "루코 BSD City The Prominence 5층",
    category: "루코",
    location: "BSD",
    locationKo: "BSD",
    monthlyRevenue: null,
    monthlyRevenueNum: null,
    profit: null,
    price: "Rp 11 M",
    priceNum: 11000000000,
    established: 2019,
    area: 500,
    floors: 5,
    description: "BSD 시티 더 프로미넌스 5층 대형 루코. 145m² 토지. 프리미엄 상업단지. 엘리베이터 포함. 최고급 위치.",
    facilities: ["엘리베이터", "145m²토지", "5층", "프리미엄 단지"],
    whatsapp: "+6281234567105",
    c2c: false,
    images: "🏢",
    badge: "매매",
    source: "rumah123.com",
    lat: -6.2980, lng: 106.6520
  }
];

const CATEGORIES = {
  bisnis: "비즈니스 M&A",
  ruko: "루코 & 상업용 부동산",
  properti: "부동산 매매",
  c2c: "직거래 (C2C)"
};

const LOCATIONS = [
  "전체 지역",
  "Jakarta Utara",
  "Jakarta Selatan",
  "Jakarta Barat",
  "Jakarta Timur",
  "Jakarta Pusat",
  "Gading Serpong",
  "BSD",
  "Depok",
  "Tangerang",
  "Bekasi",
  "Bali",
  "Surabaya",
  "Bandung",
  "Semarang"
];

const LOCATION_KO = {
  "전체 지역": "전체 지역",
  "Jakarta Utara": "자카르타 북부",
  "Jakarta Selatan": "자카르타 남부",
  "Jakarta Barat": "자카르타 서부",
  "Jakarta Timur": "자카르타 동부",
  "Jakarta Pusat": "자카르타 중부",
  "Gading Serpong": "가딩 세르퐁",
  "BSD": "BSD",
  "Depok": "데포",
  "Tangerang": "탕그랑",
  "Bekasi": "브카시",
  "Bali": "발리",
  "Surabaya": "수라바야",
  "Bandung": "반둥",
  "Semarang": "스마랑"
};

const BUSINESS_TYPES = [
  "전체 업종",
  "카페 & 레스토랑",
  "프랜차이즈",
  "제조업",
  "주차장",
  "뷰티 & 클리닉",
  "편의점 & 소매",
  "피트니스",
  "루코",
  "토지",
  "사무실 빌딩",
  "빌라 & 부동산",
  "세탁소",
  "교육 학원",
  "IT & 스타트업",
  "물류 창고",
  "숙박업",
  "자동차 서비스"
];
