// 자동 생성 파일 — scraper/scrape_99co.py 가 갱신합니다. 직접 수정 금지.
// 갱신 시각: 2026-07-21T03:18:16+00:00
const LIVE_LISTINGS_UPDATED_AT = "2026-07-21T03:18:16+00:00";
const LIVE_LISTINGS = [
  {
    "id": "live-1012747621",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Depok LT 80m2 & LB 240m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3 Miliar",
    "priceNum": 3000000000,
    "established": null,
    "area": 240.0,
    "floors": 1,
    "description": "FOR SALE! Ruko di Depok, Jawa Barat. Spesifikasi: LT 80m2, LB 240m2, cocok untuk berbagai jenis bisnis Area tidak perlu diragukan lagi karena strategis. 2 menit ke LRT Harjamukti, 7 menit ke Tol Cimanggis - ------------------------------------------------------------ Kesempatan terbatas buat Anda...",
    "facilities": [
      "토지 80m²",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-sukatani-cp-1012747621",
    "lat": -6.38093,
    "lng": 106.895821
  },
  {
    "id": "live-1010182610",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Cinere Depok dengan LB 250m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,75 Miliar",
    "priceNum": 3750000000,
    "established": null,
    "area": 250.0,
    "floors": 3,
    "description": "Tersedia Ruko lokasi Cinere, Depok, Jawa Barat. Spesifikasi luas: LT: 147m2, LB: 250m2 Harga penawaran spesial Rp 3,75 Miliar ------------------------------------------------------------ Ruko 3 Lantai Siap Pakai di Cinere - Lokasi Super Strategis & Ramai! Ruko ini punya lokasi emas di pinggir jal...",
    "facilities": [
      "토지 147m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-cinere-cp-1010182610",
    "lat": -6.33298,
    "lng": 106.778412
  },
  {
    "id": "live-1010140280",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Favorit Dijual di Cimanggis Depok Kawasan Pusat Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 850 Juta",
    "priceNum": 850000000,
    "established": null,
    "area": 79.0,
    "floors": 1,
    "description": "Unit Ruko di Cimanggis, Depok, Jawa Barat dijual dengan harga Rp 850 Juta. LT 55m2 / LB 79m2. Pastikan Anda memilih Ruko yang punya potensi bisnis besar. Harga jual Rp 850 Juta ------------------------------------------------------------ Ruko Dijual Depok LOKASI STRATEGIS Aksebilitas tinggi, deka...",
    "facilities": [
      "토지 55m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-850jt-cimanggis-cp-1010140280",
    "lat": -6.39199,
    "lng": -6.39199
  },
  {
    "id": "live-1013891236",
    "type": "ruko",
    "subtype": "jual",
    "title": "FOR SALE! Ruko di Sawangan Depok, LT 68m2, LB 114m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,15 Miliar",
    "priceNum": 1150000000,
    "established": null,
    "area": 114.0,
    "floors": 2,
    "description": "Ruko dijual, lokasi strategis di Sawangan, Depok Spesifikasi tanah 68m2, bangunan 114m2 Harga jual: Rp 1,15 Miliar Lokasi dan akses mudah. ------------------------------------------------------------ Ruko 2 Lantai Murah di Pinggir Jalan Muchtar Sawangan Depok Dijual ruko pinggir jalan di lingkung...",
    "facilities": [
      "토지 68m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-sawangan-cp-1013891236",
    "lat": -6.39289,
    "lng": 106.76178
  },
  {
    "id": "live-1014031705",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Cinere Depok 175m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 7 Miliar",
    "priceNum": 7000000000,
    "established": null,
    "area": 175.0,
    "floors": 3,
    "description": "Rumah Toko dijual di Cinere, Depok, Jawa Barat. Spesifikasi Ruko: Luas tanah 166m2, luas bangunan 175m2 Harga Rp 7 Miliar. Lokasi Ruko strategis. 6 menit ke Pintu Tol Desari, 11 menit ke Terminal Dewi Sri, 11 menit ke Stasiun Fatmawati ------------------------------------------------------------ ...",
    "facilities": [
      "토지 166m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-7miliar-cinere-cp-1014031705",
    "lat": -6.33298,
    "lng": 106.778412
  },
  {
    "id": "live-1000279217",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Margonda Depok Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 700 Juta",
    "priceNum": 700000000,
    "established": null,
    "area": 17.0,
    "floors": 1,
    "description": "DIJUAL CEPAT Unit Komersil di Apartment Atlanta Depok Ruko bagus di Margonda Depok ini memiliki lokasi yang sangat strategis. 3 menit ke Stasiun Depok Baru, 4 menit ke Stasiun Pondok Cina, 6 menit ke Stasiun UI Jadi sangat memudahkan akses dan memiliki pasar yang besar. Memiliki LT 17m2, LB 17m2 ...",
    "facilities": [
      "토지 17m²",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-700jt-margonda-cp-1000279217",
    "lat": -6.3804,
    "lng": 106.8307
  },
  {
    "id": "live-1006890183",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Favorit Dijual di Pancoran Mas Depok Area Pusat Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5,8 Miliar",
    "priceNum": 5800000000,
    "established": null,
    "area": 430.0,
    "floors": 3,
    "description": "Ruko untuk dijual di Depok, Jawa Barat. Memiliki luas tanah 154m2 dan luas bangunan 430m2. Harga Rp 5,8 Miliar Dijual cepat! Hubungi kami sekarang juga. ------------------------------------------------------------ Profil Aset Jl. Sarwo EdhiJL. Margonda Raya No. 56, Ruko.ITC Depok 38/39 Kel. Depok...",
    "facilities": [
      "토지 154m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5miliar-pancoran-mas-cp-1006890183",
    "lat": -6.39444,
    "lng": 106.80819
  },
  {
    "id": "live-1007304695",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual Lokasi Stratagis di Cinere Depok Cocok untuk Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 20 Miliar",
    "priceNum": 20000000000,
    "established": null,
    "area": 3000.0,
    "floors": 3,
    "description": "Ruko komersial di Cinere, Depok untuk dijual. Cocok untuk berbisnis. LT 1354m2, LB 3000m2, dan juga dilengkapi 5 KM. Lokasi emas. 6 menit ke Pintu Tol Desari, 11 menit ke Terminal Dewi Sri, 11 menit ke Stasiun Fatmawati Harga jual: Rp 20 Miliar ----------------------------------------------------...",
    "facilities": [
      "토지 1354m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-20miliar-cinere-cp-1007304695",
    "lat": -6.33298,
    "lng": 106.77841
  },
  {
    "id": "live-1006098291",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Usaha Dijual di Sawangan Depok LT 52m2 & LB 86m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,5 Miliar",
    "priceNum": 1500000000,
    "established": null,
    "area": 86.0,
    "floors": 2,
    "description": "Dijual Ruko lokasi Sawangan, Depok, Jawa Barat. Spesifikasi luas: LT: 52m2, LB: 86m2 Harga penawaran spesial Rp 1,5 Miliar ------------------------------------------------------------ Dijual Ruko Siap untuk Usaha, Sngt Strategis Di Sawangan,depok sudah include all in pajak2 Ada AC 3 unit Area Par...",
    "facilities": [
      "토지 52m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-sawangan-cp-1006098291",
    "lat": -6.39289,
    "lng": 106.76178
  },
  {
    "id": "live-1006115681",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Paling Dicari LB 118m2 Dijual di Limo",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,15 Miliar",
    "priceNum": 2150000000,
    "established": null,
    "area": 118.0,
    "floors": 2,
    "description": "Ruko komersial dijual di kawasan Limo, Depok. Spesifikasi: Luas tanah 127m2 dan bangunan 118m2. Area strategis! 7 menit ke Pintu Tol Desari, 13 menit ke Terminal Dewi Sri Harga Rp 2,15 Miliar ------------------------------------------------------------ Dijual Ruko Cinere dekat Samsat Harga : Rp 2...",
    "facilities": [
      "토지 127m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-limo-cp-1006115681",
    "lat": -6.34925,
    "lng": 106.77282
  },
  {
    "id": "live-1009720957",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Depok I Depok Lokasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,35 Miliar",
    "priceNum": 1350000000,
    "established": null,
    "area": 180.0,
    "floors": 2,
    "description": "DIJUAL CEPAT Ruko 2 lantai cocok buat gym + studio musik. Hadap timur, Bebas banjir, Plafon Tinggi. Oke banget deh pokoknya. Ruko bagus di Depok I Depok ini memiliki lokasi yang sangat strategis. 8 menit ke Terminal Jatijajar, 10 menit ke Stasiun Depok Baru, 12 menit ke Stasiun Depok Jadi sangat ...",
    "facilities": [
      "토지 90m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-depok-i-cp-1009720957",
    "lat": -6.3994874,
    "lng": 106.8567504
  },
  {
    "id": "live-1011928783",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Strategis di Cimanggis, Depok Potensi Cuan Besar",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 13 Miliar",
    "priceNum": 13000000000,
    "established": null,
    "area": 975.0,
    "floors": 3,
    "description": "Dijual Ruko lokasi Cimanggis, Depok, Jawa Barat. Spesifikasi luas: LT: 405m2, LB: 975m2 Harga penawaran spesial Rp 13 Miliar ------------------------------------------------------------ Turun Harga 13M now!! Dijual Ruko 5gandeng di Podomoro golf view, Cimanggis Cocok untuk tempat Gym, toko Buah d...",
    "facilities": [
      "토지 405m²",
      "ppjb 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-13miliar-cimanggis-cp-1011928783",
    "lat": -6.39199,
    "lng": 106.890617
  },
  {
    "id": "live-1008986812",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 430m2 Lokasi Strategis Depok Area Cocok untuk Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5,8 Miliar",
    "priceNum": 5800000000,
    "established": null,
    "area": 430.0,
    "floors": 3,
    "description": "Ruko dijual di Depok II, Depok. Spesifikasi luas: LT 154m2, LB 430m2 Harga Rp 5,8 Miliar - ------------------------------------------------------------ **Dijual Ruko Strategis di Jl. Sarwo Edhi, Jl. Margonda Raya, Depok** **Spesifikasi Ruko:** - Luas Tanah: 154 m² - Luas Bangunan: 430 m² - Ukuran...",
    "facilities": [
      "토지 154m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5miliar-depok-ii-cp-1008986812",
    "lat": -6.399129299999999,
    "lng": 106.81959649999999
  },
  {
    "id": "live-1012830795",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Margonda Depok Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,5 Miliar",
    "priceNum": 3500000000,
    "established": null,
    "area": 272.0,
    "floors": 3,
    "description": "Unit Ruko siap milik di Margonda Depok Lokasi paling strategis. 3 menit ke Stasiun Depok Baru, 4 menit ke Stasiun Pondok Cina, 6 menit ke Stasiun UI Luas tanah 111m2, luas bangunan 272m2, dengan fasilitas sekitar yang lengkap. Harga jual Rp 3,5 Miliar ---------------------------------------------...",
    "facilities": [
      "토지 111m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-margonda-cp-1012830795",
    "lat": -6.3804,
    "lng": 106.830704
  },
  {
    "id": "live-1013292449",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Depok LT 73m2 & LB 219m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,7 Miliar",
    "priceNum": 3700000000,
    "established": null,
    "area": 219.0,
    "floors": 3,
    "description": "Dijual Ruko di Depok, Jawa Barat Area sangat strategis untuk bangun bisnis 3 menit ke Stasiun Depok Baru, 4 menit ke Stasiun Pondok Cina, 6 menit ke Stasiun UI Ruko ini memiliki LT 73m2, LB 219m2. Harga Rp 3,7 Miliar ------------------------------------------------------------ Dijual Melalui Lela...",
    "facilities": [
      "토지 73m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-margonda-cp-1013292449",
    "lat": -6.3804,
    "lng": 106.830704
  },
  {
    "id": "live-1011959521",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 115m2 Lokasi Strategis Depok Area Cocok untuk Berbisnis",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,5 Miliar",
    "priceNum": 2500000000,
    "established": null,
    "area": 115.0,
    "floors": 2,
    "description": "DIJUAL CEPAT Di Jual Ruko Lokasi Ramai Dan Strategis Di Raffles Hills Cibubur Ruko bagus di Cibubur Depok ini memiliki lokasi yang sangat strategis. 6 menit ke LRT Harjamukti, 10 menit ke Tol Cimanggis, 9 menit ke Stasiun LRT Ciracas Jadi sangat memudahkan akses dan punya pasar yang besar. Memili...",
    "facilities": [
      "토지 76m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-cibubur-cp-1011959521",
    "lat": -6.35611,
    "lng": 106.895111
  },
  {
    "id": "live-1012438220",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Cipayung Depok Luas Tanah 282m2, Luas Bangunan 500m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5,9 Juta",
    "priceNum": 5900000,
    "established": null,
    "area": 500.0,
    "floors": 2,
    "description": "Ruko dijual di Cipayung, Depok! Memiliki LT 282m2, LB 500m2. Harga: Rp 5,9 Juta. Potensi bisnis Ruko ini sangat besar. Lokasinya strategis. 8 menit ke Stasiun Depok, 9 menit ke Stasiun Citayam, 13 menit ke Stasiun Depok Baru ------------------------------------------------------------ DIJUAL RUKO...",
    "facilities": [
      "토지 282m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5jt-cipayung-cp-1012438220",
    "lat": -6.419744,
    "lng": 106.796066
  },
  {
    "id": "live-1003274441",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Cinere Depok Luas Bangunan 200m2",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 12 Miliar",
    "priceNum": 12000000000,
    "established": null,
    "area": 200.0,
    "floors": 1,
    "description": "Untuk Dijual Ruko di Cinere, Depok Spesifikasi: LT 400m2, LB 200m2 Harga Rp 12 Miliar SHM 5 menit ke Pintu Tol Desari, 12 menit ke Terminal Dewi Sri, 11 menit ke Stasiun Fatmawati ------------------------------------------------------------ Cinere Raya, jual tanah dan bangunan lokasi strategis ko...",
    "facilities": [
      "토지 400m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-12miliar-cinere-cp-1003274441",
    "lat": -6.3333023,
    "lng": 106.7828744
  },
  {
    "id": "live-1012151782",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus LT 600m2 LB 450m2 Dijual di Cimanggis Depok",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5,5 Miliar",
    "priceNum": 5500000000,
    "established": null,
    "area": 450.0,
    "floors": 1,
    "description": "DIJUAL CEPAT! Turun Harga Dijual Ruko Jln Raya Radar Auri Lokasi: - Kecamatan: Cimanggis - Kota: Depok Spesifikasi: - LT 600m2 - LB 450m2 Lokasi prime area. 5 menit ke LRT Harjamukti, 10 menit ke Tol Cimanggis Harga Rp 5,5 Miliar ------------------------------------------------------------ Dijual...",
    "facilities": [
      "토지 600m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5miliar-cimanggis-cp-1012151782",
    "lat": -6.39199,
    "lng": 106.890617
  },
  {
    "id": "live-1012828688",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Depok LT 115m2 & LB 230m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Depok",
    "locationKo": "데포",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,3 Miliar",
    "priceNum": 2300000000,
    "established": null,
    "area": 230.0,
    "floors": 2,
    "description": "DIJUAL CEPAT Ruko Murah Siap Pakai Dipinggir Jalan Raya Besar Depok Ruko bagus di Sukmajaya Depok ini memiliki lokasi yang sangat strategis. Jadi sangat memudahkan akses dan memiliki pasar yang besar. Memiliki LT 115m2, LB 230m2 Harga Rp 2,3 Miliar Jangan sampai kelewatan! -----------------------...",
    "facilities": [
      "토지 115m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-sukmajaya-cp-1012828688",
    "lat": -6.39692,
    "lng": -6.39692
  },
  {
    "id": "live-1001400885",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Prime Area Bekasi Luas 154m2",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,1 Miliar",
    "priceNum": 1100000000,
    "established": null,
    "area": 154.0,
    "floors": 3,
    "description": "Siap Milik Ruko di Bekasi, Jawa Barat Area paling strategis untuk bangun bisnis 7 menit ke Stasiun Kranji, 8 menit ke Stasiun Cakung, 9 menit ke Halte Busway Walikota Kota Administrasi Jakarta Timur Arah Terminal Pulo Gebang Ruko ini memiliki LT 107m2, LB 154m2. Harga Rp 1,1 Miliar --------------...",
    "facilities": [
      "토지 107m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-bekasi-kota-cp-1001400885",
    "lat": -6.20116,
    "lng": 106.97735
  },
  {
    "id": "live-1009003692",
    "type": "ruko",
    "subtype": "jual",
    "title": "Dijual! Ruko di Bantar Gebang Bekasi LT 121m2 / LB 200m2 Kawasan Strategis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2 Miliar",
    "priceNum": 2000000000,
    "established": null,
    "area": 200.0,
    "floors": 2,
    "description": "Siap Milik Ruko di Bekasi, Jawa Barat Area paling strategis untuk bangun bisnis Ruko ini memiliki LT 121m2, LB 200m2. Harga Rp 2 Miliar ------------------------------------------------------------ Dijual ruko 1 setengah lantai siap beropersai/huni dipinggir jalan raya narogong akses ke tol narogo...",
    "facilities": [
      "토지 121m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-bantar-gebang-cp-1009003692",
    "lat": -6.3414752,
    "lng": 106.9898519
  },
  {
    "id": "live-2204263",
    "type": "ruko",
    "subtype": "jual",
    "title": "Terra At Pospera HUB Grand Wisata",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,89 Miliar",
    "priceNum": 4890155852,
    "established": null,
    "area": null,
    "floors": null,
    "description": "<p>Grand Wisata Bekasi merupakan kawasan pemukiman modern yang dikembangkan oleh Sinar Mas Land, Grand Wisata Bekasi menciptakan sinergitas antara lingkungan hunian yang nyaman dan asri serta mampu mengakomodir kegiatan bisnis penghuninya. Grand wisata bekasi juga memadupadankan konsep Live, Play...",
    "facilities": [
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/terra-at-pospera-hub-grand-wisata-2204263",
    "lat": -6.279090099999999,
    "lng": 107.0479557
  },
  {
    "id": "live-1010895472",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Cibubur Bekasi Lokasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,9 Miliar",
    "priceNum": 3900000000,
    "established": null,
    "area": 200.0,
    "floors": 3,
    "description": "Ruko dijual di pusat bisnis Bekasi. Memiliki luas bangunan 200m2 dan tanah 70m2. Harga Rp 3,9 Miliar bisa nego Lokasi paling dicari. 6 menit ke LRT Harjamukti, 10 menit ke Tol Cimanggis, 9 menit ke Stasiun LRT Ciracas ------------------------------------------------------------ Ruko di Cibubur, B...",
    "facilities": [
      "토지 70m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-cibubur-cp-1010895472",
    "lat": -6.35611,
    "lng": 106.89511
  },
  {
    "id": "live-1013259547",
    "type": "ruko",
    "subtype": "jual",
    "title": "Dijual! Ruko di Summarecon Bekasi Bekasi LT 85m2 / LB 272m2 Kawasan Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,95 Miliar",
    "priceNum": 2950000000,
    "established": null,
    "area": 272.0,
    "floors": 3,
    "description": "Dijual Ruko di Summarecon Bekasi, Bekasi, Jawa Barat. Unit Ruko ini memiliki LT 85m2, LB 272m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 2,95 Miliar ------------------------------------------------------------ Ruko Emerald Summarecon Bekasi Ukuran 5 x 17 Lt 85 m2 Lb 272 m2 Kamar ...",
    "facilities": [
      "토지 85m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-summarecon-bekasi-cp-1013259547",
    "lat": -6.226128,
    "lng": 107.001076
  },
  {
    "id": "live-1011006748",
    "type": "ruko",
    "subtype": "jual",
    "title": "Dijual! Ruko di Jatikarya Bekasi LT 75m2 / LB 150m2 Kawasan Strategis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,5 Miliar",
    "priceNum": 2500000000,
    "established": null,
    "area": 150.0,
    "floors": 2,
    "description": "Ruko dijual di pusat bisnis Bekasi. Memiliki luas bangunan 150m2 dan tanah 75m2. Harga Rp 2,5 Miliar bisa nego Lokasi paling dicari. 1 menit ke Stasiun Bekasi, 6 menit ke Stasiun Kranji, 6 menit ke Terminal Bekasi Kota ------------------------------------------------------------ Letak strategis. ...",
    "facilities": [
      "토지 75m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-jatikarya-cp-1011006748",
    "lat": -6.23333,
    "lng": 107
  },
  {
    "id": "live-1013606230",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Jatimulya Bekasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,7 Miliar",
    "priceNum": 1700000000,
    "established": null,
    "area": 255.0,
    "floors": null,
    "description": "Ruko untuk dijual di Jatimulya Bekasi, Jawa Barat. Potensi bisnis besar. Spesifikasi lengkap: LT 85m2, LB 255m2 Kawasan sangat strategis, cocok untuk mengembangkan bisnis! Lokasi: 2 menit ke LRT Jati Mulya, 2 menit ke Stasiun LRT Jatimulya, 4 menit ke Pintu Tol Bekasi Timur ----------------------...",
    "facilities": [
      "토지 85m²",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-jatimulya-cp-1013606230",
    "lat": -6.263445969880636,
    "lng": 107.02791062562915
  },
  {
    "id": "live-1013944770",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual Lokasi Stratagis di Tambun Utara Bekasi Cocok untuk Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,8 Miliar",
    "priceNum": 4800000000,
    "established": null,
    "area": 1490.0,
    "floors": 1,
    "description": "Ruko untuk dijual, lokasi Tambun Utara Bekasi. Cocok untuk investasi Anda! Spesifikasi: LT 1490m2, LB 1490m2. Harga Rp 4,8 Miliar Ruko ini banyak dicari karena lokasinya yang amat strategis. 13 menit ke Stasiun Bekasi Timur ------------------------------------------------------------ Dijual via l...",
    "facilities": [
      "토지 1490m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-tambun-utara-cp-1013944770",
    "lat": -6.207423340223731,
    "lng": 107.03734491730692
  },
  {
    "id": "live-1006580208",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Prime Area Bekasi Luas 600m2",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5 Miliar",
    "priceNum": 5000000000,
    "established": null,
    "area": 600.0,
    "floors": 4,
    "description": "Dijual Ruko di Pondok Gede, Bekasi, Jawa Barat. Unit Ruko ini memiliki LT 150m2, LB 600m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 5 Miliar ------------------------------------------------------------ Belakang nampak 4.5 lantai Depan nampak 3.5 lantai LT 10 x 15 m2 LB 600 m2 IMB...",
    "facilities": [
      "토지 150m²",
      "4층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5miliar-pondok-gede-cp-1006580208",
    "lat": 0,
    "lng": 0
  },
  {
    "id": "live-1011042526",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Cut Mutia Bekasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 21 Miliar",
    "priceNum": 21000000000,
    "established": null,
    "area": 1000.0,
    "floors": 4,
    "description": "Unit Ruko siap milik di Cut Mutia Bekasi Lokasi paling strategis. 3 menit ke Pintu Tol Bekasi Timur, 4 menit ke Terminal Bekasi Kota, 5 menit ke Stasiun LRT Bekasi Barat Luas tanah 1055m2, luas bangunan 1000m2, dengan fasilitas sekitar yang mumpuni. Harga jual Rp 21 Miliar -----------------------...",
    "facilities": [
      "토지 1055m²",
      "shm 증서",
      "4층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-21miliar-cut-mutia-cp-1011042526",
    "lat": -6.257399,
    "lng": 107.004738
  },
  {
    "id": "live-1012101431",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 119m2 Lokasi Strategis Bekasi Area Cocok untuk Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,4 Miliar",
    "priceNum": 1400000000,
    "established": null,
    "area": 119.0,
    "floors": 1,
    "description": "DIJUAL CEPAT Ruko Bagus Dekat Pasar Harapan Indah. Bekasi Barat Ruko di Harapan Indah SHM Ruko bagus di Harapan Indah Bekasi ini memiliki lokasi yang sangat strategis. Jadi sangat memudahkan akses dan punya pasar yang besar. Memiliki LT 83m2, LB 119m2 Harga Rp 1,4 Miliar Jangan sampai kelewatan! ...",
    "facilities": [
      "토지 83m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-harapan-indah-cp-1012101431",
    "lat": -6.17569,
    "lng": 106.987968
  },
  {
    "id": "live-1011090668",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Pondok Ungu Bekasi Lokasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,8 Miliar",
    "priceNum": 2800000000,
    "established": null,
    "area": 200.0,
    "floors": 1,
    "description": "Unit Ruko siap milik di Pondok Ungu Bekasi Lokasi paling strategis. 1 menit ke Stasiun Bekasi, 6 menit ke Stasiun Kranji, 6 menit ke Terminal Bekasi Kota Luas tanah 303m2, luas bangunan 200m2, dengan fasilitas sekitar yang lengkap. Harga jual Rp 2,8 Miliar ----------------------------------------...",
    "facilities": [
      "토지 303m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-pondok-ungu-cp-1011090668",
    "lat": -6.23333,
    "lng": 107
  },
  {
    "id": "live-1011547532",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko For Sale di Kawasan Tambun Utara, Bekasi Harga Kompetitif",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,25 Miliar",
    "priceNum": 1250000000,
    "established": null,
    "area": 115.0,
    "floors": 3,
    "description": "Dijual Ruko di Tambun Utara, Bekasi Spesifikasi: LT 60m2, LB 115m2 Harga Rp 1,25 Miliar SHM Parkir Mobil 7 menit ke Stasiun Tambun, 10 menit ke Stasiun Bekasi Timur, 11 menit ke Terminal Bekasi Kota ------------------------------------------------------------ Di jual ruko baru strategis di alaman...",
    "facilities": [
      "토지 60m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-tambun-utara-cp-1011547532",
    "lat": -6.23741,
    "lng": 107.048889
  },
  {
    "id": "live-1011547509",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Strategis di Tambun Utara, Bekasi Potensi Cuan Besar",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,7 Miliar",
    "priceNum": 1700000000,
    "established": null,
    "area": 155.0,
    "floors": 2,
    "description": "DIJUAL CEPAT! Jual Ruko Gandeng Strategis Di Alamanda Residence Tambun Bekasi Lokasi: - Kecamatan: Tambun Utara - Kota: Bekasi Spesifikasi: - LT 120m2 - LB 155m2 Lokasi prime area. 7 menit ke Stasiun Tambun, 10 menit ke Stasiun Bekasi Timur, 11 menit ke Terminal Bekasi Kota Harga Rp 1,7 Miliar --...",
    "facilities": [
      "토지 120m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-tambun-utara-cp-1011547509",
    "lat": -6.23741,
    "lng": 107.048889
  },
  {
    "id": "live-1012832812",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Bekasi LT 82m2 & LB 288m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2 Miliar",
    "priceNum": 2000000000,
    "established": null,
    "area": 288.0,
    "floors": 3,
    "description": "Unit komersial di Bekasi dijual dengan LT 82m2, LB 288m2 Kawasan sangat strategis, cocok untuk investasi Lokasi di area ramai. 6 menit ke Stasiun Cikarang, 8 menit ke Terminal Cikarang Harga Rp 2 Miliar ------------------------------------------------------------ Luas Tanah 82,5 M² Luas Bangunan ...",
    "facilities": [
      "토지 82m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-cikarang-cp-1012832812",
    "lat": -6.2513,
    "lng": 107.166267
  },
  {
    "id": "live-1013606550",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 0m2 Lokasi Strategis Bekasi Area Cocok untuk Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 10 Miliar",
    "priceNum": 10000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "DIJUAL CEPAT Ruko Gandeng Kawasan Citra Grand Jl Alternatif Cibubur Ruko bagus di Bekasi Bekasi ini memiliki lokasi yang sangat strategis. Jadi sangat memudahkan akses dan punya pasar yang besar. Memiliki LT 1m2, LB 0m2 Harga Rp 10 Miliar Jangan sampai kelewatan! ---------------------------------...",
    "facilities": [
      "토지 1m²",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-10miliar-bekasi-cp-1013606550",
    "lat": -6.19922,
    "lng": -6.19922
  },
  {
    "id": "live-1013057823",
    "type": "ruko",
    "subtype": "jual",
    "title": "Paling Diincar! Ruko Dijual di Delta Mas Harga Kompetitif",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,15 Miliar",
    "priceNum": 1150000000,
    "established": null,
    "area": 84.0,
    "floors": 1,
    "description": "Unit komersial di Bekasi dijual dengan LT 42m2, LB 84m2 Area sangat strategis, cocok untuk bisnis Lokasi di area ramai. 2 menit ke Stasiun Cikarang, 5 menit ke Terminal Cikarang Harga Rp 1,15 Miliar ------------------------------------------------------------ Kesempatan terbatas buat Anda dapatka...",
    "facilities": [
      "토지 42m²",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-delta-mas-cp-1013057823",
    "lat": -6.24745,
    "lng": 107.148453
  },
  {
    "id": "live-1011672867",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual Lokasi Stratagis di Tarumajaya Bekasi Cocok untuk Bisnis",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,8 Miliar",
    "priceNum": 1800000000,
    "established": null,
    "area": 220.0,
    "floors": 3,
    "description": "Unit Ruko komersial dijual di Bekasi. LT 100m2 & LB 220m2 Harga penawaran Rp 1,8 Miliar Target pasar besar karena lokasinya strategis. ------------------------------------------------------------ BEST DEALLL!!! Ruko Ifolia cocok untuk kantor & gudang barang import Parkiran bs untuk truk fuso 40 f...",
    "facilities": [
      "토지 100m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-tarumajaya-cp-1011672867",
    "lat": -6.1199,
    "lng": 106.996536
  },
  {
    "id": "live-1011460756",
    "type": "ruko",
    "subtype": "jual",
    "title": "Untuk Dijual Ruko di Medan Satria Bekasi LT 83m2 / LB 117m2",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,25 Miliar",
    "priceNum": 1250000000,
    "established": null,
    "area": 117.0,
    "floors": 2,
    "description": "Ruko dijual di Medan Satria, Bekasi! Memiliki LT 83m2, LB 117m2. Harga: Rp 1,25 Miliar. Potensi bisnis Ruko ini sangat tinggi. Lokasinya strategis. 12 menit ke Stasiun Kranji, 11 menit ke Terminal Pulogebang ------------------------------------------------------------ BEST DEAL !!! TERMURAH !!! R...",
    "facilities": [
      "토지 83m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-medan-satria-cp-1011460756",
    "lat": -6.18429,
    "lng": 106.985458
  },
  {
    "id": "live-1011601598",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Paling Dicari LB 300m2 Dijual di Tarumajaya",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,05 Miliar",
    "priceNum": 4050000000,
    "established": null,
    "area": 300.0,
    "floors": 4,
    "description": "Unit Ruko di Tarumajaya, Bekasi, Jawa Barat dijual dengan harga Rp 4,05 Miliar. LT 90m2 / LB 300m2. Pastikan Anda memilih Ruko yang punya potensi keuntungan besar. Harga jual Rp 4,05 Miliar ------------------------------------------------------------ Jual Cepat Ruko 4 lantai, lokasi strategis Har...",
    "facilities": [
      "토지 90m²",
      "shm 증서",
      "4층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-tarumajaya-cp-1011601598",
    "lat": -6.1199,
    "lng": 106.996536
  },
  {
    "id": "live-1011538991",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Prime Area Bekasi Luas 150m2",
    "category": "루코",
    "location": "Bekasi",
    "locationKo": "브카시",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,05 Miliar",
    "priceNum": 2050000000,
    "established": null,
    "area": 150.0,
    "floors": 2,
    "description": "Tersedia Ruko di Jatimakmur, Bekasi, Jawa Barat. Unit Ruko ini memiliki LT 102m2, LB 150m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 2,05 Miliar ------------------------------------------------------------ Ruko Baru di Jatimakmur SHM 2 Lantai Tol Jatibening Lokasi Strategis Bagus...",
    "facilities": [
      "토지 102m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-jatimakmur-cp-1011538991",
    "lat": -6.269443640240851,
    "lng": 106.93563573291141
  },
  {
    "id": "live-1009862918",
    "type": "ruko",
    "subtype": "jual",
    "title": "Dijual! Ruko di Taman Kopo Indah Bandung LT 65m2 / LB 100m2 Kawasan Strategis",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,7 Miliar",
    "priceNum": 1700000000,
    "established": null,
    "area": 100.0,
    "floors": 2,
    "description": "Dijual Ruko di Taman Kopo Indah, Bandung, Jawa Barat. Unit Ruko ini memiliki LT 65m2, LB 100m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 1,7 Miliar ------------------------------------------------------------ *FOR SALE ASAP* *RUKO TKI 1 MAINROAD lokasi ramai deket sekolah, minima...",
    "facilities": [
      "토지 65m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-taman-kopo-indah-cp-1009862918",
    "lat": -6.96188,
    "lng": 107.557732
  },
  {
    "id": "live-1009863030",
    "type": "ruko",
    "subtype": "jual",
    "title": "Dijual! Ruko di Sudirman Bandung LT 164m2 / LB 540m2 Kawasan Strategis",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 10,5 Miliar",
    "priceNum": 10500000000,
    "established": null,
    "area": 540.0,
    "floors": 4,
    "description": "Ruko dijual di pusat bisnis Bandung. Memiliki luas bangunan 540m2 dan tanah 164m2. Harga Rp 10,5 Miliar bisa nego Lokasi paling dicari. 4 menit ke Stasiun Bandung, 5 menit ke Stasiun Hall Bandung, 5 menit ke Bandara Husein Bandung ------------------------------------------------------------ *FOR ...",
    "facilities": [
      "토지 164m²",
      "4층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-10miliar-sudirman-cp-1009863030",
    "lat": -6.91906,
    "lng": 107.589561
  },
  {
    "id": "live-1009859010",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Bandung LT 78m2 & LB 150m2",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,9 Miliar",
    "priceNum": 2900000000,
    "established": null,
    "area": 150.0,
    "floors": 3,
    "description": "Unit Ruko siap milik di Leuwi Panjang Bandung Lokasi paling strategis. 1 menit ke Stasiun Hall Bandung, 1 menit ke Stasiun Bandung, 9 menit ke Bandara Husein Bandung Luas tanah 78m2, luas bangunan 150m2, dengan fasilitas sekitar yang lengkap. Harga jual Rp 2,9 Miliar -----------------------------...",
    "facilities": [
      "토지 78m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-leuwi-panjang-cp-1009859010",
    "lat": -6.91243,
    "lng": 107.606903
  },
  {
    "id": "live-1012768485",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Asia Afrika Bandung Lokasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,3 Miliar",
    "priceNum": 4300000000,
    "established": null,
    "area": 187.0,
    "floors": 1,
    "description": "Unit komersial di Bandung dijual dengan LT 104m2, LB 187m2 Area sangat strategis, cocok untuk investasi Lokasi di area ramai. 2 menit ke Stasiun Hall Bandung, 3 menit ke Stasiun Bandung, 8 menit ke Terminal Leuwipanjang Harga Rp 4,3 Miliar ---------------------------------------------------------...",
    "facilities": [
      "토지 104m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-asia-afrika-cp-1012768485",
    "lat": -6.92149,
    "lng": 107.60997
  },
  {
    "id": "live-1009863020",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Bandung LT 55m2 & LB 150m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,85 Miliar",
    "priceNum": 1850000000,
    "established": null,
    "area": 150.0,
    "floors": 2,
    "description": "Untuk dijual Ruko di Pasir Koja. Memiliki luas tanah 55m2 dan bangunan 150m2, Ruko ini cocok dijadikan aset investasi Anda. Harga penawaran hanya Rp 1,85 Miliar! ------------------------------------------------------------ FOR SALE *RUKO PASIR KOJA 1 ARAH MAINROAD* 2.5 Lantai LT 55 m LB 150 m Leb...",
    "facilities": [
      "토지 55m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-pasir-koja-cp-1009863020",
    "lat": -6.91243,
    "lng": 107.606903
  },
  {
    "id": "live-1009860753",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Bandung LT 78m2 & LB 250m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,45 Miliar",
    "priceNum": 1450000000,
    "established": null,
    "area": 250.0,
    "floors": 2,
    "description": "DIJUAL CEPAT Ruko Strategis Siap Huni Sayap Leuwipanjang Bandung Ruko bagus di Leuwi Panjang Bandung ini memiliki lokasi yang sangat strategis. 1 menit ke Stasiun Hall Bandung, 1 menit ke Stasiun Bandung, 9 menit ke Bandara Husein Bandung Jadi sangat memudahkan akses dan punya pasar yang besar. M...",
    "facilities": [
      "토지 78m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-leuwi-panjang-cp-1009860753",
    "lat": -6.91243,
    "lng": 107.606903
  },
  {
    "id": "live-1010754737",
    "type": "ruko",
    "subtype": "jual",
    "title": "Paling Diincar! Ruko Dijual di Kota Baru Parahyangan Harga Kompetitif",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5,66 Miliar",
    "priceNum": 5660000000,
    "established": null,
    "area": 269.0,
    "floors": 3,
    "description": "Ruko dijual di Kota Baru Parahyangan, Bandung. Spesifikasi luas: LT 98m2, LB 269m2 Harga Rp 5,66 Miliar - ------------------------------------------------------------ Type : Standar ▫️ Lebar muka : 7m ▫️ Panjang : 14m ▫️ Luas Tanah 98m2 ▫️ Luas Bangunan 269m2 ▫️ Toilet 2 perlantai ▫️ 3 Lantai ▫️ ...",
    "facilities": [
      "토지 98m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5miliar-kota-baru-parahyangan-cp-1010754737",
    "lat": -6.91243,
    "lng": 107.606903
  },
  {
    "id": "live-1012996984",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Otista Bandung Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4 Miliar",
    "priceNum": 4000000000,
    "established": null,
    "area": 170.0,
    "floors": 2,
    "description": "Untuk dijual Ruko di Otista. Memiliki luas tanah 150m2 dan bangunan 170m2, Ruko ini cocok dijadikan aset usaha Anda. Harga penawaran hanya Rp 4 Miliar! ------------------------------------------------------------ Lm 7.5 Luas tanah 150 Luas bangunan 170 2 lantai Kamar 2 Dapur 2 Listrik 2200w Air P...",
    "facilities": [
      "토지 150m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-otista-cp-1012996984",
    "lat": -6.91243,
    "lng": 107.606903
  },
  {
    "id": "live-1011493386",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Bandung LT 640m2 & LB 900m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25 Miliar",
    "priceNum": 25000000000,
    "established": null,
    "area": 900.0,
    "floors": 2,
    "description": "Dijual Ruko di Bandung, Jawa Barat Area paling strategis untuk bangun bisnis 4 menit ke Stasiun Hall Bandung, 5 menit ke Stasiun Bandung, 9 menit ke Terminal Sadang Serang Ruko ini memiliki LT 640m2, LB 900m2. Harga Rp 25 Miliar ------------------------------------------------------------ SHM, lu...",
    "facilities": [
      "토지 640m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-25miliar-braga-cp-1011493386",
    "lat": -6.91874,
    "lng": 107.618271
  },
  {
    "id": "live-1012766452",
    "type": "ruko",
    "subtype": "jual",
    "title": "Paling Dicari! Ruko Dijual di Cicadas Harga Kompetitif",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 325 Juta",
    "priceNum": 325000000,
    "established": null,
    "area": 15.0,
    "floors": 1,
    "description": "Untuk dijual Ruko di Cicadas. Memiliki luas tanah 15m2 dan bangunan 15m2, Ruko ini cocok dijadikan aset investasi Anda. Harga penawaran hanya Rp 325 Juta! ------------------------------------------------------------ Dijual ruko dinapartemen gateway cicadas cocok untuk segala usaha laundry, toko w...",
    "facilities": [
      "토지 15m²",
      "shm 증서",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-325jt-cicadas-cp-1012766452",
    "lat": -6.90685,
    "lng": 107.645844
  },
  {
    "id": "live-1005766429",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Bandung LT 125m2 & LB 180m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,3 Miliar",
    "priceNum": 2300000000,
    "established": null,
    "area": 180.0,
    "floors": 2,
    "description": "Unit komersial di Bandung dijual dengan LT 125m2, LB 180m2 Area sangat strategis, cocok untuk investasi Lokasi di area ramai. 8 menit ke Terminal Leuwipanjang, 10 menit ke Bandara Husein Bandung, 11 menit ke Stasiun Bandung Harga Rp 2,3 Miliar -----------------------------------------------------...",
    "facilities": [
      "토지 125m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-holis-cigondewah-cp-1005766429",
    "lat": -6.93427,
    "lng": 107.5715
  },
  {
    "id": "live-1009573332",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Bandung LT 75m2 & LB 180m2",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,65 Miliar",
    "priceNum": 3650000000,
    "established": null,
    "area": 180.0,
    "floors": 3,
    "description": "Ruko dijual di pusat bisnis Bandung. Memiliki luas bangunan 180m2 dan tanah 75m2. Harga Rp 3,65 Miliar nego Lokasi paling dicari. ------------------------------------------------------------ JUAL RUKO SUMMARECON MAGNA 75/180 3 lantai Listrik 4400 watt Lokasi sangat strategis untuk kantor atau tem...",
    "facilities": [
      "토지 75m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-summarecon-bandung-cp-1009573332",
    "lat": 0,
    "lng": 0
  },
  {
    "id": "live-1011915707",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual di Buah Batu Bandung Lokasi Strategis Cocok untuk Kembangkan Bisnis",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,8 Miliar",
    "priceNum": 1800000000,
    "established": null,
    "area": 140.0,
    "floors": 2,
    "description": "Ruko dijual di Buah Batu, Bandung. Spesifikasi luas: LT 100m2, LB 140m2 Harga Rp 1,8 Miliar - ------------------------------------------------------------ JUAL RUKO BUAH BATU SQUARE LT 100 m2 LB 140 m2 HGB 2 lantai 1 kamar mandi Listrik 2200 Watt Air Sommersible Posisi belakang transmart Tersewa ...",
    "facilities": [
      "토지 100m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-buah-batu-cp-1011915707",
    "lat": -6.9401,
    "lng": 107.625748
  },
  {
    "id": "live-1006914744",
    "type": "ruko",
    "subtype": "jual",
    "title": "Paling Dicari! Ruko Dijual di Taman Kopo Indah Harga Kompetitif",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,8 Miliar",
    "priceNum": 3800000000,
    "established": null,
    "area": 200.0,
    "floors": 3,
    "description": "DIJUAL CEPAT Ruko Bagus 3 Lantai di Taman Kopo Indah, Bandung Ruko bagus di Taman Kopo Indah Bandung ini memiliki lokasi yang sangat strategis. 2 menit ke Stasiun Hall Bandung, 2 menit ke Stasiun Bandung, 9 menit ke Terminal Sadang Serang Jadi sangat memudahkan akses dan memiliki pasar yang besar...",
    "facilities": [
      "토지 110m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-taman-kopo-indah-cp-1006914744",
    "lat": -6.91474,
    "lng": 107.61
  },
  {
    "id": "live-1007267559",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 120m2 Lokasi Strategis Bandung Area Cocok untuk Berbisnis",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,1 Miliar",
    "priceNum": 4100000000,
    "established": null,
    "area": 120.0,
    "floors": 2,
    "description": "Unit Ruko siap milik di mekar wangi Bandung Lokasi paling strategis. 6 menit ke Terminal Leuwipanjang, 7 menit ke Pintu Tol Buah Batu, 12 menit ke Stasiun Hall Bandung Luas tanah 100m2, luas bangunan 120m2, dengan fasilitas sekitar yang lengkap. Harga jual Rp 4,1 Miliar --------------------------...",
    "facilities": [
      "토지 100m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-mekar-wangi-cp-1007267559",
    "lat": -6.95472,
    "lng": 107.61348
  },
  {
    "id": "live-1013658357",
    "type": "ruko",
    "subtype": "jual",
    "title": "Lokasi Strategis! Dijual Ruko Bisnis di Soreang, Bandung Kondisi Bagus",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,8 Miliar",
    "priceNum": 2800000000,
    "established": null,
    "area": 216.0,
    "floors": 3,
    "description": "Rumah Toko dijual di Soreang, Bandung, Jawa Barat. Spesifikasi Ruko: Luas tanah 175m2, luas bangunan 216m2 Harga Rp 2,8 Miliar. Lokasi Ruko strategis. ------------------------------------------------------------ TURUN HARGA! JUAL RUKO STRATEGIS SOREANG LT 175 m2 LB 216 m2 Lebar muka 8 m 3 lantai ...",
    "facilities": [
      "토지 175m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-soreang-cp-1013658357",
    "lat": -6.97179,
    "lng": 107.538361
  },
  {
    "id": "live-41318555557",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Prime Area Bandung Luas 170m2",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,5 Miliar",
    "priceNum": 4500000000,
    "established": null,
    "area": 170.0,
    "floors": null,
    "description": "Ruko untuk dijual di Otista Bandung, Jawa Barat. Potensi usaha besar. Spesifikasi lengkap: LT 90m2, LB 170m2 Kawasan sangat strategis, sesuai untuk mengembangkan bisnis! Lokasi: 1 menit ke Stasiun Hall Bandung, 1 menit ke Stasiun Bandung, 9 menit ke Bandara Husein Bandung ------------------------...",
    "facilities": [
      "토지 90m²",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-otista-cp-41318555557",
    "lat": -6.91243,
    "lng": 107.6069
  },
  {
    "id": "live-1009574664",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Bandung LT 74m2 & LB 140m2",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,1 Miliar",
    "priceNum": 2100000000,
    "established": null,
    "area": 140.0,
    "floors": 2,
    "description": "Dijual Ruko di Bandung, Jawa Barat Area sangat strategis untuk bangun bisnis 1 menit ke Stasiun Hall Bandung, 1 menit ke Stasiun Bandung, 9 menit ke Bandara Husein Bandung Ruko ini memiliki LT 74m2, LB 140m2. Harga Rp 2,1 Miliar ------------------------------------------------------------ JUAL RU...",
    "facilities": [
      "토지 74m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-leuwi-panjang-cp-1009574664",
    "lat": -6.91243,
    "lng": 107.6069
  },
  {
    "id": "live-1013431829",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Bandung LT 155m2 & LB 200m2",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,1 Miliar",
    "priceNum": 3100000000,
    "established": null,
    "area": 200.0,
    "floors": 2,
    "description": "FOR SALE! Ruko di Bandung, Jawa Barat. Spesifikasi: LT 155m2, LB 200m2, cocok untuk berbagai jenis bisnis Area tak perlu diragukan lagi karena strategis. 5 menit ke Stasiun Hall Bandung, 6 menit ke Stasiun Bandung, 8 menit ke Stasiun Kiaracondong SHM ----------------------------------------------...",
    "facilities": [
      "토지 155m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-kosambi-cp-1013431829",
    "lat": -6.919105,
    "lng": 107.622673
  },
  {
    "id": "live-1003311329",
    "type": "ruko",
    "subtype": "jual",
    "title": "Paling Diincar! Ruko Dijual di Braga Harga Kompetitif",
    "category": "루코",
    "location": "Bandung",
    "locationKo": "반둥",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,5 Miliar",
    "priceNum": 3500000000,
    "established": null,
    "area": 363.0,
    "floors": 2,
    "description": "Ruko dijual di Braga, Bandung. Spesifikasi luas: LT 127m2, LB 363m2 Harga Rp 3,5 Miliar SHM ------------------------------------------------------------ JUAL RUKAN & GUDANG BANCEUY LT/LB 127/363 m LM 10,3 m Listrik 13200 watt Air PDAM SHM Harga 3,5M DC DINA CHRISTINA JPROPERTY 0858-9032-xxxx",
    "facilities": [
      "토지 127m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-braga-cp-1003311329",
    "lat": -6.91874,
    "lng": 107.61827
  },
  {
    "id": "live-1013616019",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 90m2 Lokasi Strategis Surabaya Area Cocok untuk Bisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,1 Miliar",
    "priceNum": 2100000000,
    "established": null,
    "area": 90.0,
    "floors": 2,
    "description": "Dijual Ruko di Surabaya, Jawa Timur Area paling strategis untuk bangun bisnis Ruko ini memiliki LT 45m2, LB 90m2. Harga Rp 2,1 Miliar ------------------------------------------------------------ Dijual Ruko Gwalk 2 Lantai Baru Renov Siap Pakai, Lokasi Sangat Strategis LT : 45 m² Dimensi : 4,5x10 ...",
    "facilities": [
      "토지 45m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-citraland-cp-1013616019",
    "lat": -7.309354,
    "lng": 112.656548
  },
  {
    "id": "live-1013384404",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Sukolilo LT 225m2, LB 997m2 untuk Investasi",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25 Miliar",
    "priceNum": 25000000000,
    "established": null,
    "area": 997.0,
    "floors": 6,
    "description": "Ruko dijual di Sukolilo, Surabaya! Memiliki LT 225m2, LB 997m2. Harga: Rp 25 Miliar. Potensi investasi Ruko ini sangat besar. Lokasinya strategis. ------------------------------------------------------------ Ruko Raya MERR Lokasi Strategis, Cocok Usaha Atau Kantor Atau Tempat Kursus LT : 225 m2 D...",
    "facilities": [
      "토지 225m²",
      "6층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-25miliar-sukolilo-cp-1013384404",
    "lat": -7.28813,
    "lng": 112.802902
  },
  {
    "id": "live-5290",
    "type": "ruko",
    "subtype": "jual",
    "title": "Atmost Business Loft",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,5 Miliar",
    "priceNum": 2500000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "<p>Atmost Business Loft, ruko multiguna persembahan developer Sinarmas Land, berlokasi di surabaya pusat, menjadikan Atmost BisLoft menjadi pilihan tempat untuk memulai mimpi usaha Anda. Dengan keunggulan akses terpisah menuju ke lantai 2 dan 3, juga membuat Atmost BisLoft bisa digunakan sendiri,...",
    "facilities": [
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/atmost-business-loft-5290",
    "lat": -7.3007208,
    "lng": 112.7397631
  },
  {
    "id": "live-1012792612",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual Lokasi Stratagis di Rungkut Surabaya Cocok untuk Bisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,29 Miliar",
    "priceNum": 3290000000,
    "established": null,
    "area": 180.0,
    "floors": 3,
    "description": "Unit Ruko komersial dijual di Surabaya. LT 84m2 & LB 180m2 Harga penawaran Rp 3,29 Miliar Target pasar luas karena lokasinya strategis. 10 menit ke Pintu Tol Tambak Sumurwar ------------------------------------------------------------ Hanya 3 M an, Ruko Rungkut, Modern Classic Style Fasade, Selan...",
    "facilities": [
      "토지 84m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-rungkut-cp-1012792612",
    "lat": -7.31434,
    "lng": 112.800232
  },
  {
    "id": "live-1013511398",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Surabaya LT 170m2 & LB 690m2",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 8,5 Miliar",
    "priceNum": 8500000000,
    "established": null,
    "area": 690.0,
    "floors": 3,
    "description": "FOR SALE! Ruko di Surabaya, Jawa Timur. Spesifikasi: LT 170m2, LB 690m2, cocok untuk berbagai jenis bisnis Area tak perlu diragukan lagi karena strategis. 3 menit ke Terminal Joyoboyo, 4 menit ke Stasiun Wonokromo, 14 menit ke Stasiun Surabaya Kota - ----------------------------------------------...",
    "facilities": [
      "토지 170m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-8miliar-manyar-cp-1013511398",
    "lat": -7.28724,
    "lng": 112.739052
  },
  {
    "id": "live-1013567409",
    "type": "ruko",
    "subtype": "jual",
    "title": "Untuk Dijual Ruko di Gubeng Surabaya LT 1290m2 / LB 643m2",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 20 Miliar",
    "priceNum": 20000000000,
    "established": null,
    "area": 643.0,
    "floors": 2,
    "description": "Ruko untuk dijual di Surabaya, Jawa Timur. Memiliki luas tanah 1290m2 dan luas bangunan 643m2. Harga Rp 20 Miliar Dijual cepat! Hubungi kami sekarang juga. ------------------------------------------------------------ Dijual Bangunan Komersil Cocok Bengkel, Car Wash, Cafe atau Kantor Lokasi Strate...",
    "facilities": [
      "토지 1290m²",
      "shm 증서",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-20miliar-gubeng-cp-1013567409",
    "lat": -7.27396,
    "lng": 112.748192
  },
  {
    "id": "live-1013918329",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Surabaya LT 180m2 & LB 180m2 Lokasi Terbaik!",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4 Miliar",
    "priceNum": 4000000000,
    "established": null,
    "area": 180.0,
    "floors": 2,
    "description": "Dijual Ruko di Mayjen Sungkono, Surabaya, Jawa Timur. Unit Ruko ini memiliki LT 180m2, LB 180m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 4 Miliar ------------------------------------------------------------ Ruko Dijual Mayjend Sungkono Surabaya Barat, 3 Ruko Connecting Jadi 1, L...",
    "facilities": [
      "토지 180m²",
      "2층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-mayjen-sungkono-cp-1013918329",
    "lat": -8.07589,
    "lng": 112.634583
  },
  {
    "id": "live-1013523749",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 151m2 Lokasi Strategis Surabaya Area Cocok untuk Berbisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,2 Miliar",
    "priceNum": 4200000000,
    "established": null,
    "area": 151.0,
    "floors": 3,
    "description": "Tersedia Ruko di Dharma Husada, Surabaya, Jawa Timur. Unit Ruko ini memiliki LT 77m2, LB 151m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 4,2 Miliar ------------------------------------------------------------ Dijual Ruko 3 Lantai Lokasi Sangat Strategis Pusat Kota di Dharmahusada...",
    "facilities": [
      "토지 77m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-dharma-husada-cp-1013523749",
    "lat": -7.26661,
    "lng": 112.768181
  },
  {
    "id": "live-1013721621",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Kawasan Mulyorejo, Surabaya Harga Kompetitif",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,4 Miliar",
    "priceNum": 1400000000,
    "established": null,
    "area": 150.0,
    "floors": 3,
    "description": "Ruko dijual di Mulyorejo, Surabaya, Jawa Timur. Spesifikasi Ruko: Luas tanah 64m2, luas bangunan 150m2 Harga Rp 1,4 Miliar. Lokasi Ruko strategis. ------------------------------------------------------------ Dijual Ruko Kalijudan 3 Lantai Siap Pakai Cocok Untuk Apotek, Salon, Koperasi dll, Lokasi...",
    "facilities": [
      "토지 64m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-mulyorejo-cp-1013721621",
    "lat": -7.27049,
    "lng": 112.780548
  },
  {
    "id": "live-1013396476",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Favorit Dijual di Genteng Surabaya Kawasan Pusat Bisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 10 Miliar",
    "priceNum": 10000000000,
    "established": null,
    "area": 760.0,
    "floors": 3,
    "description": "Ruko komersial di Genteng, Surabaya untuk dijual. Cocok untuk berbisnis. LT 279m2, LB 760m2, dan juga dilengkapi 0 KM. Lokasi emas. 6 menit ke Stasiun Surabaya Kota, 11 menit ke Terminal Joyoboyo, 12 menit ke Stasiun Wonokromo Harga jual: Rp 10 Miliar ---------------------------------------------...",
    "facilities": [
      "토지 279m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-10miliar-genteng-cp-1013396476",
    "lat": -7.26125,
    "lng": 112.742767
  },
  {
    "id": "live-1013263295",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Prime Area Surabaya Luas 125m2",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1,65 Miliar",
    "priceNum": 1650000000,
    "established": null,
    "area": 125.0,
    "floors": 3,
    "description": "Unit komersial di Surabaya dijual dengan LT 125m2, LB 125m2 Area sangat strategis, cocok untuk investasi Lokasi di area ramai. 10 menit ke Terminal Joyoboyo, 11 menit ke Stasiun Wonokromo Harga Rp 1,65 Miliar ------------------------------------------------------------ Dijual atau disewakan Ruko ...",
    "facilities": [
      "토지 125m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-1miliar-dukuh-kupang-cp-1013263295",
    "lat": -7.28244,
    "lng": 112.710747
  },
  {
    "id": "live-1013683511",
    "type": "ruko",
    "subtype": "jual",
    "title": "Lokasi Strategis! Dijual Ruko Bisnis di Kenjeran, Surabaya Kondisi Baik",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4 Miliar",
    "priceNum": 4000000000,
    "established": null,
    "area": 350.0,
    "floors": 3,
    "description": "Dijual Ruko di Kenjeran, Surabaya Spesifikasi: LT 100m2, LB 350m2 Harga Rp 4 Miliar SHM 14 menit ke Stasiun Surabaya Kota ------------------------------------------------------------ Ruko Fira Raya Kenjeran Cocok Usaha, Gudang, Bank dll, Posisi Depan Sangat Strategis LT : 100 m² Dimensi : 5x20 m ...",
    "facilities": [
      "토지 100m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-kenjeran-cp-1013683511",
    "lat": -7.23563,
    "lng": 112.786163
  },
  {
    "id": "live-1013448442",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Dijual di Dukuh Pakis Surabaya dengan LB 200m2",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,7 Miliar",
    "priceNum": 3700000000,
    "established": null,
    "area": 200.0,
    "floors": 3,
    "description": "Ruko komersial dijual di kawasan Dukuh Pakis, Surabaya. Spesifikasi: Luas tanah 67m2 dan bangunan 200m2. Area strategis! 9 menit ke Terminal Joyoboyo, 9 menit ke Stasiun Wonokromo Harga Rp 3,7 Miliar ------------------------------------------------------------ Jual Ruko 3 Lantai di Villa Bukit Ma...",
    "facilities": [
      "토지 67m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-dukuh-pakis-cp-1013448442",
    "lat": -7.29503,
    "lng": 112.710739
  },
  {
    "id": "live-1012844782",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 59m2 Lokasi Strategis Surabaya Area Cocok untuk Bisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4,5 Miliar",
    "priceNum": 4500000000,
    "established": null,
    "area": 59.0,
    "floors": 3,
    "description": "Ruko dijual di Jemursari, Surabaya. Spesifikasi luas: LT 59m2, LB 59m2 Harga Rp 4,5 Miliar SHM ------------------------------------------------------------ DIJUAL DAN DISEWAKAN RUKO NOL JALAN UTAMA SURABAYA, RAYA AHMAD YANI, Tetangga Bebek Sinjay, Ruko Raya Ahmad Yani Frontage Surabaya (Dikenal R...",
    "facilities": [
      "토지 59m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-4miliar-jemursari-cp-1012844782",
    "lat": -7.32428,
    "lng": 112.74173
  },
  {
    "id": "live-1012759642",
    "type": "ruko",
    "subtype": "jual",
    "title": "Untuk Dijual Ruko di Tegalsari Surabaya LT 400m2 / LB 300m2",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 8,5 Miliar",
    "priceNum": 8500000000,
    "established": null,
    "area": 300.0,
    "floors": 1,
    "description": "Ruko untuk dijual, lokasi Tegalsari Surabaya. Cocok untuk investasi Anda! Spesifikasi: LT 400m2, LB 300m2. Harga Rp 8,5 Miliar Ruko ini banyak diincar karena lokasinya yang amat strategis. 8 menit ke Terminal Joyoboyo, 8 menit ke Stasiun Wonokromo, 9 menit ke Stasiun Surabaya Kota ---------------...",
    "facilities": [
      "토지 400m²",
      "1층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-8miliar-tegalsari-cp-1012759642",
    "lat": -7.27355,
    "lng": 112.737457
  },
  {
    "id": "live-1013061020",
    "type": "ruko",
    "subtype": "jual",
    "title": "Paling Dicari! Ruko Dijual di Tunjungan Harga Kompetitif",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,5 Miliar",
    "priceNum": 2500000000,
    "established": null,
    "area": 229.0,
    "floors": 3,
    "description": "Unit komersial di Surabaya dijual dengan LT 78m2, LB 229m2 Area sangat strategis, cocok untuk bisnis Lokasi di area ramai. 5 menit ke Stasiun Surabaya Kota, 12 menit ke Terminal Joyoboyo, 12 menit ke Pelabuhan Tanjung Perak Harga Rp 2,5 Miliar -----------------------------------------------------...",
    "facilities": [
      "토지 78m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-tunjungan-cp-1013061020",
    "lat": -7.25935,
    "lng": 112.738876
  },
  {
    "id": "live-1013194507",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 176m2 Lokasi Strategis Surabaya Area Cocok untuk Berbisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,8 Miliar",
    "priceNum": 3800000000,
    "established": null,
    "area": 176.0,
    "floors": 3,
    "description": "Ruko dijual di pusat bisnis Surabaya. Memiliki luas bangunan 176m2 dan tanah 76m2. Harga Rp 3,8 Miliar nego Lokasi paling dicari. ------------------------------------------------------------ Ruko Menganti Lidah Kulon, jalanan ramai, padat penduduk, parkiran sangat luas, cocok untuk usaha maupun p...",
    "facilities": [
      "토지 76m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-lidah-kulon-cp-1013194507",
    "lat": -7.304073,
    "lng": 112.6586
  },
  {
    "id": "live-1013311714",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 52m2 Lokasi Strategis Surabaya Area Cocok untuk Bisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5,5 Miliar",
    "priceNum": 5500000000,
    "established": null,
    "area": 52.0,
    "floors": 4,
    "description": "Tersedia Ruko di Gununganyar, Surabaya, Jawa Timur. Unit Ruko ini memiliki LT 52m2, LB 52m2. Cocok untuk berbagai jenis usaha Harga jual mulai dari Rp 5,5 Miliar ------------------------------------------------------------ Ruko Noll Jalan Raya Merr, Baru Gress, Siap Pakai, Parkiran Luas, dekat Ka...",
    "facilities": [
      "토지 52m²",
      "4층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-5miliar-gununganyar-cp-1013311714",
    "lat": -7.33182,
    "lng": 112.80822
  },
  {
    "id": "live-1014179013",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus Dijual LB 225m2 Lokasi Strategis Surabaya Area Cocok untuk Berbisnis",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3,9 Miliar",
    "priceNum": 3900000000,
    "established": null,
    "area": 225.0,
    "floors": 3,
    "description": "DIJUAL CEPAT Disewakan Ruko Raya Menganti, Cocok untuk Usaha, Ruko Siap Pakai Ruko bagus di Menganti Surabaya ini memiliki lokasi yang sangat strategis. Jadi sangat memudahkan akses dan memiliki pasar yang besar. Memiliki LT 195m2, LB 225m2 Harga Rp 3,9 Miliar Jangan sampai kelewatan! -----------...",
    "facilities": [
      "토지 195m²",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-3miliar-menganti-cp-1014179013",
    "lat": -7.294023,
    "lng": 112.587967
  },
  {
    "id": "live-1012872384",
    "type": "ruko",
    "subtype": "jual",
    "title": "Unit Ruko Dijual di Jambangan Surabaya 466m2",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 6 Miliar",
    "priceNum": 6000000000,
    "established": null,
    "area": 466.0,
    "floors": 3,
    "description": "Tersedia Ruko di Jambangan, Surabaya, Jawa Timur. Luas tanah 466m2 dan bangunan 466m2. Harga jual Rp 6 Miliar Lokasi strategis & akses mudah. 9 menit ke Stasiun Wonokromo, 9 menit ke Terminal Joyoboyo, 10 menit ke Terminal Purabaya Bungurasih ------------------------------------------------------...",
    "facilities": [
      "토지 466m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-6miliar-jambangan-cp-1012872384",
    "lat": -7.31747,
    "lng": 112.716637
  },
  {
    "id": "live-1013432796",
    "type": "ruko",
    "subtype": "jual",
    "title": "Ruko Bagus LT 100m2 LB 180m2 Dijual di Rungkut Surabaya",
    "category": "루코",
    "location": "Surabaya",
    "locationKo": "수라바야",
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2,9 Miliar",
    "priceNum": 2900000000,
    "established": null,
    "area": 180.0,
    "floors": 3,
    "description": "Ruko untuk dijual di Surabaya, Jawa Timur. Memiliki luas tanah 100m2 dan luas bangunan 180m2. Harga Rp 2,9 Miliar Dijual cepat! Hubungi kontak tersedia sekarang juga. ------------------------------------------------------------ Ruko di Rungkut Asri, noll jalan raya, jalanan ramai, padat penduduk,...",
    "facilities": [
      "토지 100m²",
      "shm 증서",
      "3층",
      "99.co 실시간"
    ],
    "whatsapp": null,
    "c2c": false,
    "images": "🛰️",
    "badge": "매매",
    "source": "99.co",
    "sourceUrl": "https://www.99.co/id/properti/ruko-dijual-2miliar-rungkut-cp-1013432796",
    "lat": -7.31434,
    "lng": 112.800232
  }
];
