// 자동 생성 파일 — scraper/scrape_olx.py 가 갱신합니다. 직접 수정 금지.
// 갱신 시각: 2026-07-28T22:38:01+07:00
const OLX_LISTINGS_UPDATED_AT = "2026-07-28T22:38:01+07:00";
const OLX_LISTINGS = [
  {
    "id": "olx-945376128",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "DIJUAL Murah RUKO MURAH, BEBAS BANJIR, STRATEGIS + USAHA BERJALAN di Lippo Karawaci, Tangerang",
    "category": "카페 & 레스토랑",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 4.500.000.000",
    "priceNum": 4500000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "TURUN HARGA.DIJUAL RUKO dengan lokasi strategis di Lippo karawaci, cocok untuk investasi properti dan usaha dengan HARGA TERBAIK. TURUN HARGA.DIJUAL RUKO beserta dengan usaha LAUNDRY + KOST VIP yang sudah berjalan dengan pelanggan tetap. Potensi pendapatan stabil dengan keuntungan besar yang mengunt...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/dijual-murah-ruko-murah-bebas-banjir-strategis-usaha-berjalan-di-lippo-karawaci--iid-945376128",
    "postedAt": "2026-07-28T21:39:27+07:00",
    "lat": -6.245,
    "lng": 106.616
  },
  {
    "id": "olx-943945674",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "JUAL RUKO BESERTA USAHA!! Ruko Mega Boulevard di Harapan Indah 007",
    "category": "기타 사업",
    "location": "Bekasi Kota",
    "locationKo": "브카시",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 7.900.000.000",
    "priceNum": 7900000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Ukuran 7.5 x 33 x 3.5lt. Pln 23,000 watt SUDAH ADA 2 USAHA BERJALAN! - Kos-kosan - Tiki Pemasukan kotor: Kos2an = 23jt/bln Sewa lt 1 = 60jt/thn atau 5jt/bln Tiki = 20%×20jt/bln = 4jt Total = 32jt/ bulan Biaya2: Listrik, air = 6jt Gaji 2 org = 4jt Total = 10-11jt Pendptan bersih = 23jt/ bln Harga Jua...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/jual-ruko-beserta-usaha-ruko-mega-boulevard-di-harapan-indah-007-iid-943945674",
    "postedAt": "2026-07-28T18:36:29+07:00",
    "lat": -6.192,
    "lng": 106.975
  },
  {
    "id": "olx-946956870",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha laundry cipondoh",
    "category": "세탁",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Bismillah, TAKE OVER CEPAT USAHA LAUNDRY Belakang Green Lake cipondoh tangerang. dilepas karena costumer menurun kareena sering gonta ganti pegawai, pemilik tidak terjun langsung. bagi yang punya pengalaman laundry dan menambah cabang bisa jd pertimbangan : * lokasi strategis * ruko besar (3 sekat) ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-cipondoh-iid-946956870",
    "postedAt": "2026-07-28T15:10:19+07:00",
    "lat": -6.186,
    "lng": 106.682
  },
  {
    "id": "olx-946956996",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over laundry",
    "category": "세탁",
    "location": "Jakarta Barat",
    "locationKo": "자카르타 서부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Bismillah, TAKE OVER CEPAT USAHA LAUNDRY Belakang Green Lake cipondoh tangerang. dilepas karena costumer menurun kareena sering gonta ganti pegawai, pemilik tidak terjun langsung. bagi yang punya pengalaman laundry dan menambah cabang bisa jd pertimbangan : * lokasi strategis * ruko besar (3 sekat) ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-iid-946956996",
    "postedAt": "2026-07-28T15:09:19+07:00",
    "lat": -6.134,
    "lng": 106.705
  },
  {
    "id": "olx-947005642",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over Laundry kiloan bukit duri",
    "category": "세탁",
    "location": "Jakarta Selatan",
    "locationKo": "자카르타 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 70.000.000",
    "priceNum": 70000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over Laundry kiloan dan koin bukit duri. Akses jalan ramai..udah banyak pelanggan Omset sebulan 13 JT .. Sewa kios bulanan /tahunan Mesin washer LG 8 kg Dryer diamante konversi gas 10.5 Mesin washer koin Beko 11 kg Dryer koin Beko Boiler 17 liter Mesja setrika +setrikaan uap Keranjang +gantunga...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-kiloan-bukit-duri-iid-947005642",
    "postedAt": "2026-07-28T12:48:28+07:00",
    "lat": -6.231,
    "lng": 106.847
  },
  {
    "id": "olx-946785298",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Cafe Aktif",
    "category": "카페 & 레스토랑",
    "location": "Tangerang Selatan Kota",
    "locationKo": "탕그랑 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 75.000.000",
    "priceNum": 75000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Bismillah..Assalamualaikum wr wb Dioper alih usaha Tropical European vibes Cafe,Karena ownernya pindah kerja ke China,Free Kontrak Bangunan 5 Bulan Benefit: - Rating Google bintang 5 - Pinggir jalan besar persis dan ramai - Banyak ruko,kantor,sekolah dan perumahan - Keamanan 24H dan Bersih - Supply ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-cafe-aktif-iid-946785298",
    "postedAt": "2026-07-28T10:54:16+07:00",
    "lat": -6.308,
    "lng": 106.682
  },
  {
    "id": "olx-947050186",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER USAHA GAS 3KG",
    "category": "기타 사업",
    "location": "Depok Kota",
    "locationKo": "데포",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 65.000.000",
    "priceNum": 65000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take Over Usaha gas 3kg Khusus Daerah Depok, Beji kukusan, Depok Dua, Kelapa dua, Bisa balik nama langsung atas nama yang take Over, # Pengiriman dalam sebulan 1900 tabung # Kontrak agen ke pangkalan 1500 # Seminggu dua kali pengiriman (250 tabung) # Harga penebusan 16.000/tabung # Tabung Kosongan 2...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-gas-3kg-iid-947050186",
    "postedAt": "2026-07-27T21:25:53+07:00",
    "lat": -6.375,
    "lng": 106.823
  },
  {
    "id": "olx-947038491",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha laundry koin",
    "category": "세탁",
    "location": "Jakarta Selatan",
    "locationKo": "자카르타 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 95.000.000",
    "priceNum": 95000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Usaha laundry self-service. Semua isi di dalam toko 3 dryer(LG), 3 washer (Foggia) 15kg 1 setrika uap nagamoto semi auto. Karyawati 2 orang. Dan perlengkapan lainnya. Lokasi di jln manunggal2, Petukangan selatan, pesanggrahan jaksel Harga di luar biaya kontrakan (20jt/thn)",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-koin-iid-947038491",
    "postedAt": "2026-07-27T20:28:24+07:00",
    "lat": -6.247,
    "lng": 106.761
  },
  {
    "id": "olx-947048136",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha bisnis klinik salon kecantikan spa",
    "category": "뷰티 & 살롱",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 100.000.000",
    "priceNum": 100000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Saatnya yang ingin memiliki usaha tanpa dari enol Over rugi salon kecantikan Lokasi di ruko crystal 2 (dekat sekolah pahoa) prospek ibu ibu sangat tinggi. Alat alat kecantikan lengkap dan terjamin karena dibeli dari Jamberdetak derma tech yang terdiri dari Hifu,Oxygeneo,laser,ipl dan ada oxygen hydr...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-bisnis-klinik-salon-kecantikan-spa-iid-947048136",
    "postedAt": "2026-07-27T19:42:18+07:00",
    "lat": -6.243,
    "lng": 106.619
  },
  {
    "id": "olx-947042916",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Salon di Serang",
    "category": "뷰티 & 살롱",
    "location": "Serang Kota",
    "locationKo": "Serang Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 600.000.000",
    "priceNum": 600000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "harga 600 jt ( inc alat , sistem, karyawan )",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-salon-di-serang-iid-947042916",
    "postedAt": "2026-07-27T15:36:24+07:00",
    "lat": -6.125,
    "lng": 106.14
  },
  {
    "id": "olx-946942016",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER USAHA LAUNDRY",
    "category": "세탁",
    "location": "Jakarta Timur",
    "locationKo": "자카르타 동부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 99.900.000",
    "priceNum": 99900000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Kini hadir Paket Usaha Laundry Istimewa di Jakarta Timur yang sudah terbukti menghasilkan $Omset Rp 15 Juta++/bulan. ​ Apa aja keuntungannya? ​Bebas Pikir Biaya Sewa: Sewa kios sudah AMAN & LUNAS sampai 1 Januari 2027! ​Anti Gabut / Anti Bingung: Dipandu cara kelolanya selama 30 hari penuh. ​Peralat...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-iid-946942016",
    "postedAt": "2026-07-27T11:41:58+07:00",
    "lat": -6.326,
    "lng": 106.856
  },
  {
    "id": "olx-940266640",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Frandchise",
    "category": "기타 사업",
    "location": "Tangerang Selatan Kota",
    "locationKo": "탕그랑 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Mau over frandchise kemitraan 1.Istanbul Kebab : 50jt, mau di over 25jt 2.Pide Turkish Pizza : 50jt, mau di over 25jt 3.Ambil keduanya jadi 40jt saja Lokasi Jl.Cabe 4, (Deket Indomaret 2) Pondok Cabe ilir, Tangsel Pantau > Cocok > bayar",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-frandchise-iid-940266640",
    "postedAt": "2026-07-27T01:01:49+07:00",
    "lat": -6.347,
    "lng": 106.741
  },
  {
    "id": "olx-944651438",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over Laundry",
    "category": "뷰티 & 살롱",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 475.000.000",
    "priceNum": 475000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Kalau Berjodoh Cocok Benefitnya: - 4 Washer Samsung WF 16kg - 4 Dryer LG Giant Max - AC Changkong 2PK - 4 CCTV Ezviz - Modem Orbit - Free Asuransi Kebakaran - Mesin Perawatan Rutin - OPPO Reno 11F - Printer Blue Print Kabel - Printer Blue Print Portabel - Timbangan Duduk Benz 150k - 7tb Gas pink 12K...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-iid-944651438",
    "postedAt": "2026-07-26T18:02:09+07:00",
    "lat": -6.186,
    "lng": 106.682
  },
  {
    "id": "olx-944058514",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Turun Harga!! TAKE OVER SALON SIAP JALAN",
    "category": "뷰티 & 살롱",
    "location": "Cirebon Kota",
    "locationKo": "Cirebon Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 99.000.000",
    "priceNum": 99000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Kesempatan langka untuk langsung punya bisnis salon tanpa mulai dari nol. ALL IN - Lokasi strategis (Citraland, Cirebon) - Ruko 2 lantai (sisa sewa masih ada s/d Oktober 2026) - Ruang Facial, ruang Spa, Ruang Salon - AC setiap ruangan - Peralatan salon lengkap (siap pakai) - alat Nail art lengkap - ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/turun-harga-take-over-salon-siap-jalan-iid-944058514",
    "postedAt": "2026-07-26T15:49:23+07:00",
    "lat": -6.731,
    "lng": 108.551
  },
  {
    "id": "olx-946840940",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over Salon",
    "category": "뷰티 & 살롱",
    "location": "Jakarta Barat",
    "locationKo": "자카르타 서부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 21.000.000",
    "priceNum": 21000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Takeover salon isi & alat2 salon",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-salon-iid-946840940",
    "postedAt": "2026-07-26T05:50:42+07:00",
    "lat": -6.148,
    "lng": 106.735
  },
  {
    "id": "olx-947007609",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over/ hand over LAUNDRY JAKARTA BARAT MURAH",
    "category": "세탁",
    "location": "Jakarta Barat",
    "locationKo": "자카르타 서부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 65.000.000",
    "priceNum": 65000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Omset -+ 15 juta perbulan Lokasi: Anggrek Rosliana, Kemanggisan, Palmerah. Jakarta Barat info bisa chat ke no tertera!!",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-hand-over-laundry-jakarta-barat-murah-iid-947007609",
    "postedAt": "2026-07-25T22:33:06+07:00",
    "lat": -6.19,
    "lng": 106.797
  },
  {
    "id": "olx-946995741",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Dijual Usaha Percetakan Masih Berjalan Berikut Kelengkapan dan Client",
    "category": "기타 사업",
    "location": "Jakarta Timur",
    "locationKo": "자카르타 동부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000.000",
    "priceNum": 25000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual lepas/take over Usaha Percetakan di Jakarta Timur masih berjalan dengan baik dan berikut tempat usaha, peralatan, pelanggan tinggal melanjutkan. Manajemen baik dan berjalan lancar, workshop maaih beroperasi lancar pelanggan masih setia memakai jasanya. Alasan dijual pemilik mau pensiun karena...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/dijual-usaha-percetakan-masih-berjalan-berikut-kelengkapan-dan-client-iid-946995741",
    "postedAt": "2026-07-25T12:57:01+07:00",
    "lat": -6.355,
    "lng": 106.873
  },
  {
    "id": "olx-943426071",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha gaplek pakan ternak",
    "category": "제조",
    "location": "Sukabumi Kab.",
    "locationKo": "Sukabumi Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1.000.000.000",
    "priceNum": 1000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take Over Usaha Skala Umkm Masih Berjalan. Produksi Gaplek Untuk Pakan Ternak. Harga Rp 1 Milyar (Nego). Pendapatan Usaha Bisa Ditingkatkan Lagi. Rincian aset : - 1 Unit pabrik LT 300m² LB 150m² AJB. - 1 Unit mobil Foton Engkel 2011. - 1 Unit mobil Toyota Rush 2020 matic Lokasi pabrik pinggir jln Ra...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-gaplek-pakan-ternak-iid-943426071",
    "postedAt": "2026-07-25T09:55:49+07:00",
    "lat": -6.968,
    "lng": 106.806
  },
  {
    "id": "olx-946960572",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Sekaligus Sisa Sewa Warteg Super Strategi di Perempatan Lampu Merah Plaza Jambu Dua Bogor",
    "category": "카페 & 레스토랑",
    "location": "Bogor Kota",
    "locationKo": "보고르",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 45.000.000",
    "priceNum": 45000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "TAKE OVER WARTEG BISNIS SUDAH JALAN * Investasi Hanya Rp150.000.000 / Lokasi * Sudah termasuk sewa tempat sampai September 2027 * Usaha sudah berjalan ±3 tahun * Tinggal lanjut operasional dan kembangkan bisnis Ingin memiliki usaha kuliner tanpa harus memulai dari NOL? Saat ini banyak franchise wart...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-sekaligus-sisa-sewa-warteg-super-strategi-di-perempatan-lampu-me-iid-946960572",
    "postedAt": "2026-07-25T08:59:17+07:00",
    "lat": -6.569,
    "lng": 106.808
  },
  {
    "id": "olx-946959012",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha laundry tinggal jalanin",
    "category": "세탁",
    "location": "Bogor Kab.",
    "locationKo": "Bogor Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 250.000.000",
    "priceNum": 250000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over laundry tinggal jalan Ruko 2 lt dan isi nya minat langsung DM saja untuk nego\"",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-tinggal-jalanin-iid-946959012",
    "postedAt": "2026-07-24T17:14:08+07:00",
    "lat": -6.738,
    "lng": 106.876
  },
  {
    "id": "olx-946523445",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER LAUNDRY ALL IN",
    "category": "세탁",
    "location": "Jakarta Timur",
    "locationKo": "자카르타 동부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 20.000.000",
    "priceNum": 20000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "YANG ANDA DAPATKAN CUKUP DENGAN 20JUTA Mesin 1. Dryer Azalea 10,5 kg (6 bulan pemakaian) = Rp4.500.000 2. Mesin cuci LG 6 kg (OLD) = Rp2.000.000 3. Mesin cuci LG 8,5 kg (3 bulan pemakaian) = Rp5.500.000 4. Mesin boiler = Rp2.000.000 5. Setrika uap = Rp300.000 6. 2 tabung gas = Rp50.000 7. Mesin pres...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-all-in-iid-946523445",
    "postedAt": "2026-07-23T11:06:24+07:00",
    "lat": -6.23,
    "lng": 106.882
  },
  {
    "id": "olx-946937488",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over / Jual Borongan Peralatan Salon Lengkap  Siap Langsung Usaha",
    "category": "뷰티 & 살롱",
    "location": "Samarinda Kota",
    "locationKo": "Samarinda Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 20.000.000",
    "priceNum": 20000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "JUAL BORONGAN PERALATAN SALON & BEAUTY STUDIO LENGKAP – SIAP LANGSUNG USAHA Dijual 1 paket lengkap isi salon dalam kondisi masih bagus dan siap pakai. Cocok untuk salon rambut, beauty studio, eyelash, facial, spa, maupun klinik kecantikan. Isi Paket: • 4 Kursi salon hidrolik • 2 Kursi keramas (shamp...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-jual-borongan-peralatan-salon-lengkap-siap-langsung-usaha-iid-946937488",
    "postedAt": "2026-07-23T06:30:02+07:00",
    "lat": -0.52,
    "lng": 117.129
  },
  {
    "id": "olx-946915049",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "GEDUNG +LAUNDRY OPERASIONAL JALAN UTAMA  3,5M  TAKE OVER LANGSUNG CUAN",
    "category": "세탁",
    "location": "Denpasar Kota",
    "locationKo": "Denpasar Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 3.500.000.000",
    "priceNum": 3500000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "01 DIJUAL – GEDUNG + USAHA LAUNDRY (READY OPERASIONAL) lokasi gn Soputan Denpasar barat strategis dan Siap langsung digunakan untuk operasional, Cocok untuk yang ingin langsung menjalankan bisnis laundry tanpa perlu investasi peralatan dari awal, atau sebagai aset investasi komersial lainnya di loka...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/gedung-laundry-operasional-jalan-utama-3-5m-take-over-langsung-cuan-iid-946915049",
    "postedAt": "2026-07-22T21:30:00+07:00",
    "lat": -8.698,
    "lng": 115.248
  },
  {
    "id": "olx-945430273",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Franchise, Take Over Usaha",
    "category": "기타 사업",
    "location": "Depok Kota",
    "locationKo": "데포",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 12.000.000",
    "priceNum": 12000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over usaha minuman Lokasi di Depok Minat hub: Kosong delapan tujuh 887 enam lima kosong 897",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-franchise-take-over-usaha-iid-945430273",
    "postedAt": "2026-07-22T17:40:14+07:00",
    "lat": -6.436,
    "lng": 106.835
  },
  {
    "id": "olx-946916437",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha Laundry koin",
    "category": "세탁",
    "location": "Jakarta Barat",
    "locationKo": "자카르타 서부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 95.000.000",
    "priceNum": 95000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over usaha laundry koin - 5 mesin cuci merk beko 11 kg - 7 mesin pengering merk beko - 6 tabung gas 12 kg pink -1500 liter Toren -air pakai satelit bersih -filter air - stabilizer 5000 -listrik 3200 watt - hexos - CCTV - karyawan 2 -sewa sampai Desember 2026 Take over laundry koin, tinggal lanj...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-koin-iid-946916437",
    "postedAt": "2026-07-22T10:23:12+07:00",
    "lat": -6.134,
    "lng": 106.705
  },
  {
    "id": "olx-946904249",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha",
    "category": "카페 & 레스토랑",
    "location": "Jakarta Selatan",
    "locationKo": "자카르타 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 45.000.000",
    "priceNum": 45000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take Over Usaha Warung Pudding Kesempatan memiliki usaha tanpa harus dari 0 karena sudah dikenal di wilayah Jagakarsa dan sudah pernah diliput oleh stasiun TV swasta. Sudah termasuk: • Seluruh akun socmed • Resep asli pudding • Dekorasi toko • Meja kasir • Meja dan kursi • Chiller Midea • Freezer Mi...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-iid-946904249",
    "postedAt": "2026-07-21T17:16:53+07:00",
    "lat": -6.334,
    "lng": 106.823
  },
  {
    "id": "olx-946449660",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over laundry daerah Depok !!!",
    "category": "세탁",
    "location": "Depok Kota",
    "locationKo": "데포",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over cepat laundry wilayah Depok Laundry sudah jalan 6 tahun Take over karena pemilik sudah mulai sibuk Berikut mesin-mesinnya dan kelengkapannya : 1) Mesin cuci LG 12 KG 2) Mesin Pengering Diamante 3) Mesin Pengering Azalea 4) Setrika uap 5) Setrika Listrik 6) Pompa pendorong 7) Tandon air 8) ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-daerah-depok-iid-946449660",
    "postedAt": "2026-07-21T13:24:42+07:00",
    "lat": -6.364,
    "lng": 106.859
  },
  {
    "id": "olx-946893734",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER LAUNDRY / OVER KONTRAK RUKO 2 LANTAI DAERAH CIBALIGO CIMINDI",
    "category": "세탁",
    "location": "Cimahi Kota",
    "locationKo": "Cimahi Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 11.500.000",
    "priceNum": 11500000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "OVER KONTRAK RUKO 2 LANTAI daerah jalan cibaligo dekat fly over cimindi cibeureum cimahi selatan Over kontrak usaha laundry dengan semua perlengkapannya, Keunggulan lokasi berada di pinggir jalan yang ramai dilalui masyarakat setiap hari. dekat sekolah, masjid dan pusat aktivitas warga. Lingkungan p...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-over-kontrak-ruko-2-lantai-daerah-cibaligo-cimindi-iid-946893734",
    "postedAt": "2026-07-21T12:20:28+07:00",
    "lat": -6.905,
    "lng": 107.532
  },
  {
    "id": "olx-946721093",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over londri sdh berjalan 7 tahun",
    "category": "세탁",
    "location": "Jakarta Timur",
    "locationKo": "자카르타 동부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Di take over londri beserta semua peralatannya dan semua pelanggan tetapnya Londri sudah berjalan 7 tahun,dekat dengan pemukiman warga dan Kluster Yang di dapat : Mesin cuci tabung depan 2 Uk.8kg Pengering 2 Uk. 9,5kg Timbangan 1 Print nota 1 Kipas angin 1 Setrika uap Tabung gas 5 Keranjang baju 10 ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-londri-sdh-berjalan-7-tahun-iid-946721093",
    "postedAt": "2026-07-20T21:39:41+07:00",
    "lat": -6.327,
    "lng": 106.9
  },
  {
    "id": "olx-946874423",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Jual Tempat Usaha Berjalan Raya Pasar Minggu",
    "category": "기타 사업",
    "location": "Jakarta Selatan",
    "locationKo": "자카르타 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 26.000.000.000",
    "priceNum": 26000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "lantai 1 area bengkel indomaret food court parkir luas shm on hand jalan depan 2 mobil",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/jual-tempat-usaha-berjalan-raya-pasar-minggu-iid-946874423",
    "postedAt": "2026-07-20T17:13:01+07:00",
    "lat": -6.289,
    "lng": 106.839
  },
  {
    "id": "olx-767013947",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Paketan Laundry Pemula / Take over laundry",
    "category": "뷰티 & 살롱",
    "location": "Jakarta Barat",
    "locationKo": "자카르타 서부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Paket usaha laundry kiloan Mesin dan semua perlengkapan second 95% Kami bukan hanya jual tp after sales langsung kami tangani sendiri didukung Dengan teknisi ahli dibidangnya Free ongkir JaBoDeTaBek paket 25 jt 1 unit mesin cuci top loading 8 kg 1 unit mesin cuci top loading 9 kg 1 mesin pengering g...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/paketan-laundry-pemula-take-over-laundry-iid-767013947",
    "postedAt": "2026-07-19T10:26:07+07:00",
    "lat": -6.148,
    "lng": 106.735
  },
  {
    "id": "olx-946798620",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Toko Strategis MGK - Dapat stok, Siap Pakai & Omzet Stabil",
    "category": "소매점",
    "location": "Jakarta Pusat",
    "locationKo": "자카르타 중부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 16.500.000",
    "priceNum": 16500000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijamin amanah. Take over usaha toko di MGK, posisi sangat strategis tepat di depan ATM BCA dan pas di depan eskalator dengan traffic pengunjung yang tinggi. Usaha sudah jalan, stabil dengan omzet +-15juta/bulan, jika ramai bisa dapat lebih dan siap lanjut operasional. Alasan take over karena pindah...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-toko-strategis-mgk-dapat-stok-siap-pakai-omzet-stabil-iid-946798620",
    "postedAt": "2026-07-17T01:27:24+07:00",
    "lat": -6.16,
    "lng": 106.847
  },
  {
    "id": "olx-945839491",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Oper usaha sembako dan Cilok dan Bakso",
    "category": "기타 사업",
    "location": "Bekasi Kota",
    "locationKo": "브카시",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 20.000.000",
    "priceNum": 20000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Di oper usaha sembako, Cilok dan Bakso sudah berjalan lebih dari 7 tahun,dan pendapatan Cilok, Bakso sudah rutin,juga sembako, apabila sembako lebih dilengkapi itemnya akan banyak menambah penghasilan. Alasan dioper karena mau pindah ketempat yang satunya.dg total harga oper keseluruhan dan ditambah...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/oper-usaha-sembako-dan-cilok-dan-bakso-iid-945839491",
    "postedAt": "2026-07-16T22:03:02+07:00",
    "lat": -6.27,
    "lng": 106.929
  },
  {
    "id": "olx-943537276",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER USAHA LAUNDRY",
    "category": "세탁",
    "location": "Palembang Kota",
    "locationKo": "Palembang Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 50.000.000",
    "priceNum": 50000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over usaha laundry Pelanggan sudah ada dan lokasi strategis dekat jalan besar Take over karena mau pindah luar kota, kondisi barang mulus belum setahun Sudah termasuk - sewa tempat - mesin cuci front loading LG dan pengering Diamente - mesin cuci top loading LG - set meja dan lemari laundry - s...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-iid-943537276",
    "postedAt": "2026-07-15T10:06:33+07:00",
    "lat": -2.948,
    "lng": 104.693
  },
  {
    "id": "olx-944595042",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Ruko Gandeng Tigaraksa + Take Over kepemilikkan dengan Usaha  Les Anak",
    "category": "교육",
    "location": "Tangerang Kab.",
    "locationKo": "Tangerang Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2.400.000.000",
    "priceNum": 2400000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Berapa 2 ruko gandeng Spec /unit Luas tanah : 65m2 dan 78m2 Dimensi tanah : 5x15 dan 5x17.5 Luas bangunan : 5x20 dan 5x20 Lantai : 2 Air : pam PLN: token 2200watt masing2 Hadap : barat Surat : HGB Harga jual : 2.4M Nego ? Ya Kondisi skrg : masih dipakai untuk les lesan. Dan bisnis siap jalan Jual be...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/ruko-gandeng-tigaraksa-take-over-kepemilikkan-dengan-usaha-les-anak-iid-944595042",
    "postedAt": "2026-07-14T20:51:12+07:00",
    "lat": -6.263,
    "lng": 106.466
  },
  {
    "id": "olx-946731878",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "take over murah usaha toko plastik dan bahan kue",
    "category": "소매점",
    "location": "Bandung Kab.",
    "locationKo": "Bandung Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 13.000.000",
    "priceNum": 13000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "take over toko plastik dan bahan kue (karna saya mau pindah kota) lokasi strategis pinggir jalan, dekat dengan banyak perumahan, di sekitar toko banyak pedagang. sewa toko 500ribu/bulan.. total stok barang harga modal 13jutaan..sudah ada etalase, rak² dan lemari.. serius minat wa saja masih bisa neg...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-murah-usaha-toko-plastik-dan-bahan-kue-iid-946731878",
    "postedAt": "2026-07-14T12:23:43+07:00",
    "lat": -6.982,
    "lng": 107.662
  },
  {
    "id": "olx-946731630",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Jual ruko dan usaha berjalan RM Padang",
    "category": "제조",
    "location": "Bekasi Kab.",
    "locationKo": "Bekasi Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1.000.000.000",
    "priceNum": 1000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Jual ruko dan usaha berjalan rumah makan padang Ukuran ruko 4x11,5 Luas tanah 46 m² Luas bangunan 54 m² Bagian belakang sudah direnovasi jadi kitchen 1,5 lantai Lantai 2nya berupa mezanine dengan 2 kamar difungsikan sebagai mes karyawan. Hadap Selatan Lokasi ruko sangat strategis berada tepat di dep...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/jual-ruko-dan-usaha-berjalan-rm-padang-iid-946731630",
    "postedAt": "2026-07-14T10:38:03+07:00",
    "lat": -6.363,
    "lng": 107.042
  },
  {
    "id": "olx-946408613",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER BRAND LAUNDRY DEPOK | OMZET 50 JT/BULAN | AUTOPILOT",
    "category": "세탁",
    "location": "Bogor Kab.",
    "locationKo": "Bogor Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 595.000.000",
    "priceNum": 595000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "TAKE OVER BRAND KLEAN LOKA LAUNDRY Bukan sekadar membeli mesin laundry. Anda membeli: - BRAND yang sudah dikenal pasar - Passive Income Business - Sistem bisnis yang sudah berjalan - Customer aktif lebih dari 1.500 - Bisnis yang dapat dijalankan secara autopilot - Digital asset lengkap KENAPA KLEAN ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-brand-laundry-depok-omzet-50-jt-bulan-autopilot-iid-946408613",
    "postedAt": "2026-07-14T06:08:40+07:00",
    "lat": -6.49,
    "lng": 106.83
  },
  {
    "id": "olx-946006220",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over laundry omset 23-30juta siap temani owner baru 2 minggu",
    "category": "세탁",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 130.000.000",
    "priceNum": 130000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Jual laundry masih aktif, sudah auto pilot, karyawan sudah ada cctv sudah lengkap motor listrik volta 2 baterai Omset bagus 23-30 jt siap dampingi 1-2minggu , siap kasih racikan sabun dan parfum agar lebih kecil kos biaya penggeluran nya, langsung datang untuk lebih jelasnya",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-omset-23-30juta-siap-temani-owner-baru-2-minggu-iid-946006220",
    "postedAt": "2026-07-13T16:12:15+07:00",
    "lat": -6.186,
    "lng": 106.682
  },
  {
    "id": "olx-932881436",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Jual Kios Ruang Usaha di Sky House Alam Sutera take over bisa",
    "category": "카페 & 레스토랑",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1.500.000.000",
    "priceNum": 1500000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual Cash / Takeover Unit Kios Tempat Usaha Shophouse Skyhouse Alam Sutera, Tangerang Selatan. Lokasi Ok Strategis seberang Mal Aeo Alam Sutera, dekat IKEAm, dekat Tol Alam Sutera dll. Luas Tanah = 53 M2 Luas bangunan = 50 M2 - Unit saat ini digunakan untuk coffee shop. - Unit sudah di renovasi fu...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/jual-kios-ruang-usaha-di-sky-house-alam-sutera-take-over-bisa-iid-932881436",
    "postedAt": "2026-07-13T13:33:48+07:00",
    "lat": -6.22,
    "lng": 106.661
  },
  {
    "id": "olx-939197639",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over usaha laundry",
    "category": "세탁",
    "location": "Tangerang Kab.",
    "locationKo": "Tangerang Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 175.000.000",
    "priceNum": 175000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "TAKE OVER USAHA LAUNDRY 1. Terdapat 2 set mesin kecil dengan kapasitas 10,5kg (cuci & dryer). Sudah konvert gas. Dan memakai sistem qris. 2. Terdapat 2 set mesin besar dengan kapasitas 20kg. Sudah konvert gas. Sudah memakai sistem qris. 3. Toran 1100L 4. Tabung gas 3kg @4bh 5. 1 meja gosok uap 6. 1 ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-laundry-iid-939197639",
    "postedAt": "2026-07-13T10:45:22+07:00",
    "lat": -6.257,
    "lng": 106.523
  },
  {
    "id": "olx-942855349",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Sabana Fried Chicken Duren sawit di jual atau take over",
    "category": "기타 사업",
    "location": "Jakarta Timur",
    "locationKo": "자카르타 동부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 22.000.000",
    "priceNum": 22000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Di jual atau take over kemitraan. Sabana Fried Chicken di Jl Raden inten Raya. Komplek Kimia Farma. Lokasi strategis pinggir jalan . Sebelah Indomaret. Usaha sudah berjalan dari 2011. Sampai sekarang masih berjualan. Perlengkapan siap jualan. Tinggal beli bahan baku saja. Beli dari sabana pusat. Ala...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/sabana-fried-chicken-duren-sawit-di-jual-atau-take-over-iid-942855349",
    "postedAt": "2026-07-12T09:45:48+07:00",
    "lat": -6.232,
    "lng": 106.915
  },
  {
    "id": "olx-946564635",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Disewakan Space / take over usaha",
    "category": "카페 & 레스토랑",
    "location": "Bandung Kota",
    "locationKo": "반둥",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 100.000.000",
    "priceNum": 100000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over cafe sudah berjalan 1 tahun lebih Masih tersisa 3 tahun lebih Disewakan space Luas tanah Luas bngunan 250 Listrik brp watt 4400+1500 Air shareing Peruntukan office atau public area Bs renovasi ga ( bs)",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/disewakan-space-take-over-usaha-iid-946564635",
    "postedAt": "2026-07-12T00:48:51+07:00",
    "lat": -6.891,
    "lng": 107.615
  },
  {
    "id": "olx-904264579",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over Perlengkapan franchise makanan korea",
    "category": "기타 사업",
    "location": "Jakarta Barat",
    "locationKo": "자카르타 서부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 10.000.000",
    "priceNum": 10000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual franchise makanan Korea beserta perlengkapannya : 1. Gerobak 2. Freezer 200ltr 3. Showcase pemanas makanan 4. Mesin kasir & printer ya 5. Gas pink 5ltr = 2pcs 6. Gas hijau 3kg = 4pcs 7. Kompor gas 2 tungku = 2 pcs (merk cosmos & rinai) 8. Perlengkapan masak & saji (yg topoki = 6 foodpan besar...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-perlengkapan-franchise-makanan-korea-iid-904264579",
    "postedAt": "2026-07-11T17:41:55+07:00",
    "lat": -6.162,
    "lng": 106.788
  },
  {
    "id": "olx-946675781",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER CAFE / BEVERAGE OUTLET SIAP PAKAI",
    "category": "카페 & 레스토랑",
    "location": "Surabaya Kota",
    "locationKo": "수라바야",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 100.000.000",
    "priceNum": 100000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Lokasi Premium Dekat UNESA Nol Jalan – Babatan Harga Take Over Hanya Rp100 Juta (Nego) Ingin langsung punya usaha tanpa ribet renovasi? Outlet ini sudah siap operasional, tinggal rebranding sesuai konsep Anda! Cocok untuk: * Coffee Shop * Tea & Beverage * Dessert & Ice Cream * Bakery * Snack Bar * F...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-cafe-beverage-outlet-siap-pakai-iid-946675781",
    "postedAt": "2026-07-11T15:59:39+07:00",
    "lat": -7.302,
    "lng": 112.668
  },
  {
    "id": "olx-941039689",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Laundry",
    "category": "뷰티 & 살롱",
    "location": "Pekanbaru Kota",
    "locationKo": "Pekanbaru Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 80.000.000",
    "priceNum": 80000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual Cepat Usaha Laundry Aktif Masih Berjalan – Siap Jalan & Lengkap Dijual cepat usaha laundry yang masih aktif, dan berjalan normal. Sudah satu tahun berjalan, masih ada masa sewa ruko hingga bulan Desember 2026. Alasan dijual karena tidak terurus dan sibuk di pekerjaan lainnya. Termasuk: 3 Mesi...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-iid-941039689",
    "postedAt": "2026-07-10T01:36:35+07:00",
    "lat": 0.524,
    "lng": 101.399
  },
  {
    "id": "olx-946624221",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Kebab",
    "category": "기타 사업",
    "location": "Sidoarjo  Kab.",
    "locationKo": "Sidoarjo  Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 35.000.000",
    "priceNum": 35000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "TAKE OVER USAHA KEBAB (Urgent!!) - Rombong dg semua barang (Wajan, LPG, dll) - Burner bakar daging + LPG - Bahan yang ada - Kotak Kebab - Kotak Burger - Bisa buka di delta sari",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-kebab-iid-946624221",
    "postedAt": "2026-07-09T12:29:58+07:00",
    "lat": -7.351,
    "lng": 112.768
  },
  {
    "id": "olx-946463892",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "take over laundry",
    "category": "세탁",
    "location": "Depok Kota",
    "locationKo": "데포",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 39.000.000",
    "priceNum": 39000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Over laundry kiloan di jalan utama Deket kos\" perumahan an jalur utama Karyawan ada bisa di lanjut Air tanah super bersih air nya laundry tinggal lanjut mesin\" masih gress smua",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-laundry-iid-946463892",
    "postedAt": "2026-07-08T13:25:51+07:00",
    "lat": -6.436,
    "lng": 106.835
  },
  {
    "id": "olx-946596627",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Photobooth",
    "category": "기타 사업",
    "location": "Depok Kota",
    "locationKo": "데포",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 35.000.000",
    "priceNum": 35000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Di jual usaha photobooth untuk mengisi acara Wedding, Birthday, Event lain. Proyeksi 1 sampai 2 bulan balik modal Di jual 2 set Lengkap untuk meneruskan usaha photobooth saya. Semua sudah lengkap terdiri dari Box photo 2 Layar 11.6 inc 2 Mini pc 2 Flash 2 Payung 2 Trigger 2 Camera dslr full set 2 Ba...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-photobooth-iid-946596627",
    "postedAt": "2026-07-08T11:13:04+07:00",
    "lat": -6.408,
    "lng": 106.764
  },
  {
    "id": "olx-923479901",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over oper usaha bakso pentol dan minuman boba posisi masi laba",
    "category": "기타 사업",
    "location": "Depok Kota",
    "locationKo": "데포",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 25.000.000",
    "priceNum": 25000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Over usaha bakso pentol dan minuman boba posisi masi laba, di jual karena udh g fokus ( hanya jual usahanya) tempat sewa Posisi di mall detos lapak sewa 1 bulan 3 jt udah termasuk service charge dll. Nanti bakso ready di support tinggal jual saja Minuman juga di ajarin ngelolanya Lokasi mall di area...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-oper-usaha-bakso-pentol-dan-minuman-boba-posisi-masi-laba-iid-923479901",
    "postedAt": "2026-07-07T13:46:50+07:00",
    "lat": -6.375,
    "lng": 106.823
  },
  {
    "id": "olx-946549413",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "TAKE OVER jual usaha tempat cuci mobil",
    "category": "뷰티 & 살롱",
    "location": "Tangerang Kota",
    "locationKo": "탕그랑",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 1.550.000.000",
    "priceNum": 1550000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "TAKE OVER USAHA CUCI MOBIL AKTIF - CIPONDOH TANGERANG Dijual / take over usaha cuci mobil yang sudah berjalan di area Cipondoh, Tangerang. Ini bukan jual alat bekas saja, tetapi paket take over lengkap: lokasi usaha, fasilitas cuci mobil, equipment, setup operasional, goodwill, dan sistem kerja yang...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-jual-usaha-tempat-cuci-mobil-iid-946549413",
    "postedAt": "2026-07-06T12:02:36+07:00",
    "lat": -6.186,
    "lng": 106.682
  },
  {
    "id": "olx-943355887",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Rumah tempat usaha masih berjalan di lokasi strategis mainroad Antapani",
    "category": "기타 사업",
    "location": "Bandung Kota",
    "locationKo": "반둥",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 2.850.000.000",
    "priceNum": 2850000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual Rumah / tempat usaha masih berjalan di lokasi strategis mainroad Antapani Bandung Spesifikasi : > Jumlah Lantai : 2 > Luas Tanah : 160 > Luas Bangunan : 250 > Orientasi Hadap : timur > Kamar Tidur : 3 > Kamar Mandi : 3 > Pasokan Listrik : 5500 watt > Sumber Air : PDAM > Garasi : - > Carport :...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/rumah-tempat-usaha-masih-berjalan-di-lokasi-strategis-mainroad-antapani-iid-943355887",
    "postedAt": "2026-07-06T06:55:49+07:00",
    "lat": -6.913,
    "lng": 107.659
  },
  {
    "id": "olx-946519656",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over warmindo",
    "category": "기타 사업",
    "location": "Sleman Kab.",
    "locationKo": "Sleman Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 15.000.000",
    "priceNum": 15000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Bagi yang ingin buka usaha warmindo bisa di lanjutkan usaha saya, mau di over beserta isinya karena saya sudah kerja dan tidak ada yang nungguin. Kontrakan masih panjang sampai Maret 2027. Posisi warmindo di jalan besar dan lingkungan nya banyak usaha yang lain. Yang mau tanya tanya dulu dipersilahk...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-warmindo-iid-946519656",
    "postedAt": "2026-07-04T21:00:12+07:00",
    "lat": -7.717,
    "lng": 110.396
  },
  {
    "id": "olx-931179452",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over Usaha Pangkalan Gas & Depot Air",
    "category": "카페 & 레스토랑",
    "location": "Cianjur Kab.",
    "locationKo": "Cianjur Kab.",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 355.000.000",
    "priceNum": 355000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual pangkalan gas di daerah kabupaten cianjur, sudah tinggal menjalankan usahanya saja dan nanti dikenalkan kepada langganan semuanya, alasan dijual karena ada usaha baru dan pindah kota Penjualan sudah termasuk : - tabung gas sebanyak 595 tabung - galon isi air minum 350 Pcs - mobil pick up mits...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-usaha-pangkalan-gas-depot-air-iid-931179452",
    "postedAt": "2026-07-02T15:55:06+07:00",
    "lat": -6.675,
    "lng": 107.219
  },
  {
    "id": "olx-946451560",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Rumah Hook dan Usaha Berjalan",
    "category": "카페 & 레스토랑",
    "location": "Jakarta Selatan",
    "locationKo": "자카르타 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 5.950.000.000",
    "priceNum": 5950000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Dijual Rumah Hook: cocok utk rumah tinggal dgn usaha berjalan, lokasi di jalan hidup dan ramai. Usaha yg berjalan saat ini: 7 kios & 3 kamar kost. Rumah tinggal: Jl Kostrad Pusri A 11, Petukangan Utara, Pesanggrahan, Jakarta Selatan. Sertifikat SHM Luas tanah 466 Luas Bangunan 220 1 Lantai Hadap Bar...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/rumah-hook-dan-usaha-berjalan-iid-946451560",
    "postedAt": "2026-07-01T22:34:23+07:00",
    "lat": -6.247,
    "lng": 106.761
  },
  {
    "id": "olx-944910041",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take Over cafe siap jualan",
    "category": "카페 & 레스토랑",
    "location": "Medan Kota",
    "locationKo": "Medan Kota",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 110.000.000",
    "priceNum": 110000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Take over cafe siap jualan tinggal masuk jual rugi separuh harga. Sudah termasuk semua barang dan peralatan. Jika serius datang ke lokasi dan nego ditempat",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-cafe-siap-jualan-iid-944910041",
    "postedAt": "2026-07-01T22:34:17+07:00",
    "lat": 3.568,
    "lng": 98.657
  },
  {
    "id": "olx-944258262",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Jual Tempat Usaha Berjalan Raya Jatipadang Pasar Minggu",
    "category": "기타 사업",
    "location": "Jakarta Selatan",
    "locationKo": "자카르타 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 26.000.000.000",
    "priceNum": 26000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Luas Tanah : 1095 m2 Luas Bangunan : 500 m2 Lantai 1: 1 Area Bengkel mobil 1 Area Indomaret 1 Area Food Court Area Parkir Luas Lantai 2: Listrik : Bengkel 6600, Indomaret 22000 Jalan Masuk : 2 mobil Sertifikat : SHM On Hand Food Court komdisi berjalan full Bengkel kondisi berjalan Indomaret kondisi ...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/jual-tempat-usaha-berjalan-raya-jatipadang-pasar-minggu-iid-944258262",
    "postedAt": "2026-07-01T12:16:32+07:00",
    "lat": -6.289,
    "lng": 106.839
  },
  {
    "id": "olx-942093547",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Take over franchise roti kupi / take over sewa ruko",
    "category": "기타 사업",
    "location": "Tangerang Selatan Kota",
    "locationKo": "탕그랑 남부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 31.000.000",
    "priceNum": 31000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Jual cepat paket usaha Roti Kupi. Asset lengkap tinggal pindah tempat atau lanjut di lokasi, peralatan lengkap bisa langsung jualan Harga sudah termasuk - Oven Getra 2 tray - Freezer GEA - Deck + loyang 17 pcs - Surat kemitraan tanpa expired date Masih bisa nego tipis Untuk ruko juga di take over , ...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/take-over-franchise-roti-kupi-take-over-sewa-ruko-iid-942093547",
    "postedAt": "2026-06-30T10:10:41+07:00",
    "lat": -6.258,
    "lng": 106.658
  },
  {
    "id": "olx-940990780",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Oper Usaha Produksi",
    "category": "제조",
    "location": "Jakarta Timur",
    "locationKo": "자카르타 동부",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 27.000.000",
    "priceNum": 27000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Punya uang tapi bingung mau usaha apa, ini sy tawarkan usaha sy yang sudah berjalan 6 tahun, tinggal beli bahan, produksi dan jual. Produk sudah dikenal se Indonesia, tinggal kembangkan saja dgn ide\" kreatif anda agar lebih maju. Spesifikasi: * Mesin siap produksi Baru * Diajarkan cara mengolah baha...",
    "facilities": [
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": false,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "완전인수",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/oper-usaha-produksi-iid-940990780",
    "postedAt": "2026-06-30T02:08:07+07:00",
    "lat": -6.337,
    "lng": 106.854
  },
  {
    "id": "olx-941713634",
    "type": "bisnis",
    "subtype": "akuisisi",
    "title": "Rumah Sayap Cikutra Jual Cepat ada Usaha yang berjalan Harga Negotible",
    "category": "카페 & 레스토랑",
    "location": "Bandung Kota",
    "locationKo": "반둥",
    "address": null,
    "monthlyRevenue": null,
    "monthlyRevenueNum": null,
    "profit": null,
    "price": "Rp 15.000.000.000",
    "priceNum": 15000000000,
    "established": null,
    "area": null,
    "floors": null,
    "description": "Rumah Usaha Strategis - Jumlah Lantai : 1 Lantai + Pav 2 Lt - Luas Tanah : 419 M2 - Luas Bangunan : 100 M2 ( Belum termasuk tambahan Bangunan Usaha yang Sedang Berjalan ) - Bentuk Tanah : Kotak ( Ngantong ) - Kamar Tidur: 6 - Kamar Mandi Dalam : 6 - Kamar Pembantu : 1 - Kamar Mandi Luar : 1 - Gudang...",
    "facilities": [
      "부동산 포함 매각",
      "운영 중 사업체",
      "OLX 실시간"
    ],
    "propertyIncluded": true,
    "whatsapp": null,
    "c2c": true,
    "images": "🏪",
    "badge": "부동산+사업체",
    "source": "olx.co.id",
    "sourceUrl": "https://www.olx.co.id/item/rumah-sayap-cikutra-jual-cepat-ada-usaha-yang-berjalan-harga-negotible-iid-941713634",
    "postedAt": "2026-06-29T12:11:28+07:00",
    "lat": -6.904,
    "lng": 107.624
  }
];
